topicsByLang.es = [
    "La sobremesa",
    "El qué dirán",
    "Madrugada",
    "La chancla",
    "Ser vs estar",
    "La quinceañera",
    "El Día de Muertos",
    "Tertulias",
    "La siesta",
    "El piropo",
    "Abuela vs mamá",
    "La bendición",
    "El cafecito de la mañana",
    "Echar de menos",
    "El mercado del domingo",
    "Tener vergüenza ajena",
    "La hora latina",
    "Compadrazgo",
    "El regateo",
    "Quedar bien vs ser sincero",
    "La lotería de Navidad",
    "El aguinaldo",
    "La cuesta de enero",
    "Dar el pésame",
    "Echar la casa por la ventana",
    "La primera comunión",
    "El bautizo",
    "La pedida de mano",
    "Tirar la casa por la ventana",
    "El orgullo de barrio",
    "La plaza del pueblo",
    "El paseo dominical",
    "Ir al tianguis",
    "El olor a tierra mojada",
    "Las posadas",
    "Romper la piñata",
    "El rosca de Reyes",
    "La Candelaria",
    "Semana Santa en familia",
    "Las mañanitas",
    "Pedir posada",
    "El grito de independencia",
    "Las fiestas patrias",
    "La verbena",
    "San Fermín y los encierros",
    "Las Fallas de Valencia",
    "La Tomatina",
    "El carnaval de Barranquilla",
    "La Feria de Abril",
    "Los Sanfermines",
    "El camino de Santiago",
    "La Noche de San Juan",
    "El Inti Raymi",
    "La Pachamama",
    "El tango en Buenos Aires",
    "La cueca chilena",
    "El jarabe tapatío",
    "Bailar cumbia",
    "El son jarocho",
    "La salsa como filosofía",
    "El merengue dominicano",
    "El reggaetón y la identidad",
    "La bachata y el desamor",
    "El bolero de siempre",
    "Cantar rancheras",
    "El mariachi a medianoche",
    "La trova cubana",
    "El flamenco y el duende",
    "La copla española",
    "El rock en español",
    "La nueva canción latinoamericana",
    "Calle 13 y la protesta",
    "Silvio Rodríguez y la esperanza",
    "Mercedes Sosa y la tierra",
    "Chavela Vargas y la rebeldía",
    "Manu Chao y el mestizaje",
    "Violeta Parra y el folclore",
    "El vallenato colombiano",
    "La música norteña",
    "Los corridos",
    "El huapango",
    "La zampoña y el charango",
    "Tocar guitarra en la fogata",
    "El cajón peruano",
    "La marimba",
    "Cantar en la ducha",
    "La serenata bajo el balcón",
    "El karaoke con amigos",
    "Dedicar una canción",
    "La playlist del desamor",
    "Llorar con una canción",
    "El himno del equipo",
    "La música que heredamos",
    "La canción de cuna",
    "Tararear sin saber la letra",
    "El primer concierto",
    "Un vinilo olvidado",
    "El casete grabado a mano",
    "La radio de madrugada",
    "Tortilla de patatas: con o sin cebolla",
    "El asado del domingo",
    "Las empanadas de la abuela",
    "El mole de mamá",
    "Tamales en diciembre",
    "El ceviche perfecto",
    "La paella valenciana",
    "Churros con chocolate",
    "El pan de muerto",
    "Tacos al pastor a las tres de la mañana",
    "El choripán del estadio",
    "Arepas vs pupusas",
    "El dulce de leche",
    "Las medialunas del desayuno",
    "El mate y la conversación",
    "Tomar café con pan dulce",
    "El atole de la abuela",
    "Agua de horchata",
    "El aguacate en todo",
    "Arroz con frijoles",
    "El sancocho de los domingos",
    "La bandeja paisa",
    "Un buen gazpacho en verano",
    "El cocido madrileño",
    "La fabada asturiana",
    "El puchero de la abuela",
    "Las migas del pastor",
    "El jamón ibérico",
    "Aceite de oliva",
    "La tortilla española vs la tortilla mexicana",
    "El picante: placer o castigo",
    "Comer con las manos",
    "Repetir plato sin culpa",
    "La receta secreta de familia",
    "Cocinar sin receta",
    "El olor de la cocina al llegar a casa",
    "El refrigerador de mamá",
    "El tupper que nunca vuelve",
    "Compartir comida con desconocidos",
    "El mercado vs el supermercado",
    "Las frutas de temporada",
    "El vendedor de elotes",
    "El camión de los tamales",
    "El heladero del barrio",
    "La tiendita de la esquina",
    "El puesto de jugos",
    "Las garnachas de la calle",
    "El olor a pan recién hecho",
    "El chocolate caliente en día de lluvia",
    "El café de olla",
    "Un mezcal en buena compañía",
    "La cerveza bien fría",
    "El vino de la casa",
    "La sangría del verano",
    "El tequila y la sal",
    "Brindar por los ausentes",
    "La última copa",
    "Ser de pueblo vs ser de ciudad",
    "La nostalgia del emigrante",
    "Volver al pueblo en verano",
    "El acento que delata",
    "Cambiar de acento según con quién hablas",
    "El spanglish",
    "El lunfardo porteño",
    "Los mexicanismos",
    "Las palabras que no tienen traducción",
    "Tutear o hablar de usted",
    "El doble sentido",
    "Los refranes de la abuela",
    "Más vale pájaro en mano",
    "Al que madruga Dios le ayuda",
    "No hay mal que por bien no venga",
    "Dime con quién andas y te diré quién eres",
    "El que mucho abarca poco aprieta",
    "Ojos que no ven corazón que no siente",
    "En boca cerrada no entran moscas",
    "Camarón que se duerme se lo lleva la corriente",
    "A falta de pan buenas son tortas",
    "Cría cuervos y te sacarán los ojos",
    "El albur mexicano",
    "La ironía como escudo",
    "Reírse de uno mismo",
    "El humor negro latino",
    "El chiste del momento incómodo",
    "Hacer reír para no llorar",
    "La risa contagiosa",
    "El amigo chistoso del grupo",
    "Los memes como lenguaje",
    "El sticker perfecto de WhatsApp",
    "El grupo de WhatsApp familiar",
    "Los audios de cinco minutos",
    "Mandar un audio llorando",
    "El visto y no contestado",
    "Responder mañana y olvidarlo",
    "La foto de perfil que dice todo",
    "Stalkear en redes sociales",
    "Borrar fotos del ex",
    "El estado de WhatsApp indirecto",
    "Publicar indirectas",
    "La vida real vs la vida en redes",
    "El influencer de pueblo",
    "Hacerse viral sin querer",
    "El primer celular",
    "Llamar por teléfono vs escribir",
    "Las cabinas telefónicas",
    "La carta escrita a mano",
    "El correo electrónico olvidado",
    "La tecnología y los abuelos",
    "Enseñarle tecnología a tus padres",
    "El internet del pueblo",
    "El cibercafé de la infancia",
    "Los videojuegos de la infancia",
    "La tele de la tarde",
    "Las telenovelas",
    "El Chavo del Ocho",
    "Los dibujos animados del sábado",
    "El cine de barrio",
    "Las películas de Cantinflas",
    "El realismo mágico",
    "Cien años de soledad",
    "García Márquez y Macondo",
    "Borges y los laberintos",
    "Neruda y el amor",
    "Octavio Paz y la soledad",
    "Cortázar y lo fantástico",
    "Isabel Allende y la memoria",
    "Rulfo y los murmullos",
    "Cervantes y los molinos",
    "Quijote: loco o visionario",
    "Frida Kahlo y el dolor",
    "Diego Rivera y los murales",
    "Botero y las formas",
    "Dalí y lo surreal",
    "Picasso y la reinvención",
    "Gaudí y la naturaleza",
    "El muralismo como protesta",
    "El arte callejero latino",
    "Los grafitis del barrio",
    "La artesanía indígena",
    "El barro y las manos",
    "Tejer como meditación",
    "Los alebrijes",
    "Las calaveras de azúcar",
    "El papel picado",
    "Los retablos peruanos",
    "Las molas panameñas",
    "La hamaca",
    "El sombrero vueltiao",
    "El poncho",
    "La guayabera",
    "Los huipiles",
    "Las alpargatas",
    "La ropa tendida al sol",
    "El uniforme escolar",
    "La bata de casa",
    "Vestirse para impresionar",
    "La primera impresión",
    "Juzgar por la apariencia",
    "El clasismo cotidiano",
    "La desigualdad invisible",
    "Ser rico vs ser feliz",
    "El dinero y la dignidad",
    "Trabajar para vivir vs vivir para trabajar",
    "El pluriempleo",
    "La economía informal",
    "Vender en la calle",
    "El emprendedor latino",
    "Hacer negocio de la necesidad",
    "La tienda del barrio que sobrevive",
    "El fiado y la confianza",
    "Pagar en abonos",
    "Deber y no poder pagar",
    "La tanda",
    "Prestar dinero a un amigo",
    "El que presta un libro no lo recupera",
    "Pedir prestado vs comprar",
    "La cultura del ahorro",
    "La alcancía de barro",
    "El colchón como banco",
    "Las remesas familiares",
    "Mandar dinero a casa",
    "El sacrificio del migrante",
    "Cruzar la frontera",
    "El sueño americano desde el sur",
    "La maleta del emigrante",
    "Extrañar la comida de casa",
    "El olor de la tierra natal",
    "El regreso que no es igual",
    "Ser extranjero en tu propia tierra",
    "La identidad partida",
    "Ni de aquí ni de allá",
    "El privilegio de tener pasaporte",
    "Las fronteras invisibles",
    "La patria es la infancia",
    "La bandera y lo que significa",
    "El himno que eriza la piel",
    "La selección nacional",
    "El fútbol como religión",
    "El gol del siglo",
    "Maradona: genio y figura",
    "Messi y la perseverancia",
    "El clásico del fútbol",
    "La cancha del barrio",
    "Jugar en la calle",
    "La cascarita",
    "El portero que nadie quiere ser",
    "El árbitro y la injusticia",
    "La porra del estadio",
    "Los cánticos de la hinchada",
    "El domingo de fútbol",
    "Ver el partido en familia",
    "Gritar gol hasta quedarse ronco",
    "La repetición del gol",
    "El penal decisivo",
    "Perder la final",
    "El descenso del equipo",
    "La lealtad al equipo",
    "Cambiar de equipo: traición",
    "El béisbol caribeño",
    "La lucha libre mexicana",
    "El boxeo como salida",
    "Los toros: tradición o crueldad",
    "La charrería",
    "El rodeo",
    "Los juegos de mesa en familia",
    "La lotería mexicana",
    "El dominó en la acera",
    "Las cartas españolas",
    "La rayuela",
    "Las canicas",
    "El trompo",
    "La cuerda de saltar",
    "Las escondidas",
    "La roña",
    "Jugar hasta que oscurezca",
    "La calle como patio de juegos",
    "Los amigos del barrio",
    "El mejor amigo de la infancia",
    "El vecino chismoso",
    "La señora del edificio",
    "El portero que todo lo sabe",
    "El barrio que ya no existe",
    "La casa de la infancia",
    "El cuarto compartido",
    "La litera de arriba o de abajo",
    "Dormir en casa de la abuela",
    "La casa del pueblo",
    "El patio interior",
    "La azotea",
    "El balcón como mirador",
    "Tender la ropa en el balcón",
    "Los ruidos del vecino",
    "La música a todo volumen",
    "La fiesta del vecino un martes",
    "Pedir silencio sin ser antipático",
    "La convivencia en comunidad",
    "Las juntas de vecinos",
    "El ascensor como confesionario",
    "El saludo en el portal",
    "Conocer a tus vecinos",
    "El perro del vecino",
    "Pasear al perro y socializar",
    "El gato callejero del barrio",
    "Adoptar vs comprar mascotas",
    "El primer perro",
    "El animal que te marcó la infancia",
    "La familia numerosa",
    "El hermano mayor y la responsabilidad",
    "El hermano menor y los privilegios",
    "El hijo único",
    "Los primos como hermanos",
    "La reunión familiar obligatoria",
    "La Navidad en familia",
    "La cena de Nochebuena",
    "Los villancicos",
    "El Nacimiento vs el árbol",
    "Los Reyes Magos vs Papá Noel",
    "La carta a los Reyes",
    "Dejar zapatos en la ventana",
    "El carbón para el niño malo",
    "Abrir regalos a medianoche",
    "Año Nuevo y las doce uvas",
    "Los propósitos de Año Nuevo",
    "La ropa interior roja en Año Nuevo",
    "Salir con la maleta para viajar",
    "Quemar el año viejo",
    "Los fuegos artificiales",
    "Abrazar a desconocidos a medianoche",
    "El brindis de Año Nuevo",
    "Enero: mes de reflexión o depresión",
    "El Blue Monday latino",
    "San Valentín: comercial o romántico",
    "El Día del Amor y la Amistad",
    "Regalar flores",
    "La serenata como declaración",
    "Pedir noviazgo formalmente",
    "Presentar al novio en casa",
    "La aprobación de los padres",
    "El suegro difícil",
    "La suegra: mito y realidad",
    "Los cuñados",
    "La familia política",
    "Casarse por la iglesia",
    "La boda civil vs la religiosa",
    "El vestido de la novia",
    "El vals del padre",
    "El ramo de la novia",
    "La víbora de la mar",
    "El pastel de bodas",
    "La luna de miel",
    "El primer año de casados",
    "La convivencia en pareja",
    "Los roles de género en el hogar",
    "El machismo cotidiano",
    "El feminismo en Latinoamérica",
    "Las mujeres que cambiaron la historia",
    "Las abuelas de Plaza de Mayo",
    "La lucha por los derechos",
    "El voto femenino",
    "La brecha salarial",
    "El techo de cristal",
    "Ser madre y trabajar",
    "La maternidad no romantizada",
    "El instinto maternal: mito o realidad",
    "La paternidad moderna",
    "El padre ausente",
    "Romper el ciclo familiar",
    "Lo que heredamos sin querer",
    "Los traumas generacionales",
    "Sanar para no repetir",
    "La terapia en Latinoamérica",
    "El estigma de la salud mental",
    "Pedir ayuda no es debilidad",
    "La ansiedad de la generación actual",
    "La presión de tenerlo todo resuelto",
    "El síndrome del impostor",
    "Compararse con los demás",
    "La envidia disfrazada de admiración",
    "El éxito ajeno",
    "Celebrar los logros de otros",
    "La competencia entre hermanos",
    "La competencia en el trabajo",
    "El compañero que se lleva el crédito",
    "El jefe que no escucha",
    "La reunión que pudo ser un correo",
    "Trabajar desde casa",
    "La oficina en la sala",
    "Separar vida personal y laboral",
    "El burnout latino",
    "El descanso como derecho",
    "Las vacaciones que no alcanzaron",
    "Viajar con presupuesto ajustado",
    "El mochilero latinoamericano",
    "Dormir en aeropuertos",
    "Perderse en una ciudad nueva",
    "El regateo en el mercado artesanal",
    "Comprar recuerdos innecesarios",
    "La foto turística obligatoria",
    "Volver del viaje y ser el mismo",
    "El viaje que te cambió la vida",
    "La ruta del Che",
    "Machu Picchu al amanecer",
    "Las ruinas mayas",
    "Teotihuacán y el misterio",
    "La Habana vieja",
    "Cartagena de Indias",
    "Buenos Aires y su melancolía",
    "Ciudad de México y su caos hermoso",
    "Barcelona y la nostalgia",
    "Madrid de noche",
    "Sevilla y el azahar",
    "Granada y la Alhambra",
    "Las Islas Galápagos",
    "El Salar de Uyuni",
    "La selva amazónica",
    "El desierto de Atacama",
    "Los Andes y la altura",
    "El Caribe y el tiempo detenido",
    "La playa como terapia",
    "El mar y la libertad",
    "El sonido de las olas",
    "La arena entre los dedos",
    "Caminar descalzo",
    "El atardecer en la playa",
    "El amanecer en la montaña",
    "La fogata en la playa",
    "La brisa del mar",
    "La hamaca entre palmeras",
    "El olor a sal",
    "El agua de coco en la playa",
    "Nadar de noche",
    "La luna llena sobre el agua",
    "Las estrellas en el campo",
    "El cielo sin contaminación",
    "La Vía Láctea desde el pueblo",
    "El campo vs la ciudad",
    "La tierra que se cultiva",
    "El maíz como identidad",
    "La milpa",
    "El café de altura",
    "Cosechar lo que siembras",
    "El ciclo de la tierra",
    "La lluvia esperada",
    "La sequía y el miedo",
    "El cambio climático en primera persona",
    "Los ríos que se secan",
    "Los bosques que desaparecen",
    "El jaguar y la selva",
    "El cóndor y la montaña",
    "El quetzal y la libertad",
    "La mariposa monarca",
    "El colibrí y la paciencia",
    "La tortuga y el tiempo",
    "El perro callejero",
    "El gallo del amanecer",
    "Los pájaros de la tarde",
    "La naturaleza como maestra",
    "Hablarle a las plantas",
    "El jardín de la abuela",
    "La maceta en el balcón",
    "El árbol del parque",
    "Abrazar un árbol sin ironía",
    "El volcán dormido",
    "La tierra que tiembla",
    "Vivir sobre fallas sísmicas",
    "El terremoto y la solidaridad",
    "Los huracanes del Caribe",
    "La fuerza de la naturaleza",
    "Reconstruir después del desastre",
    "La solidaridad del vecino",
    "El voluntariado",
    "Ayudar sin esperar nada",
    "La generosidad del que menos tiene",
    "El pobre que invita a comer",
    "Compartir lo poco que hay",
    "La abundancia que no es material",
    "Ser rico en experiencias",
    "La felicidad simple",
    "Un vaso de agua fría en el calor",
    "La sombra de un árbol",
    "Sentarse a no hacer nada",
    "El silencio del campo",
    "La paz de la madrugada",
    "El insomnio y las preguntas",
    "Las tres de la mañana",
    "Pensar de más a medianoche",
    "El despertador como enemigo",
    "El primer café del día",
    "La rutina que salva",
    "La rutina que asfixia",
    "Romper la rutina",
    "El lunes por la mañana",
    "El viernes por la tarde",
    "La libertad del sábado",
    "El domingo de angustia",
    "La tarde de domingo",
    "El tiempo que se escapa",
    "El reloj que no para",
    "La prisa como forma de vida",
    "La lentitud como resistencia",
    "El placer de ir despacio",
    "Caminar sin destino",
    "Perderse a propósito",
    "Tomar el camino largo",
    "Los atajos que alargan",
    "La paciencia como virtud",
    "La impaciencia como motor",
    "Esperar sin saber cuánto falta",
    "La sala de espera",
    "Hacer fila",
    "La burocracia latina",
    "El trámite interminable",
    "El sello que falta",
    "Volver mañana",
    "La ventanilla equivocada",
    "El funcionario amable",
    "El sistema que no funciona",
    "La corrupción cotidiana",
    "La mordida",
    "Hacer lo correcto cuando nadie ve",
    "La honestidad incómoda",
    "Decir la verdad vs ser diplomático",
    "La mentira piadosa",
    "La verdad a medias",
    "Prometer y no cumplir",
    "La palabra de honor",
    "El apretón de manos",
    "La confianza que tarda y se pierde rápido",
    "Perdonar sin olvidar",
    "El rencor que pesa",
    "Soltar lo que duele",
    "El orgullo que estorba",
    "Pedir perdón de verdad",
    "Disculparse sin excusas",
    "Reconciliarse después de años",
    "El abrazo que sana",
    "El abrazo latino",
    "El beso en la mejilla",
    "Saludar con contacto físico",
    "La distancia física y emocional",
    "El espacio personal",
    "Hablar de cerca",
    "Gesticular al hablar",
    "Hablar con las manos",
    "Subir la voz sin enojarse",
    "El tono que ofende",
    "Las palabras que no se olvidan",
    "Lo que no se dice también se siente",
    "El silencio que dice todo",
    "Callar por respeto o por miedo",
    "Hablar por hablar",
    "Escuchar de verdad",
    "La conversación profunda",
    "La conversación superficial",
    "Hablar del clima cuando no hay tema",
    "La charla del taxi",
    "El taxista filósofo",
    "El conductor de autobús",
    "El transporte público como aventura",
    "El metro en hora punta",
    "Ceder el asiento",
    "Los vendedores del metro",
    "El músico del metro",
    "El artista callejero",
    "La propina",
    "El valet parking",
    "Estacionar en doble fila",
    "El tráfico de la ciudad",
    "La hora pico",
    "El claxon como comunicación",
    "Manejar en Latinoamérica",
    "Las señales que nadie respeta",
    "La calle sin banqueta",
    "Los baches como prueba",
    "La infraestructura que falta",
    "El puente peatonal vacío",
    "La bicicleta en la ciudad",
    "Caminar de noche",
    "La inseguridad cotidiana",
    "El miedo a salir de noche",
    "La ciudad que duerme y la que no",
    "La vida nocturna",
    "La discoteca del viernes",
    "El antro y las memorias borrosas",
    "El after que nadie planeó",
    "La cruda moral",
    "Arrepentirse al día siguiente",
    "Las fotos que hay que borrar",
    "La resaca del domingo",
    "El caldo de pollo para la cruda",
    "Los chilaquiles de la mañana",
    "El remedio de la abuela",
    "La medicina tradicional",
    "El curandero del pueblo",
    "La limpia con huevo",
    "El mal de ojo",
    "El empacho",
    "El susto como enfermedad",
    "Los remedios con hierbas",
    "El té de manzanilla",
    "El vaporrú en el pecho",
    "La fe que cura",
    "La Virgen de Guadalupe",
    "La Virgen del Rocío",
    "Los santos patronos",
    "La religión heredada",
    "Cuestionar la fe de los padres",
    "La fe sin religión",
    "La espiritualidad latina",
    "El sincretismo religioso",
    "Los altares en casa",
    "La veladora encendida",
    "Rezar antes de dormir",
    "La señal de la cruz",
    "El escapulario",
    "La promesa al santo",
    "La peregrinación",
    "Caminar de rodillas",
    "La fe que mueve",
    "El milagro cotidiano",
    "La esperanza como motor",
    "La resiliencia latina",
    "Salir adelante",
    "Echarle ganas",
    "El optimismo del que tiene poco",
    "Ser agradecido",
    "Contar las bendiciones",
    "La queja como deporte",
    "Quejarse sin actuar",
    "La resignación",
    "El conformismo",
    "Conformarse vs agradecer",
    "Querer más vs ser feliz con lo que hay",
    "La ambición bien entendida",
    "El éxito sin perder la esencia",
    "Olvidar de dónde vienes",
    "Las raíces que se niegan",
    "El mestizaje",
    "La identidad cultural",
    "Ser latino en el extranjero",
    "La diáspora latina",
    "La comunidad latina en el mundo",
    "El orgullo latino",
    "Los estereotipos sobre los latinos",
    "Romper estereotipos",
    "La diversidad dentro de Latinoamérica",
    "México no es toda Latinoamérica",
    "España no es toda Europa",
    "Los acentos que unen y dividen",
    "El español como puente",
    "La riqueza del idioma",
    "Las lenguas indígenas que se pierden",
    "El náhuatl vivo",
    "El quechua y la resistencia",
    "El guaraní como lengua oficial",
    "El mapudungun y la tierra",
    "Las palabras prestadas",
    "Los anglicismos que invaden",
    "El lenguaje inclusivo en español",
    "La Real Academia vs el pueblo",
    "Las palabras nuevas",
    "El lenguaje de los jóvenes",
    "El lenguaje de los abuelos",
    "Las groserías como expresión",
    "La grosería cariñosa",
    "Insultar con creatividad",
    "El eufemismo latino",
    "Decir que sí cuando es no",
    "La cortesía que confunde",
    "Ser educado por obligación",
    "La hipocresía social",
    "Guardar las apariencias",
    "La doble moral",
    "Lo que se dice en público vs en privado",
    "El chisme como institución",
    "La vecina que todo lo sabe",
    "La comadre",
    "El compadre",
    "La lealtad del compadre",
    "Los amigos que son familia",
    "La familia que eliges",
    "El amigo de toda la vida",
    "Crecer y distanciarse",
    "Los amigos que se pierden",
    "Reencontrarse después de años",
    "El abrazo del reencuentro",
    "La nostalgia de la infancia",
    "Los juegos de la infancia",
    "El recreo escolar",
    "La tiendita de la escuela",
    "El chicle y los dulces",
    "Los dulces mexicanos",
    "El chamoy y el miguelito",
    "La paleta de hielo",
    "El raspado del parque",
    "Los elotes del carrito",
    "El algodón de azúcar",
    "La feria del pueblo",
    "La rueda de la fortuna",
    "Los caballitos del carrusel",
    "El payaso del cumpleaños",
    "La fiesta infantil",
    "Las sillas musicales",
    "Ponerle la cola al burro",
    "La piñata de siete picos",
    "Los dulces que caen de la piñata",
    "El brincolin",
    "Crecer demasiado rápido",
    "La inocencia perdida",
    "El primer amor",
    "La carta de amor",
    "El recado en clase",
    "El corazón en el pupitre",
    "Mandar flores a escondidas",
    "El novio secreto",
    "La relación a escondidas",
    "El primer beso",
    "El beso robado",
    "La mano sudada",
    "El nervio de declararse",
    "El miedo al rechazo",
    "El rechazo que forma",
    "El amor no correspondido",
    "Querer a quien no te quiere",
    "Amar en silencio",
    "La friendzone",
    "El amor imposible",
    "Romeo y Julieta en el barrio",
    "Los amores prohibidos",
    "La distancia en el amor",
    "El amor a distancia",
    "Las relaciones por internet",
    "El match que no funciona",
    "La cita a ciegas",
    "El ligue en el bar",
    "El cortejo antiguo vs el moderno",
    "La galantería",
    "El romanticismo muerto",
    "El detalle pequeño",
    "Una flor sin motivo",
    "Cocinar para alguien",
    "El lenguaje del amor latino",
    "Demostrar amor con comida",
    "El amor de la abuela en un plato",
    "La comida como abrazo",
    "La sopa de la enfermedad",
    "Cuidar al otro cuando está enfermo",
    "La vulnerabilidad en pareja",
    "Llorar frente a alguien",
    "El hombre que no llora",
    "La masculinidad tóxica",
    "Redefinir ser hombre",
    "La ternura como valentía",
    "La fuerza de la suavidad",
    "El equilibrio entre duro y sensible",
    "Mostrar debilidad",
    "Pedir ayuda",
    "La soledad elegida",
    "La soledad impuesta",
    "Estar solo sin sentirse solo",
    "El ermitaño moderno",
    "La necesidad de pertenencia",
    "Formar parte de algo",
    "La tribu",
    "El grupo de amigos",
    "La pandilla del barrio",
    "La banda de música del colegio",
    "El equipo de fútbol del barrio",
    "El club social",
    "La asociación de vecinos",
    "La comunidad que protege",
    "La comunidad que juzga",
    "Ser diferente en un pueblo",
    "La diversidad en Latinoamérica",
    "La comunidad LGBTQ+ latina",
    "La aceptación familiar",
    "Salir del clóset en familia latina",
    "El orgullo de ser quien eres",
    "La autenticidad",
    "Ser uno mismo",
    "La máscara social",
    "El personaje que creamos",
    "El yo de las redes vs el yo real",
    "La vulnerabilidad como conexión",
    "Abrirse a los demás",
    "La confianza mutua",
    "El secreto compartido",
    "El secreto que pesa",
    "Guardar un secreto ajeno",
    "La traición de confianza",
    "El chisme que destruye",
    "La reputación",
    "El nombre de la familia",
    "El apellido que pesa",
    "La herencia del apellido",
    "El nombre que te pusieron",
    "El apodo cariñoso",
    "El apodo cruel",
    "El sobrenombre del barrio",
    "La identidad en el nombre",
    "Ser tocayo",
    "Los diminutivos en español",
    "El ito y el ita de todo",
    "El cariño en las palabras",
    "Amor como forma de dirigirse",
    "Mi vida, mi cielo, mi sol",
    "Los piropos creativos",
    "El piropo que incomoda",
    "El respeto en la calle",
    "Caminar como mujer en la ciudad",
    "Los espacios seguros",
    "La noche que no es para todas",
    "El miedo como compañero",
    "La valentía cotidiana",
    "Enfrentar lo desconocido",
    "El primer día de escuela",
    "La maestra que te marcó",
    "El maestro rural",
    "La escuela pública",
    "La educación como privilegio",
    "La educación como derecho",
    "Estudiar con hambre",
    "La beca que cambió todo",
    "Ser el primero de la familia en la universidad",
    "El título que cuelga en la pared",
    "La graduación de los hijos",
    "El orgullo de los padres",
    "La expectativa de los padres",
    "La carrera que tus padres eligieron",
    "Estudiar lo que te gusta vs lo que da dinero",
    "El artista incomprendido",
    "Vivir del arte",
    "El escritor que no publica",
    "El poeta de café",
    "El pintor de domingos",
    "La creatividad reprimida",
    "El niño que dibujaba en los márgenes",
    "La imaginación como refugio",
    "El libro que te cambió",
    "La biblioteca pública",
    "El olor a libro viejo",
    "Subrayar libros: sí o no",
    "El libro prestado que no volvió",
    "Las librerías de viejo",
    "El puesto de revistas",
    "La historieta mexicana",
    "Mafalda y sus verdades",
    "Condorito y el humor simple",
    "El Chapulín Colorado",
    "La comedia mexicana",
    "El cine latinoamericano",
    "Las películas de Almodóvar",
    "El cine de Guillermo del Toro",
    "El cine argentino",
    "El cine brasileño",
    "La telenovela como espejo social",
    "El melodrama latino",
    "La villana de la telenovela",
    "El galán de la telenovela",
    "La señora de la limpieza sabia",
    "Los personajes que nos representan",
    "El humor como crítica social",
    "La sátira política",
    "El periodismo valiente",
    "La libertad de prensa",
    "Las noticias que no salen",
    "La desinformación",
    "Las fake news en el grupo familiar",
    "Creer todo lo que ves",
    "El pensamiento crítico",
    "Dudar como ejercicio",
    "La duda existencial",
    "El sentido de la vida",
    "La crisis de los cuarenta",
    "La crisis de los veinte",
    "No saber qué hacer con tu vida",
    "La presión de los treinta",
    "Los treinta son los nuevos veinte",
    "Envejecer en Latinoamérica",
    "Envejecer con dignidad",
    "La vejez y la sabiduría",
    "Los ancianos en la familia latina",
    "El asilo: abandono o necesidad",
    "Cuidar a los padres mayores",
    "La deuda con los padres",
    "Lo que nunca le dijiste a tus padres",
    "La conversación pendiente",
    "El perdón que llega tarde",
    "El adiós que no alcanzaste",
    "El duelo latino",
    "El velorio",
    "El entierro",
    "Las flores en el cementerio",
    "Visitar la tumba",
    "Hablar con los muertos",
    "Los muertos que viven en nosotros",
    "La muerte como parte de la vida",
    "El altar de muertos",
    "La ofrenda",
    "El cempasúchil",
    "El pan de muerto y el recuerdo",
    "La calavera literaria",
    "Reírse de la muerte",
    "La muerte con humor",
    "La Catrina",
    "El más allá",
    "La reencarnación",
    "El karma latino",
    "Lo que va vuelve",
    "La justicia divina",
    "La justicia terrenal que falla",
    "El sistema que no cambia",
    "La protesta pacífica",
    "La marcha ciudadana",
    "El pañuelo como símbolo",
    "La pancarta con mensaje",
    "La voz del pueblo",
    "El grito que no se calla",
    "La plaza como espacio político",
    "El Zócalo",
    "La Puerta del Sol",
    "La Plaza de Mayo",
    "La Plaza Bolívar",
    "Los héroes de la independencia",
    "Bolívar y el sueño americano",
    "San Martín y la libertad",
    "Hidalgo y el grito",
    "La historia que nos contaron",
    "La historia que nos ocultaron",
    "La conquista y sus heridas",
    "El legado colonial",
    "Las ciudades coloniales",
    "La arquitectura que cuenta historias",
    "Las iglesias barrocas",
    "El sincretismo en la arquitectura",
    "Los pueblos mágicos",
    "El turismo y la autenticidad",
    "La gentrificación del barrio",
    "El barrio que pierde su esencia",
    "La modernidad que arrasa",
    "Lo antiguo vs lo moderno",
    "La tecnología en manos de todos",
    "El smartphone como extensión del cuerpo",
    "La adicción al celular",
    "Un día sin internet",
    "La desconexión digital",
    "El detox tecnológico",
    "Volver a lo analógico",
    "Escribir a mano",
    "La caligrafía del abuelo",
    "Las fotos impresas",
    "El álbum de fotos familiar",
    "La foto en la sala",
    "El retrato de la abuela",
    "Los recuerdos que se guardan",
    "Los recuerdos que se inventan",
    "La memoria selectiva",
    "Recordar lo bueno",
    "Olvidar lo malo",
    "El olvido como defensa",
    "Lo que quisieras olvidar",
    "Lo que nunca olvidarás",
    "El momento que lo cambió todo",
    "El día que creciste",
    "El día que te fuiste de casa",
    "La independencia que asusta",
    "Vivir solo por primera vez",
    "Aprender a cocinar por necesidad",
    "La primera lavada de ropa",
    "Llamar a mamá para preguntar una receta",
    "Los errores de principiante",
    "El error que enseñó más",
    "Fracasar y volver a empezar",
    "La segunda oportunidad",
    "Reinventarse",
    "Empezar de cero a los cuarenta",
    "Nunca es tarde",
    "La edad como número",
    "La experiencia como escuela",
    "La calle como universidad",
    "Los libros vs la experiencia",
    "La teoría vs la práctica",
    "El título vs el talento",
    "La meritocracia: mito o realidad",
    "Los contactos que abren puertas",
    "La palanca",
    "El amiguismo",
    "La rosca",
    "El poder y la responsabilidad",
    "El liderazgo verdadero",
    "Mandar vs liderar",
    "El jefe que inspira",
    "El jefe que controla",
    "La autonomía en el trabajo",
    "El primer sueldo",
    "El sueldo que no alcanza",
    "Vivir al día",
    "El fin de quincena",
    "La quincena que se va en un día",
    "Los gastos hormiga",
    "El café caro de cada día",
    "Ahorrar para el futuro",
    "El futuro incierto",
    "La incertidumbre como constante",
    "Planificar vs improvisar",
    "La improvisación latina",
    "Resolver sobre la marcha",
    "El ingenio mexicano",
    "La creatividad de la necesidad",
    "Hacer mucho con poco",
    "El alambre que arregla todo",
    "La cinta adhesiva como solución",
    "Si sirve no lo toques",
    "La reparación casera",
    "El vecino que sabe de todo",
    "El cuñado que todo lo arregla",
    "El tutorial de YouTube",
    "Aprender solo",
    "El autodidacta",
    "La curiosidad como motor",
    "Preguntar sin pena",
    "La pregunta tonta que no existe",
    "El que sabe sabe y el que no pregunta",
    "La humildad intelectual",
    "Aceptar que no sabes",
    "Cambiar de opinión",
    "La terquedad",
    "Tener la razón vs tener paz",
    "La discusión en la cena",
    "La política en la mesa",
    "La religión en la mesa",
    "Los temas prohibidos",
    "Hablar de dinero",
    "Hablar de muerte",
    "Hablar de sexo",
    "Los tabúes latinos",
    "Lo que no se habla en familia",
    "El secreto a voces",
    "La oveja negra de la familia",
    "Ser el diferente",
    "No encajar",
    "Buscar tu lugar",
    "El sentido de pertenencia",
    "El hogar como sentimiento",
    "Casa no es lo mismo que hogar",
    "Donde cuelgas el sombrero",
    "Las mudanzas",
    "Empacar una vida en cajas",
    "El objeto que siempre llevas contigo",
    "La cobija de la infancia",
    "El peluche viejo",
    "El juguete favorito",
    "El regalo que nunca olvidas",
    "El regalo perfecto",
    "El regalo que no gustó",
    "Agradecer de verdad",
    "La gratitud diaria",
    "Lo que damos por sentado",
    "El agua limpia",
    "La electricidad como privilegio",
    "El techo sobre la cabeza",
    "La mesa servida",
    "La salud que no valoramos",
    "El cuerpo que nos carga",
    "Escuchar al cuerpo",
    "El dolor como mensaje",
    "La enfermedad como pausa",
    "El hospital público",
    "La espera en urgencias",
    "El doctor de cabecera",
    "La farmacia como consultorio",
    "Automedicarse",
    "El remedio casero vs la medicina",
    "La fe en la ciencia",
    "La ciencia en Latinoamérica",
    "La fuga de cerebros",
    "Irse para crecer",
    "Quedarse para construir",
    "Irse vs quedarse",
    "La culpa de irse",
    "El orgullo de quedarse",
    "Transformar desde adentro",
    "El activismo local",
    "El cambio que empieza en casa",
    "Barrer tu banqueta",
    "Ser buen vecino",
    "La responsabilidad ciudadana",
    "Votar con conciencia",
    "La democracia imperfecta",
    "El populismo",
    "Las promesas de campaña",
    "El político que olvida",
    "La memoria política",
    "Los ciclos que se repiten",
    "La historia que no aprendemos",
    "El presente como construcción",
    "El futuro que queremos",
    "El mundo que heredamos",
    "Lo que dejamos a los hijos",
    "La responsabilidad generacional",
    "Ser el puente entre dos mundos",
    "La traducción cultural",
    "Explicar tu cultura",
    "La cultura que se pierde",
    "La tradición que se adapta",
    "Lo viejo con ojos nuevos",
    "Innovar respetando raíces",
    "El progreso y el costo",
    "Ganar y perder al mismo tiempo",
    "Los sacrificios necesarios",
    "Lo que dejas para avanzar",
    "Soltar para crecer",
    "El apego que frena",
    "El desapego budista latino",
    "La meditación en el caos",
    "Respirar en medio del ruido",
    "El ruido de la ciudad",
    "El silencio como lujo",
    "La calma después de la tormenta",
    "La tormenta que limpia",
    "Bailar bajo la lluvia",
    "Mojarse sin paraguas",
    "El paraguas que nunca traes",
    "El clima como excusa",
    "Llegar tarde por el tráfico",
    "Llegar tarde por costumbre",
    "La puntualidad como respeto",
    "La impuntualidad como cultura",
    "El tiempo elástico",
    "Ahorita como concepto filosófico",
    "Mañana como promesa eterna",
    "Luego luego",
    "Ya merito",
    "Al rato",
    "El tiempo circular",
    "El eterno retorno latino",
    "Lo que fue volverá",
    "La nostalgia del futuro",
    "Imaginar lo que viene",
    "Soñar despierto",
    "El sueño como motor",
    "El soñador y el pragmático",
    "Los pies en la tierra",
    "La cabeza en las nubes",
    "El equilibrio imposible",
    "Buscar el centro",
    "El justo medio",
    "Ni mucho ni poco",
    "La moderación latina",
    "Todo o nada",
    "La pasión desbordada",
    "El corazón antes que la razón",
    "Tomar decisiones con el estómago",
    "La corazonada",
    "La intuición de la madre",
    "El presentimiento",
    "El sexto sentido",
    "La superstición cotidiana",
    "El martes trece",
    "El viernes trece",
    "Pasar debajo de una escalera",
    "El gato negro",
    "Romper un espejo",
    "Tocar madera",
    "La herradura en la puerta",
    "El trébol de cuatro hojas",
    "La suerte y el destino",
    "El destino escrito",
    "Crear tu propio destino",
    "La libre voluntad",
    "Las decisiones que definen",
    "El camino no tomado",
    "La puerta que no abriste",
    "La oportunidad que dejaste ir",
    "El arrepentimiento",
    "Vivir sin arrepentirse",
    "Hacer las paces con el pasado",
    "Aceptar lo que fue",
    "El pasado que construye",
    "El presente que es regalo",
    "Vivir el momento",
    "El aquí y ahora",
    "La presencia plena",
    "Estar sin estar",
    "La mente en otro lado",
    "Volver a conectar",
    "La conexión humana",
    "Mirarse a los ojos",
    "La conversación sin celular",
    "La mesa sin pantallas",
    "Comer juntos",
    "La familia alrededor de la mesa",
    "El ritual de la comida",
    "Bendecir los alimentos",
    "Dar gracias antes de comer",
    "El primer bocado",
    "Comer en silencio",
    "Comer con prisa",
    "Saborear despacio",
    "El último pedazo que nadie toma",
    "Ofrecer antes de servirse",
    "La hospitalidad latina",
    "Mi casa es tu casa",
    "Recibir visitas sin aviso",
    "La casa siempre abierta",
    "El café siempre listo",
    "Ofrecer comida hasta que acepten",
    "La insistencia cariñosa",
    "No aceptar un no",
    "La terquedad del amor",
    "Querer a la fuerza",
    "Dejar ir con amor",
    "El amor que libera",
    "El amor que atrapa",
    "Los celos como prueba de amor",
    "Los celos como prisión",
    "La confianza en la pareja",
    "La comunicación en la pareja",
    "Lo que no se habla se pudre",
    "Las palabras que curan",
    "Las palabras que destruyen",
    "El poder de la palabra",
    "La palabra empeñada",
    "El valor de la palabra dicha",
    "Hablar es plata, callar es oro",
    "Agua que no has de beber déjala correr",
    "No hay mal que dure cien años",
    "Después de la tormenta viene la calma",
    "Al mal tiempo buena cara",
    "Más vale tarde que nunca",
    "El que persevera alcanza",
    "Poco a poco se llega lejos",
    "Paso a paso",
    "Un día a la vez",
    "La paciencia del campesino",
    "Sembrar sin ver frutos",
    "La cosecha que otros recogerán",
    "Plantar un árbol sabiendo que no verás su sombra",
    "El legado invisible",
    "Lo que enseñas sin saber",
    "El ejemplo como enseñanza",
    "Predicar con el ejemplo",
    "La coherencia entre decir y hacer",
    "La integridad silenciosa",
    "El héroe cotidiano",
    "La madre que madruga",
    "El padre que trabaja doble",
    "Los abuelos que crían",
    "La tía que es segunda madre",
    "El tío que cuenta historias",
    "Las historias del abuelo",
    "La memoria oral",
    "Los cuentos de antes de dormir",
    "La leyenda de La Llorona",
    "El Coco",
    "El Chupacabras",
    "La Luz Mala",
    "El Silbón",
    "Las leyendas urbanas",
    "Los fantasmas del pueblo",
    "La casa embrujada del barrio",
    "Contar historias de terror",
    "El miedo a la oscuridad",
    "La lámpara encendida toda la noche",
    "Dormir con la puerta abierta",
    "El ruido que tranquiliza",
    "La tele encendida para dormir",
    "El radio de fondo",
    "La voz que arrulla",
    "El arrullo de la madre",
    "La canción que te duerme",
    "Los sueños recurrentes",
    "El sueño que parece real",
    "Soñar con quien ya no está",
    "Despertar y sentir su ausencia",
    "La silla vacía en la mesa",
    "El lugar que ya no se ocupa",
    "Seguir poniendo el plato extra",
    "La costumbre que se resiste a morir",
    "Lo que permanece después de la pérdida",
    "El amor que trasciende",
    "La huella que dejamos",
    "Ser recordado",
    "Vivir en la memoria de otros",
    "La inmortalidad en las palabras",
    "El poema que sobrevive",
    "La canción que perdura",
    "El mural que resiste",
    "La historia que se cuenta de nuevo",
    "El cuento que nunca envejece",
    "La verdad que cambia con el tiempo",
    "La perspectiva que todo transforma",
    "Ver el mundo con otros ojos",
    "Ponerse en los zapatos del otro",
    "La empatía como revolución",
    "Escuchar antes de juzgar",
    "El juicio rápido",
    "La primera piedra",
    "Los errores ajenos",
    "La compasión como fuerza",
    "Ayudar sin juzgar",
    "La mano que se extiende",
    "El desconocido que ayuda",
    "La bondad inesperada",
    "El acto de bondad anónimo",
    "Pagar el café del siguiente",
    "Sonreír a un extraño",
    "La sonrisa como lenguaje universal",
    "La amabilidad como resistencia",
    "Ser amable en un mundo difícil",
    "La ternura en tiempos duros",
    "La suavidad como fortaleza",
    "Lo blando que no se quiebra",
    "El bambú que se dobla pero no se rompe",
    "La flexibilidad como supervivencia",
    "Adaptarse sin perderse",
    "Fluir con lo que viene",
    "Aceptar lo que no puedes cambiar",
    "Cambiar lo que sí puedes",
    "La sabiduría de distinguirlos",
    "La serenidad buscada",
    "La paz interior",
    "El refugio interno",
    "El lugar seguro dentro de ti",
    "Volver a uno mismo",
    "El viaje interior",
    "Conocerse de verdad",
    "El espejo que no miente",
    "Mirarse sin filtros",
    "La honestidad con uno mismo",
    "Las excusas que nos contamos",
    "La zona de confort",
    "Salir de lo conocido",
    "El vértigo del cambio",
    "El cambio que da miedo",
    "El miedo que paraliza",
    "El miedo que impulsa",
    "La valentía no es ausencia de miedo",
    "Actuar con miedo",
    "El salto de fe",
    "Confiar en el proceso",
    "El camino se hace al andar",
    "Caminante no hay camino",
    "La poesía en lo cotidiano",
    "La belleza de lo imperfecto",
    "El wabi-sabi latino",
    "Lo roto que se repara con oro",
    "Las cicatrices que cuentan historias",
    "La marca que nos identifica",
    "El tatuaje con significado",
    "La piel como lienzo",
    "El cuerpo como territorio",
    "La libertad del cuerpo",
    "Bailar solo en casa",
    "Cantar a todo pulmón en el carro",
    "La libertad de los pequeños actos",
    "El placer de lo prohibido",
    "La travesura inocente",
    "El niño interior",
    "No perder la capacidad de asombro",
    "Maravillarse con lo simple",
    "La primera vez que ves el mar",
    "La primera nevada",
    "El primer vuelo en avión",
    "La primera vez lejos de casa",
    "Las primeras veces que recordamos",
    "Las últimas veces que no sabemos",
    "La última vez que jugaste en la calle",
    "La última cena de la abuela",
    "El último abrazo sin saber que lo era",
    "Vivir como si fuera la última vez",
    "La urgencia de vivir",
    "La vida que se escapa",
    "Atrapar el instante",
    "El momento perfecto",
    "La felicidad fugaz",
    "La alegría profunda",
    "La diferencia entre placer y felicidad",
    "La paz que no depende de nada",
    "La libertad interior",
    "Ser libre de verdad",
    "Las cadenas invisibles",
    "Los barrotes que construimos",
    "La jaula dorada",
    "La comodidad como trampa",
    "El riesgo como libertad",
    "Apostar por uno mismo",
    "Creer en ti cuando nadie más lo hace",
    "La fe en uno mismo",
    "La duda que fortalece",
    "El fracaso como escalón",
    "Caer y levantarse",
    "La dignidad de levantarse",
    "No rendirse",
    "Echarle ganas aunque duela",
    "La fuerza que no sabías que tenías",
    "Descubrir tu propia fuerza",
    "El poder de la voluntad",
    "La disciplina silenciosa",
    "El esfuerzo invisible",
    "Lo que nadie ve detrás del éxito",
    "El aplauso que llega tarde",
    "El reconocimiento que no necesitas",
    "Hacer las cosas por convicción",
    "La vocación como brújula",
    "Encontrar tu propósito",
    "El propósito que cambia",
    "Reinventarse a cualquier edad",
    "La vida como obra en construcción",
    "El borrador eterno",
    "La perfección como enemiga",
    "Lo suficientemente bueno",
    "Terminar lo que empiezas",
    "El proyecto abandonado",
    "La idea que nunca se ejecutó",
    "El sueño postergado",
    "Mañana empiezo",
    "La procrastinación latina",
    "Hacer todo a última hora",
    "La presión del deadline",
    "Trabajar mejor bajo presión",
    "El caos organizado",
    "El desorden creativo",
    "La mesa llena de papeles",
    "El cajón de los recuerdos",
    "La caja de zapatos con fotos",
    "Los objetos que no podemos tirar",
    "El apego a las cosas",
    "Las cosas que cuentan historias",
    "El reloj del abuelo",
    "La cadena de oro de la abuela",
    "El anillo de bodas gastado",
    "La cruz del bautizo",
    "El escapulario heredado",
    "Los objetos con alma",
    "La casa que respira recuerdos",
    "Las paredes que escucharon todo",
    "El árbol que plantó tu padre",
    "La tierra donde creciste",
    "Los pies descalzos en la tierra",
    "El polvo del camino"
];
