topicsByLang.de = [
    "Wanderlust",
    "Gemütlichkeit",
    "Feierabend",
    "Fernweh",
    "Stammtisch",
    "Weltanschauung",
    "Sonntagsruhe",
    "Torschlusspanik",
    "Schadenfreude",
    "Heimat",
    "Kindergarten",
    "Zeitgeist",
    "Fingerspitzengefühl",
    "Sehnsucht",
    "Lebensfreude",
    "Weltschmerz",
    "Heimweh",
    "Geborgenheit",
    "Zweisamkeit",
    "Innerer Schweinehund",
    "Frühjahrsmüdigkeit",
    "Ohrwurm",
    "Backpfeifengesicht",
    "Fremdschämen",
    "Schnapsidee",
    "Kopfkino",
    "Weichei",
    "Dreikäsehoch",
    "Handschuhschneeballwerfer",
    "Vergangenheitsbewältigung",
    "Doppelgänger",
    "Angst vor dem Montag",
    "Die Ruhe vor dem Sturm",
    "Brot und Butter",
    "Der frühe Vogel fängt den Wurm",
    "Morgenstund hat Gold im Mund",
    "Wer rastet, der rostet",
    "Der Ton macht die Musik",
    "Übung macht den Meister",
    "Lieber spät als nie",
    "Der Apfel fällt nicht weit vom Stamm",
    "Alles hat ein Ende, nur die Wurst hat zwei",
    "Dienst ist Dienst und Schnaps ist Schnaps",
    "Aller Anfang ist schwer",
    "Da liegt der Hund begraben",
    "Das ist nicht das Gelbe vom Ei",
    "Ich verstehe nur Bahnhof",
    "Jemandem auf den Keks gehen",
    "Ins kalte Wasser springen",
    "Die Kirche im Dorf lassen",
    "Sonntagsfahrer",
    "Die Qual der Wahl",
    "Abendbrot",
    "Kaffeeklatsch",
    "Kaffee und Kuchen um vier",
    "Biergartenkultur",
    "Die erste Maß auf dem Oktoberfest",
    "Brezn oder Brezel",
    "Schweinshaxe und Knödel",
    "Sauerkraut als Nationalgericht",
    "Currywurst an der Imbissbude",
    "Döner als deutsches Kulturgut",
    "Die Vielfalt des deutschen Brotes",
    "Schwarzbrot vs. Weißbrot",
    "Maultaschen – schwäbische Seele",
    "Spätzle selber schaben",
    "Lebkuchen im Advent",
    "Glühwein auf dem Weihnachtsmarkt",
    "Stollen aus Dresden",
    "Butterbrot zum Abendbrot",
    "Kartoffelsalat – warm oder kalt",
    "Sonntagsbraten bei der Familie",
    "Pfannkuchen, Berliner oder Krapfen",
    "Handkäs mit Musik",
    "Spargelsaison",
    "Erdbeerzeit",
    "Federweißer im Herbst",
    "Apfelwein in Sachsenhausen",
    "Weinfest an der Mosel",
    "Schützenfest im Dorf",
    "Karneval in Köln",
    "Fasching in München",
    "Fastnacht in Mainz",
    "Rosenmontag",
    "Helau oder Alaaf",
    "Maibaumaufstellen",
    "Erntedankfest",
    "Martinszug mit Laterne",
    "Nikolaustag",
    "Heiligabend",
    "Zwischen den Jahren",
    "Silvesterknaller und Bleigießen",
    "Der erste Schnee im Winter",
    "Schlittenfahren am Hang",
    "Eislaufen auf dem zugefrorenen See",
    "Wandern im Schwarzwald",
    "Radtour am Rhein",
    "Spaziergang im Herbstlaub",
    "Pilze sammeln im Oktober",
    "Nordsee oder Ostsee",
    "Sylt und seine Strandkörbe",
    "Rügen und die Kreidefelsen",
    "Bodensee im Sommer",
    "Die Zugspitze erklimmen",
    "Allgäuer Almwiesen",
    "Sonnenuntergang über den Alpen",
    "Nebelmorgen im Tal",
    "Herbstwald in goldenen Farben",
    "Kirschblüte in Bonn",
    "Der Geruch von frisch gemähtem Gras",
    "Rapsfelder im Mai",
    "Störche auf dem Dach",
    "Der Kuckuck im Frühling",
    "Schrebergarten und Laubenpieper",
    "Das Wetter als Gesprächsthema",
    "Regenwetter und gute Laune",
    "Fön und Kopfschmerzen",
    "Wenn der Föhn bläst",
    "Bauernregeln",
    "Die vier Jahreszeiten in Deutschland",
    "Deutsche Pünktlichkeit",
    "Deutsche Gründlichkeit",
    "Ordnung muss sein",
    "Mülltrennung als Lebensphilosophie",
    "Pfandsystem und Nachhaltigkeit",
    "Der gelbe Sack",
    "Recyclinghof am Samstag",
    "Das Duale System",
    "Energiewende",
    "Atomausstieg",
    "Kohleausstieg und Strukturwandel",
    "Windräder in der Landschaft",
    "Solardach auf dem Eigenheim",
    "Tempolimit auf der Autobahn",
    "Freie Fahrt für freie Bürger",
    "Stau auf der A1",
    "Autobahnraststätte",
    "Baustellen ohne Ende",
    "Schottergärten vs. Vorgärten",
    "Nachbarschaftsstreit wegen Hecken",
    "Rasenmähen am Sonntag",
    "Mittagsruhe einhalten",
    "Sonntagsbrötchen vom Bäcker",
    "Brötchentüte am Türgriff",
    "Der Gang zum Amt",
    "Bürokratie und Formulare",
    "Warten beim Bürgeramt",
    "Die elektronische Gesundheitskarte",
    "Faxgerät im Büro",
    "Digitalisierung in deutschen Schulen",
    "Funklöcher auf dem Land",
    "Bargeld oder Kartenzahlung",
    "Deutsche und ihr Bargeld",
    "Girokonto und Schufa",
    "Bausparen als Lebensziel",
    "Riester-Rente",
    "Die Angst vor Altersarmut",
    "Eigenheim oder Miete",
    "Mietpreisbremse",
    "Wohnungssuche in Berlin",
    "Gentrifizierung im Kiez",
    "Altbau oder Neubau",
    "Plattenbau-Charme",
    "Gründerzeit-Stuck",
    "Fachwerkhäuser",
    "Schlösser und Burgen",
    "Neuschwanstein – Kitsch oder Kunst",
    "Brandenburger Tor",
    "Kölner Dom",
    "Dresdner Frauenkirche",
    "Berliner Mauer und Wiedervereinigung",
    "Der 9. November",
    "Tag der Deutschen Einheit",
    "Ossi und Wessi – noch aktuell?",
    "Die Wende und ihre Folgen",
    "Treuhand und Nachwendezeit",
    "Solidaritätszuschlag",
    "Das Grundgesetz",
    "Artikel 1: Die Würde des Menschen",
    "Meinungsfreiheit und ihre Grenzen",
    "Föderalismus in Deutschland",
    "Bundesländer und ihre Eigenheiten",
    "Bayern und der Rest der Republik",
    "Norddeutscher Humor",
    "Schwäbische Sparsamkeit",
    "Rheinischer Frohsinn",
    "Berliner Schnauze",
    "Sächsisch als Dialekt",
    "Plattdeutsch bewahren",
    "Bairisch verstehen",
    "Hochdeutsch als Kompromiss",
    "Dialekt oder Hochsprache",
    "Denglisch im Alltag",
    "Anglizismen in der Sprache",
    "Gendern in der deutschen Sprache",
    "Duzen oder Siezen",
    "Das Sie als Respektform",
    "Vom Sie zum Du wechseln",
    "Der Hamburger Sie",
    "Höflichkeit im Wandel",
    "Bitte und Danke sagen",
    "Grüßen im Treppenhaus",
    "Smalltalk im Aufzug",
    "Blickkontakt in der U-Bahn",
    "Deutsche Direktheit",
    "Ehrlichkeit oder Taktlosigkeit",
    "Konstruktive Kritik geben",
    "Das Vier-Augen-Gespräch",
    "Die offene Tür im Büro",
    "Flurfunk und Gerüchte",
    "Betriebsrat und Mitbestimmung",
    "Tarifvertrag und Gewerkschaft",
    "Work-Life-Balance auf Deutsch",
    "Gleitzeit und Vertrauensarbeitszeit",
    "Überstunden als Normalzustand",
    "Burnout und Prävention",
    "Krankmeldung am Montag",
    "Der gelbe Schein",
    "Kur und Reha",
    "Gesetzliche Krankenkasse",
    "Vorsorgeuntersuchung",
    "Hausarzt des Vertrauens",
    "Wartezimmer-Erfahrungen",
    "Apothekenpflicht",
    "Rezeptfreie Hausmittel",
    "Kamillentee als Allheilmittel",
    "Zwiebelsaft gegen Husten",
    "Der Sonntagsspaziergang",
    "Nordic Walking im Park",
    "Vereinsleben in Deutschland",
    "Fußballverein und Ehrenamt",
    "Bundesliga-Samstag",
    "Die Sportschau um 18 Uhr",
    "Champions League am Dienstag",
    "WM-Fieber alle vier Jahre",
    "Das Sommermärchen 2006",
    "Der Mauerfall und Fußball",
    "Lokalderby und Rivalität",
    "Fangesänge im Stadion",
    "Stehplatz oder Sitzplatz",
    "Bratwurst im Stadion",
    "Dortmunder Südtribüne",
    "50+1-Regel im Fußball",
    "Handball-Begeisterung",
    "Biathlon im Fernsehen",
    "Skispringen an Neujahr",
    "Vierschanzentournee",
    "Formel 1 am Sonntag",
    "Nürburgring-Nostalgie",
    "Turnverein um die Ecke",
    "DLRG und Schwimmabzeichen",
    "Seepferdchen als Meilenstein",
    "Sportabzeichen in der Schule",
    "Bundesjugendspiele",
    "Schulsport und Völkerball",
    "Goethe und Schiller",
    "Faust – erster oder zweiter Teil",
    "Kafka und die Verwandlung",
    "Thomas Mann und die Buddenbrooks",
    "Hesse und der Steppenwolf",
    "Brecht und das epische Theater",
    "Rilke und die Dinge",
    "Die Romantik als Epoche",
    "Sturm und Drang",
    "Aufklärung und Vernunft",
    "Die Weimarer Klassik",
    "Expressionismus in der Kunst",
    "Bauhaus und Design",
    "Die Brücke und Der Blaue Reiter",
    "Caspar David Friedrich",
    "Albrecht Dürer",
    "Ludwig van Beethoven",
    "Johann Sebastian Bach",
    "Richard Wagner – Genie oder Umstritten",
    "Robert Schumann und Clara",
    "Händel und sein Messias",
    "Berliner Philharmoniker",
    "Bayreuth und die Festspiele",
    "Salzburger Festspiele",
    "Wiener Philharmoniker",
    "Neujahrskonzert aus Wien",
    "Oper oder Musical",
    "Tatort am Sonntagabend",
    "Das Sandmännchen",
    "Die Sendung mit der Maus",
    "Löwenzahn und Peter Lustig",
    "Pumuckl",
    "Jim Knopf und Lukas",
    "Die unendliche Geschichte",
    "Momo und die Zeitdiebe",
    "Pippi Langstrumpf auf Deutsch",
    "Die Augsburger Puppenkiste",
    "Loriot und der deutsche Humor",
    "Heinz Erhardt",
    "Otto Waalkes",
    "Gerhard Polt",
    "Karl Valentin",
    "Der deutsche Kabarett-Abend",
    "Politisches Kabarett",
    "Die Anstalt im ZDF",
    "Heute-Show",
    "Tagesschau um 20 Uhr",
    "Brennpunkt im Ersten",
    "Anne Will oder Maybrit Illner",
    "Talkshow-Kultur",
    "Öffentlich-rechtlicher Rundfunk",
    "GEZ und Rundfunkbeitrag",
    "Privatfernsehen",
    "Streaming vs. lineares Fernsehen",
    "Deutsche Filmkunst",
    "Das Leben der Anderen",
    "Good Bye, Lenin!",
    "Der Untergang",
    "Die Blechtrommel",
    "Metropolis von Fritz Lang",
    "Das Cabinet des Dr. Caligari",
    "Der deutsche Expressionismus im Film",
    "Berlinale",
    "Deutscher Filmpreis",
    "Neue Deutsche Welle",
    "Kraftwerk und Elektro",
    "Rammstein – Provokation als Kunst",
    "Die Toten Hosen",
    "Die Ärzte",
    "Nena und 99 Luftballons",
    "Herbert Grönemeyer",
    "Udo Lindenberg",
    "Falco – Der Kommissar",
    "Deutschrap und Straßenkultur",
    "Schlager und Volksmusik",
    "Helene Fischer",
    "Andrea Berg",
    "Heino und die Volkslieder",
    "Techno und die Loveparade",
    "Berghain und Türpolitik",
    "Clubkultur in Berlin",
    "Wacken Open Air",
    "Rock am Ring",
    "Reeperbahn Festival",
    "Donauinselfest in Wien",
    "Montreux Jazz Festival",
    "Klassik Open Air",
    "Straßenmusik in der Fußgängerzone",
    "Erster Schultag und die Schultüte",
    "Schulranzen packen",
    "Bundesland bestimmt den Lehrplan",
    "G8 oder G9 – die Gymnasiumdebatte",
    "Abitur als Meilenstein",
    "Numerus Clausus",
    "Studieren in Deutschland",
    "Semesterticket",
    "Mensa-Essen",
    "WG-Leben",
    "WG-Casting",
    "Der Putzplan in der WG",
    "Studium oder Ausbildung",
    "Duales Studium",
    "Meisterbrief und Handwerk",
    "Lehrjahre sind keine Herrenjahre",
    "Gesellenprüfung bestehen",
    "Handwerk hat goldenen Boden",
    "Fachkräftemangel",
    "Brain Drain aus ländlichen Gebieten",
    "Pendeln zwischen Stadt und Land",
    "Deutsche Bahn und Verspätungen",
    "Der ICE nach Berlin",
    "Bahncard 50",
    "9-Euro-Ticket-Nostalgie",
    "Deutschlandticket",
    "S-Bahn oder U-Bahn",
    "Fahrradstadt Münster",
    "Radwege in Kopenhagen und Deutschland",
    "Lastenrad als Statussymbol",
    "E-Auto oder Verbrenner",
    "Diesel-Fahrverbote",
    "TÜV und Hauptuntersuchung",
    "ADAC als gelber Engel",
    "Führerschein mit 17",
    "Die erste Fahrstunde",
    "Elternzeit und Elterngeld",
    "Kita-Platz-Suche",
    "Tagesmutter oder Kindergarten",
    "Einschulung mit sechs oder sieben",
    "Waldkindergarten",
    "Spielplatzkultur",
    "Sandkasten-Diplomatie",
    "Kindergeburtstag organisieren",
    "Laternenumzug im November",
    "Adventskalender basteln",
    "Weihnachtsfeier im Büro",
    "Wichteln unter Kollegen",
    "Betriebsausflug",
    "Sommerfest der Firma",
    "Jubiläum im Unternehmen",
    "Abschied vom Kollegen",
    "Der letzte Arbeitstag",
    "Rente mit 63 oder 67",
    "Ruhestand und dann",
    "Ehrenamt im Alter",
    "Senioren im Internet",
    "Enkelkinder betreuen",
    "Mehrgenerationenhaus",
    "Pflege der Eltern",
    "Pflegeheim oder häusliche Pflege",
    "Patientenverfügung",
    "Vorsorgevollmacht",
    "Sterbehilfe-Debatte",
    "Organspende – ja oder nein",
    "Der Tod als Tabuthema",
    "Trauer und Abschied nehmen",
    "Bestattungskultur im Wandel",
    "Friedhof als Ort der Stille",
    "Erinnerungskultur in Deutschland",
    "Stolpersteine",
    "Holocaust-Gedenktag",
    "Nie wieder – was bedeutet das heute",
    "Verantwortung und Erinnerung",
    "Geschichte im Schulunterricht",
    "Zeitzeugengespräche",
    "Museumsbesuche mit Kindern",
    "Deutsches Museum in München",
    "Pergamonmuseum in Berlin",
    "Grünes Gewölbe in Dresden",
    "Documenta in Kassel",
    "Art Basel",
    "Straßenkunst und Graffiti",
    "Streetart in Berlin",
    "Flohmarkt am Sonntag",
    "Trödelmarkt und Schnäppchen",
    "Antiquariat und alte Bücher",
    "Die Buchmesse in Frankfurt",
    "Leipziger Buchmesse",
    "Vorlesetag",
    "Bibliotheken als dritte Orte",
    "Das gedruckte Buch vs. E-Reader",
    "Zeitungen am Frühstückstisch",
    "Die Zeit oder die Süddeutsche",
    "Spiegel oder Focus",
    "Bild-Zeitung – Fluch oder Segen",
    "Podcast-Boom in Deutschland",
    "Lanz und Precht philosophieren",
    "Gemischtes Hack",
    "True Crime auf Deutsch",
    "Hörspiele und Hörbücher",
    "Die drei Fragezeichen",
    "TKKG und Fünf Freunde",
    "Benjamin Blümchen",
    "Bibi Blocksberg",
    "Kassetten überspielen",
    "Schallplatten sammeln",
    "Vinyl-Revival",
    "Musikkassetten-Nostalgie",
    "Walkman-Erinnerungen",
    "GameBoy unter der Bettdecke",
    "Commodore 64",
    "Die erste E-Mail",
    "Das Internet in den 90ern",
    "StudiVZ und SchülerVZ",
    "Das Nokia 3310",
    "SMS-Sprache",
    "WhatsApp-Gruppen der Familie",
    "Eltern auf Facebook",
    "TikTok und die Jugend",
    "Influencer als Berufswunsch",
    "YouTube-Deutschland",
    "Datenschutz und DSGVO",
    "Recht auf Vergessenwerden",
    "Überwachung und Freiheit",
    "Der gläserne Bürger",
    "Algorithmen und Filterblasen",
    "Fake News erkennen",
    "Medienkompetenz in der Schule",
    "Künstliche Intelligenz im Alltag",
    "Automatisierung und Arbeitsplätze",
    "Industrie 4.0",
    "Made in Germany",
    "Mittelstand als Rückgrat",
    "Hidden Champions",
    "Familienunternehmen über Generationen",
    "Garagenfirmen und Start-ups",
    "Silicon Valley vs. Berlin",
    "Deutsche Gründerszene",
    "Bürokratie für Gründer",
    "Scheitern als Chance",
    "Insolvenz und Neuanfang",
    "Hartz IV und seine Folgen",
    "Bürgergeld",
    "Sozialstaat und Eigenverantwortung",
    "Solidarität in der Gesellschaft",
    "Ehrenamt und Engagement",
    "Freiwilliges Soziales Jahr",
    "Bundesfreiwilligendienst",
    "Zivildienst-Erinnerungen",
    "Wehrpflicht – abschaffen oder behalten",
    "Bundeswehr und Gesellschaft",
    "Zeitenwende",
    "Sicherheitspolitik in Europa",
    "NATO und Deutschland",
    "Europäische Union – wohin",
    "Deutschland in Europa",
    "Schengen und offene Grenzen",
    "Grenzkontrollen und Freiheit",
    "Migration und Integration",
    "Willkommenskultur 2015",
    "Sprachkurse für Geflüchtete",
    "Integration durch Sport",
    "Vielfalt im Klassenzimmer",
    "Multikulti im Alltag",
    "Doppelte Staatsbürgerschaft",
    "Einbürgerungstest",
    "Was bedeutet deutsch sein",
    "Leitkultur-Debatte",
    "Verfassungspatriotismus",
    "Demokratie verteidigen",
    "Wahlpflicht oder Wahlrecht",
    "Sonntagsfrage",
    "Koalitionsverhandlungen",
    "Große Koalition",
    "Ampelkoalition",
    "Opposition und Kontrolle",
    "Der Bundestag als Arbeitsparlament",
    "Bundesrat und Länderkammer",
    "Das Bundesverfassungsgericht",
    "Gewaltenteilung",
    "Demonstrationsrecht",
    "Fridays for Future in Deutschland",
    "Klimaschutz und Wohlstand",
    "Verkehrswende",
    "Heizungsdebatte",
    "Wärmepumpe oder Gasheizung",
    "Gebäudesanierung",
    "Balkonkraftwerk",
    "Bürgerenergie",
    "Flächenverbrauch und Versiegelung",
    "Hochwasserschutz",
    "Dürresommer",
    "Waldsterben 2.0",
    "Borkenkäfer und Fichtensterben",
    "Aufforstung und Mischwald",
    "Nationalpark Bayerischer Wald",
    "Wattenmeer und UNESCO",
    "Biosphärenreservat",
    "Wolf zurück in Deutschland",
    "Wildtiere in der Stadt",
    "Füchse in Berlin",
    "Wildschweine im Vorgarten",
    "Bienensterben und Volksbegehren",
    "Insektenhotel bauen",
    "Urban Gardening",
    "Permakultur im eigenen Garten",
    "Selbstversorgung als Trend",
    "Foodsharing und Containern",
    "Tafel und Lebensmittelrettung",
    "Mindesthaltbarkeitsdatum und Verschwendung",
    "Biomarkt oder Discounter",
    "Aldi und Lidl erobern die Welt",
    "Wochenmarkt am Samstag",
    "Metzger des Vertrauens",
    "Fleischkonsum in der Diskussion",
    "Vegetarisch oder vegan",
    "Schnitzel ohne Fleisch",
    "Hafermilch im Kaffee",
    "Craft Beer aus der Region",
    "Reinheitsgebot von 1516",
    "Biervielfalt in Deutschland",
    "Riesling und Spätburgunder",
    "Weinanbaugebiete",
    "Winzergenossenschaft",
    "Obstbrand vom Bauernhof",
    "Schnaps nach dem Essen",
    "Verdauungsschnaps – Mythos oder Wahrheit",
    "Kräuterlikör und Tradition",
    "Mineralwasser mit oder ohne",
    "Sprudel oder still",
    "Leitungswasser trinken",
    "Die deutsche Kaffeekultur",
    "Filterkaffee-Renaissance",
    "Espresso oder Milchkaffee",
    "Das Café als Wohnzimmer",
    "Kuchen backen am Wochenende",
    "Schwarzwälder Kirschtorte",
    "Apfelstrudel",
    "Sachertorte in Wien",
    "Kaiserschmarrn auf der Alm",
    "Wiener Schnitzel",
    "Tafelspitz",
    "Schweizer Fondue",
    "Raclette an Silvester",
    "Rösti und Birchermüesli",
    "Schweizer Schokolade",
    "Österreichischer Schmäh",
    "Wiener Kaffeehaus",
    "Heuriger in Wien",
    "Almabtrieb im Herbst",
    "Jodeln in den Alpen",
    "Schuhplattler",
    "Trachten und Dirndl",
    "Lederhose – Tradition oder Kostüm",
    "Volksfest und Fahrgeschäfte",
    "Kirmes auf dem Dorf",
    "Dorfgemeinschaft",
    "Landflucht und Stadtleben",
    "Gentrifizierung vs. Leerstand",
    "Coworking auf dem Land",
    "Homeoffice in der Provinz",
    "Pendlerpauschale",
    "Zweitwohnung in der Stadt",
    "Der tägliche Stau",
    "Fahrgemeinschaft bilden",
    "Park and Ride",
    "Das 49-Euro-Ticket im Alltag",
    "Carsharing und Mobilität",
    "E-Scooter auf dem Gehweg",
    "Verkehrschaos in der Innenstadt",
    "Fußgängerzone als Lebensraum",
    "Einkaufsstraße oder Onlineshop",
    "Innenstädte sterben aus",
    "Kaufhaus-Nostalgie",
    "Der Tante-Emma-Laden",
    "Bäckerei-Sterben",
    "Handwerk und Nachwuchssorgen",
    "Meisterzwang – pro und contra",
    "Schwarzarbeit und Pfusch",
    "Nachbarschaftshilfe",
    "Nebenan.de und lokale Netzwerke",
    "Ehrenamt im Sportverein",
    "Freiwillige Feuerwehr",
    "THW im Einsatz",
    "DRK und Blutspende",
    "Erste-Hilfe-Kurs auffrischen",
    "Zivilcourage zeigen",
    "Hinschauen statt Wegsehen",
    "Mobbing am Arbeitsplatz",
    "Mobbing in der Schule",
    "Cybermobbing bei Jugendlichen",
    "Mediensucht erkennen",
    "Bildschirmzeit begrenzen",
    "Digital Detox am Wochenende",
    "Offline-Zeiten einrichten",
    "Das Handy im Restaurant",
    "Tischmanieren heute",
    "Anstand und Benehmen",
    "Knigge – noch zeitgemäß",
    "Der feste Händedruck",
    "Visitenkarte überreichen",
    "Business-Etikette in Deutschland",
    "Dresscode im Büro",
    "Casual Friday",
    "Duzen im Start-up",
    "Hierarchien in Unternehmen",
    "Flache Hierarchien – Wunsch oder Wirklichkeit",
    "Führungskraft oder Teamplayer",
    "Diversity im Unternehmen",
    "Frauenquote in Vorständen",
    "Gender Pay Gap",
    "Equal Pay Day",
    "Vereinbarkeit von Familie und Beruf",
    "Väter in Elternzeit",
    "Teilzeit als Karrierebremse",
    "Alles unter einen Hut bringen",
    "Perfektionismus als Falle",
    "Gut genug statt perfekt",
    "Prokrastination überwinden",
    "Selbstdisziplin aufbauen",
    "Gewohnheiten ändern",
    "Neujahrsvorsätze und ihr Scheitern",
    "Der innere Kritiker",
    "Selbstzweifel und Imposter-Syndrom",
    "Mut zur Lücke",
    "Fehlerkultur in Deutschland",
    "Aus Fehlern lernen",
    "Resilienz aufbauen",
    "Achtsamkeit im Alltag",
    "Meditation für Skeptiker",
    "Yoga im Trend",
    "Waldbaden als Therapie",
    "Naturheilkunde und Schulmedizin",
    "Homöopathie – Glaube oder Wirkung",
    "Osteopathie und Physiotherapie",
    "Rückenschmerzen der Deutschen",
    "Sitzen als neues Rauchen",
    "Stehschreibtisch im Büro",
    "Ergonomie am Arbeitsplatz",
    "Gesund durch den Winter",
    "Grippe oder Erkältung",
    "Impfdebatte",
    "Masken im Alltag nach Corona",
    "Long Covid und die Folgen",
    "Pandemie und Zusammenhalt",
    "Lockdown-Erinnerungen",
    "Homeschooling-Erfahrungen",
    "Zoom-Müdigkeit",
    "Hybrides Arbeiten",
    "New Work und Sinnsuche",
    "Purpose statt Gehalt",
    "Generation Z im Beruf",
    "Boomer und Millennials",
    "Generationenkonflikt",
    "OK Boomer",
    "Jugendsprache verstehen",
    "Cringe und sheesh",
    "Unwort des Jahres",
    "Wort des Jahres",
    "Jugendwort des Jahres",
    "Sprache und Macht",
    "Framing in der Politik",
    "Wahlkampf und Versprechen",
    "Politikverdrossenheit",
    "Demokratie und Beteiligung",
    "Bürgerbegehren",
    "Petitionen einreichen",
    "Stammtisch-Politik",
    "Wahlabend vor dem Fernseher",
    "Hochrechnung und Prognose",
    "Koalitionspoker",
    "Die Kanzlerfrage",
    "Bundespräsident als Integrationsfigur",
    "Der Zapfenstreich",
    "Staatsbesuch und Protokoll",
    "Diplomatie und Kompromiss",
    "Verhandlungskunst",
    "Kompromiss als Schwäche oder Stärke",
    "Konsens finden",
    "Streitkultur pflegen",
    "Diskutieren ohne zu streiten",
    "Die Kunst des Zuhörens",
    "Reden ist Silber, Schweigen ist Gold",
    "Das ungesagte Wort",
    "Zwischen den Zeilen lesen",
    "Ironie und Sarkasmus",
    "Schwarzer Humor",
    "Galgenhumor",
    "Lachen als Medizin",
    "Das Lächeln eines Fremden",
    "Freundlichkeit als Revolution",
    "Hilfsbereitschaft im Alltag",
    "Türaufhalten und Danke sagen",
    "Komplimente geben",
    "Lob aussprechen",
    "Anerkennung im Beruf",
    "Wertschätzung in der Beziehung",
    "Die fünf Sprachen der Liebe",
    "Beziehung und Alltag",
    "Zusammenziehen",
    "Der erste gemeinsame Ikea-Besuch",
    "Möbel aufbauen als Beziehungstest",
    "Kompromisse in der Beziehung",
    "Streit und Versöhnung",
    "Die leise Entfremdung",
    "Funkstille in Beziehungen",
    "Ghosting als Phänomen",
    "Online-Dating in Deutschland",
    "Der erste Eindruck",
    "Blind Date",
    "Schmetterling im Bauch",
    "Liebeskummer überwinden",
    "Freundschaft nach der Trennung",
    "Alleinsein vs. Einsamkeit",
    "Einsamkeit in der Großstadt",
    "Nachbarschaft als Gemeinschaft",
    "Stammkneipe und Stammplatz",
    "Der Lieblingsitaliener",
    "Pizza oder Pasta",
    "Griechisch essen gehen",
    "Türkischer Supermarkt",
    "Asiatisch kochen lernen",
    "Sushi in Deutschland",
    "Fusion-Küche",
    "Foodtrucks und Streetfood",
    "Markthalle als Treffpunkt",
    "Imbissbudenkultur",
    "Pommes rot-weiß",
    "Schnitzel mit Pommes",
    "Gyros oder Döner",
    "Falafel als Alternative",
    "Bowl und Superfood",
    "Smoothie-Wahnsinn",
    "Meal Prep für die Woche",
    "Sonntagsessen vorbereiten",
    "Rezepte der Großmutter",
    "Kochen als Kulturgut",
    "Kochshow im Fernsehen",
    "Das perfekte Dinner",
    "Geburtstag feiern",
    "Runder Geburtstag",
    "Überraschungsparty",
    "Gartenparty im Sommer",
    "Grillen – Gas, Kohle oder Elektro",
    "Die perfekte Grillwurst",
    "Nachbarn zum Grillen einladen",
    "Straßenfest organisieren",
    "Tag der offenen Tür",
    "Dorffest und Gemeinschaft",
    "Volkslauf und Stadtmarathon",
    "Firmenlauf als Teambuilding",
    "Der innere Schweinehund beim Sport",
    "Neuanfang im Januar",
    "Vorsätze durchhalten",
    "Tagebuch schreiben",
    "Journaling als Selbstreflexion",
    "Briefe schreiben im digitalen Zeitalter",
    "Postkarten aus dem Urlaub",
    "Souvenirs sammeln",
    "Reiseerinnerungen",
    "Camping am See",
    "Wohnmobil-Urlaub",
    "Zelten im Regen",
    "Jugendherberge und Klassenfahrt",
    "Austauschschüler aufnehmen",
    "Auslandsjahr nach dem Abi",
    "Interrail durch Europa",
    "Backpacking in Südostasien",
    "Fernreise oder Nahziel",
    "Urlaub auf Balkonien",
    "Staycation",
    "Wellnesshotel im Allgäu",
    "Therme und Sauna",
    "Saunakultur in Deutschland",
    "Aufguss und Wedeln",
    "FKK als Tradition",
    "Nacktwandern",
    "Deutsche Eigenheiten",
    "Handtuch auf der Sonnenliege",
    "Deutsche im Ausland",
    "Sandalen mit Socken",
    "Klischees über Deutsche",
    "Selbstironie lernen",
    "Humor als Brücke",
    "Witze erzählen können",
    "Spontan eine Rede halten",
    "Lampenfieber überwinden",
    "Rhetorik im Alltag",
    "Überzeugend argumentieren",
    "Der rote Faden",
    "Geschichten erzählen",
    "Storytelling im Beruf",
    "Präsentieren vor Publikum",
    "PowerPoint-Karaoke",
    "Kreativität und Routine",
    "Inspiration finden",
    "Der leere Bildschirm",
    "Schreibblockade überwinden",
    "Kreatives Schreiben",
    "Gedichte schreiben",
    "Slam Poetry",
    "Poetry Slam in Deutschland",
    "Theaterbesuch",
    "Volkstheater",
    "Kabarett vs. Comedy",
    "Stand-up Comedy auf Deutsch",
    "Improvisationstheater",
    "Rollenspiel und Empathie",
    "Perspektivwechsel",
    "In anderen Schuhen gehen",
    "Empathie als Superkraft",
    "Emotionale Intelligenz",
    "Gefühle zeigen als Mann",
    "Toxische Männlichkeit",
    "Rollenbilder im Wandel",
    "Gleichberechtigung im Haushalt",
    "Mental Load",
    "Unsichtbare Arbeit",
    "Care-Arbeit anerkennen",
    "Danke sagen für Selbstverständliches",
    "Die kleinen Dinge im Leben",
    "Dankbarkeit üben",
    "Zufriedenheit vs. Glück",
    "Glücksforschung",
    "Was macht ein gutes Leben aus",
    "Minimalismus als Lebensstil",
    "Weniger ist mehr",
    "Aufräumen nach Marie Kondo",
    "Entrümpeln befreit",
    "Sammelleidenschaft",
    "Briefmarken und Münzen",
    "Modelleisenbahn im Keller",
    "Hobbys und Leidenschaft",
    "Ein neues Hobby beginnen",
    "Instrument lernen als Erwachsener",
    "Volkshochschule und Weiterbildung",
    "Lebenslanges Lernen",
    "Bildung als Privileg",
    "Chancengleichheit im Bildungssystem",
    "Dreigliedriges Schulsystem",
    "Gesamtschule als Alternative",
    "PISA-Studie und ihre Folgen",
    "Lehrkräftemangel",
    "Quereinsteiger an der Schule",
    "Digitale Klassenzimmer",
    "Tafel oder Smartboard",
    "Kreide und Nostalgie",
    "Schulhof-Erinnerungen",
    "Pausenbrot und Capri-Sonne",
    "Klassentreffen nach zwanzig Jahren",
    "Alte Freundschaften pflegen",
    "Freundschaft über Distanz",
    "Der beste Freund, die beste Freundin",
    "Freundschaft vs. Bekanntschaft",
    "Netzwerken auf Deutsch",
    "Vitamin B",
    "Seilschaften und Klüngel",
    "Vetternwirtschaft",
    "Transparenz in der Politik",
    "Lobbyismus in Berlin",
    "Parteiendemokratie",
    "Volkspartei in der Krise",
    "Splitterparteien und Vielfalt",
    "Fünf-Prozent-Hürde",
    "Erst- und Zweitstimme",
    "Wahlsonntag",
    "Wahllokal und Stimmzettel",
    "Briefwahl",
    "Demokratie ist keine Selbstverständlichkeit",
    "Grundrechte schützen",
    "Pressefreiheit",
    "Kunstfreiheit",
    "Wissenschaftsfreiheit",
    "Religionsfreiheit und Laizismus",
    "Kirche und Staat",
    "Kirchensteuer",
    "Kirchenaustritt",
    "Spiritualität ohne Religion",
    "Weihnachten ohne Glaube",
    "Ostern – mehr als Eiersuche",
    "Reformationstag oder Halloween",
    "Allerheiligen und Totensonntag",
    "Buß- und Bettag",
    "Christi Himmelfahrt als Vatertag",
    "Muttertag – kommerziell oder herzlich",
    "Valentinstag in Deutschland",
    "Der Antrag am Schalttag",
    "Hochzeit planen",
    "Standesamt oder Kirche",
    "Polterabend",
    "Junggesellenabschied",
    "Flitterwochen",
    "Silberne Hochzeit",
    "Goldene Hochzeit",
    "Diamantene Hochzeit",
    "Ehe für alle",
    "Regenbogenfamilien",
    "Patchworkfamilie",
    "Alleinerziehend und stark",
    "Großfamilie oder Kleinfamilie",
    "Einzelkind oder Geschwister",
    "Geschwisterrivalität",
    "Erbschaftsstreit",
    "Testament und letzter Wille",
    "Über Geld spricht man nicht",
    "Gehaltsverhandlung",
    "Die erste Gehaltserhöhung",
    "Taschengeld für Kinder",
    "Sparen lernen",
    "Das Sparschwein",
    "Girokonto mit 18",
    "Erster eigener Mietvertrag",
    "Die erste eigene Wohnung",
    "Möbel vom Sperrmüll",
    "Kleinanzeigen-Abenteuer",
    "Was letzte Preis",
    "Tauschbörse und Secondhand",
    "Nachhaltigkeit im Alltag",
    "Fast Fashion und Alternativen",
    "Capsule Wardrobe",
    "Mode aus Deutschland",
    "Funktionskleidung überall",
    "Outdoor-Boom",
    "Wanderschuhe einlaufen",
    "Der erste Gipfel",
    "Hüttenwanderung",
    "Berghütte und Brotzeit",
    "Klettersteig für Anfänger",
    "Skifahren in den Alpen",
    "Après-Ski",
    "Skiurlaub in Österreich",
    "Langlauf statt Abfahrt",
    "Schneeschuhwandern",
    "Rodeln als Kindheitserinnerung",
    "Der Geruch von Tannennadeln",
    "Christbaum schmücken",
    "Weihnachtslieder singen",
    "Stille Nacht, Heilige Nacht",
    "O Tannenbaum",
    "Leise rieselt der Schnee",
    "Weihnachtsgans oder Kartoffelsalat",
    "Geschenke einpacken",
    "Die Freude des Schenkens",
    "Umtauschrecht nach Weihnachten",
    "Geld statt Geschenk",
    "Zeit schenken",
    "Gutscheine als Notlösung",
    "Das perfekte Geschenk",
    "Überraschung oder Wunschliste",
    "Amazon und der lokale Handel",
    "Lieferkettenprobleme",
    "Globalisierung und Regionalität",
    "Buy local",
    "Direktvermarkter und Hofladen",
    "Biobauer um die Ecke",
    "Solidarische Landwirtschaft",
    "Landwirtschaft im Wandel",
    "Bauernproteste",
    "Agrarsubventionen",
    "Tierhaltung und Ethik",
    "Massentierhaltung",
    "Tierrechte",
    "Haustier als Familienmitglied",
    "Hund oder Katze",
    "Gassi gehen bei jedem Wetter",
    "Hundeschule",
    "Reiten als Hobby",
    "Pferde und Verantwortung",
    "Zoo – artgerecht oder nicht",
    "Tierpark und Wildgehege",
    "Vogelbeobachtung",
    "Gartenarbeit als Meditation",
    "Rasen mähen und Hecke schneiden",
    "Der perfekte Rasen",
    "Unkraut oder Wildblume",
    "Bienenfreundlicher Garten",
    "Kompost und Kreislauf",
    "Regentonne und Wasserknappheit",
    "Trockenheit und Grundwasser",
    "Trinkwasserqualität in Deutschland",
    "Wasserwerke und Infrastruktur",
    "Marode Brücken",
    "Sanierungsstau",
    "Stuttgart 21 und Großprojekte",
    "BER und das Scheitern",
    "Elbphilharmonie und Erfolg",
    "Stadtplanung und Bürgerbeteiligung",
    "Grünflächen in der Stadt",
    "Parks als Oase",
    "Englischer Garten in München",
    "Tiergarten in Berlin",
    "Stadtwald und Erholung",
    "Lärm in der Stadt",
    "Stille suchen",
    "Entschleunigung",
    "Slow Food und Slow Living",
    "Langsam essen und genießen",
    "Das Mittagessen als Pause",
    "Kantine oder Foodtruck",
    "Mitgebrachtes Essen im Büro",
    "Tupperware als Kulturgut",
    "Die Thermoskanne",
    "Frühstück als wichtigste Mahlzeit",
    "Müsli oder Marmeladenbrot",
    "Ei zum Frühstück",
    "Brunch am Sonntag",
    "Frühstücken gehen",
    "Einkaufen am Samstagmorgen",
    "Vollgepackter Einkaufswagen",
    "Die Kassenschlange",
    "Selbstbedienungskasse",
    "Bon-Pflicht",
    "Kassenzettel für alles",
    "Steuererklärung machen",
    "ELSTER und die Frustration",
    "Steuerberater oder selber machen",
    "Steuern zahlen als Bürgerpflicht",
    "Schwarze Null",
    "Schuldenbremse",
    "Generationengerechtigkeit",
    "Was hinterlassen wir den Kindern",
    "Zukunftsangst",
    "Optimismus in schwierigen Zeiten",
    "Hoffnung als Antrieb",
    "Vertrauen in die Zukunft",
    "Verantwortung übernehmen",
    "Vorbild sein",
    "Vorbilder und Helden",
    "Heldentum im Alltag",
    "Die leise Heldin",
    "Unerkannte Leistung",
    "Sichtbarkeit und Anerkennung",
    "Im Rampenlicht stehen",
    "Bescheidenheit als Tugend",
    "Understatement",
    "Angeben und Protzen",
    "Statussymbole",
    "Auto als Statussymbol",
    "Markenbewusstsein",
    "Konsum und Identität",
    "Haben oder Sein",
    "Materialismus hinterfragen",
    "Freiheit und Besitz",
    "Besitz verpflichtet",
    "Eigentum und Gemeinwohl",
    "Enteignungsdebatte",
    "Wohnungsnot und Lösungen",
    "Tiny House als Alternative",
    "Bauwagenplatz und Freiheit",
    "Hausboot auf dem Kanal",
    "Leben auf dem Wasser",
    "Auswandern – Traum oder Flucht",
    "Rückkehr nach Deutschland",
    "Heimat neu definieren",
    "Ankommen und Bleiben",
    "Wurzeln und Flügel",
    "Tradition und Moderne",
    "Alt und Neu verbinden",
    "Denkmalschutz und Fortschritt",
    "Altstadt bewahren",
    "Architektur und Identität",
    "Brutalismus und Beton",
    "Nachhaltiges Bauen",
    "Holzbau als Zukunft",
    "Tiny-Häuser aus Holz",
    "Container als Wohnraum",
    "Kreativquartier und Zwischennutzung",
    "Leerstand als Chance",
    "Kreativer Umgang mit Raum",
    "Gemeinschaftsräume schaffen",
    "Bibliothek der Dinge",
    "Teilen statt Besitzen",
    "Sharing Economy",
    "Mitfahrgelegenheit",
    "Couchsurfing und Gastfreundschaft",
    "Gastfreundschaft auf Deutsch",
    "Den Tisch decken für Gäste",
    "Besuch kündigt sich an",
    "Unangekündigter Besuch",
    "Gastgeschenk mitbringen",
    "Blumen oder Wein",
    "Pünktlich oder akademisches Viertel",
    "Zu spät kommen – eine Todsünde",
    "Die fünf Minuten vor der Zeit",
    "Warten können",
    "Geduld als Tugend",
    "Ungeduld im Stau",
    "Road Rage auf der Autobahn",
    "Gelassenheit üben",
    "Was man nicht ändern kann",
    "Akzeptanz und Loslassen",
    "Abschiednehmen üben",
    "Der letzte Schultag",
    "Der erste Arbeitstag",
    "Berufswahl als Lebensentscheidung",
    "Den richtigen Beruf finden",
    "Quereinstieg wagen",
    "Umschulung mit vierzig",
    "Lebenslanges Lernen ernst nehmen",
    "Bildungsurlaub nutzen",
    "Sabbatical nehmen",
    "Ein Jahr Auszeit",
    "Weltreise mit dem Rucksack",
    "Jakobsweg gehen",
    "Pilgern als Selbstfindung",
    "Sinnsuche in der Lebensmitte",
    "Midlife-Crisis oder Midlife-Chance",
    "Älterwerden und Weiserwerden",
    "Falten und Erfahrung",
    "Schönheit im Alter",
    "Jugendwahn der Gesellschaft",
    "Anti-Aging oder Pro-Aging",
    "Selbstliebe lernen",
    "Körperbild und Gesellschaft",
    "Schönheitsideale hinterfragen",
    "Mode als Ausdruck",
    "Kleidung und Persönlichkeit",
    "Uniform oder Individualität",
    "Der Sonntagsanzug",
    "Jogginghose in der Öffentlichkeit",
    "Karl Lagerfeld und die Jogginghose",
    "Eleganz und Schlichtheit",
    "Die Kraft der Farben",
    "Grau als Lieblingsfarbe der Deutschen",
    "Schwarz tragen",
    "Funktionalität vor Ästhetik",
    "Form follows function",
    "Deutscher Industriedesign",
    "Braun und Dieter Rams",
    "Porsche als Designikone",
    "Deutsche Ingenieurskunst",
    "Tüftler und Erfinder",
    "Die Erfindung des Buchdrucks",
    "Die Erfindung des Automobils",
    "Einstein und die Relativität",
    "Humboldt und die Bildung",
    "Kant und der kategorische Imperativ",
    "Hegel und die Dialektik",
    "Nietzsche – Gott ist tot",
    "Marx und das Kapital",
    "Hannah Arendt und die Banalität des Bösen",
    "Habermas und der Diskurs",
    "Frankfurter Schule",
    "Kritische Theorie im Alltag",
    "Philosophie am Küchentisch",
    "Gedankenexperimente",
    "Was wäre wenn",
    "Die Macht der Vorstellung",
    "Tagträumen erlaubt",
    "Phantasie und Wirklichkeit",
    "Utopie und Dystopie",
    "Die beste aller Welten",
    "Fortschritt und seine Schattenseiten",
    "Technikoptimismus",
    "Technikskepsis",
    "German Angst",
    "Risikobereitschaft",
    "Sicherheitsdenken",
    "Versicherung für alles",
    "Der Versicherungsordner",
    "Akten und Abheften",
    "Der Leitz-Ordner",
    "Bürokratie abbauen",
    "Digitale Verwaltung",
    "E-Government",
    "Der digitale Ausweis",
    "Papier vs. digital",
    "Handschrift bewahren",
    "Füller oder Kugelschreiber",
    "Schreibschrift in der Schule",
    "Lesen fördern bei Kindern",
    "Vorlesen am Abend",
    "Gute-Nacht-Geschichte",
    "Kindheit gestern und heute",
    "Spielen ohne Bildschirm",
    "Brettspiele am Familienabend",
    "Mensch ärgere dich nicht",
    "Siedler von Catan",
    "Skat und Doppelkopf",
    "Schafkopf in Bayern",
    "Jassen in der Schweiz",
    "Rommé mit der Oma",
    "Puzzlen an Regentagen",
    "Kreuzworträtsel lösen",
    "Sudoku im Zug",
    "Rätseln und Knobeln",
    "Escape Room als Teambuilding",
    "Geocaching in der Natur",
    "Orientierungslauf",
    "Pfadfinder und Abenteuer",
    "Lagerfeuer und Stockbrot",
    "Marshmallows rösten",
    "Zelten mit Freunden",
    "Festival-Erfahrungen",
    "Schlamm und Musik",
    "Die erste Konzert-Erinnerung",
    "Ohrenstöpsel im Konzert",
    "Vinyljacke und Patches",
    "Subkulturen in Deutschland",
    "Punk in Kreuzberg",
    "Techno in den 90ern",
    "Loveparade-Erinnerung",
    "Christopher Street Day",
    "Toleranz und Akzeptanz",
    "Anders sein",
    "Zugehörigkeit und Ausgrenzung",
    "Inklusion im Alltag",
    "Barrierefreiheit",
    "Behindertenparkplatz und Rücksicht",
    "Aufeinander achten",
    "Fürsorge und Selbstfürsorge",
    "Grenzen setzen",
    "Nein sagen lernen",
    "People Pleasing",
    "Harmoniebedürfnis",
    "Konfliktscheu",
    "Konflikte konstruktiv lösen",
    "Mediation",
    "Schlichten statt richten",
    "Vergebung und Versöhnung",
    "Alte Wunden heilen",
    "Therapie als Stärke",
    "Psychische Gesundheit enttabuisieren",
    "Über Gefühle sprechen",
    "Männer und Emotionen",
    "Frauen und Wut",
    "Wut als Motor",
    "Gelassenheit statt Zorn",
    "Die Stille nach dem Streit",
    "Wieder aufeinander zugehen",
    "Die Hand reichen",
    "Brücken bauen",
    "Dialog statt Monolog",
    "Debattenkultur",
    "Stammtisch vs. Salon",
    "Intellektueller Diskurs",
    "Populismus erkennen",
    "Komplexität aushalten",
    "Einfache Antworten auf schwere Fragen",
    "Grautöne statt Schwarzweiß",
    "Ambivalenz ertragen",
    "Widersprüche leben",
    "Doppelmoral",
    "Authentisch sein",
    "Masken ablegen",
    "Verletzlichkeit zeigen",
    "Stärke in der Schwäche",
    "Aufstehen nach dem Fallen",
    "Durchhaltevermögen",
    "Der lange Atem",
    "Marathon statt Sprint",
    "Langsam und stetig",
    "Schnelllebigkeit der Moderne",
    "Informationsflut",
    "Reizüberflutung",
    "Stille als Luxus",
    "Nichtstun als Kunst",
    "Langeweile aushalten",
    "Muße und Kreativität",
    "Das dolce far niente auf Deutsch",
    "Die Hängematte am Nachmittag",
    "Mittagsschlaf oder Powernap",
    "Die Siesta fehlt uns",
    "Arbeitsrhythmus und Biorhythmus",
    "Lerchen und Eulen",
    "Der frühe Morgen",
    "Die blaue Stunde",
    "Dämmerung im Sommer",
    "Weiße Nächte im Norden",
    "Mittsommer und Johanni",
    "Sommersonnenwende feiern",
    "Wintersonnenwende und Dunkelheit",
    "Lichtmangel im Winter",
    "Vitamin D und Winterblues",
    "Hygge auf Deutsch: Gemütlichkeit",
    "Kerzen anzünden",
    "Kaminfeuer und Tee",
    "Decke und Buch auf dem Sofa",
    "Regentag zu Hause",
    "Der Duft von frischem Brot",
    "Plätzchenbacken im Advent",
    "Zimtsterne und Vanillekipferl",
    "Christstollen anschneiden",
    "Der erste Biss Lebkuchen",
    "Glühwein selbst machen",
    "Punsch auf dem Weihnachtsmarkt",
    "Gebrannte Mandeln",
    "Dampfnudeln mit Vanillesoße",
    "Kartoffelpuffer mit Apfelmus",
    "Reibekuchen am Rhein",
    "Grünkohl und Pinkel",
    "Labskaus in Hamburg",
    "Himmel und Erde",
    "Rheinischer Sauerbraten",
    "Thüringer Klöße",
    "Dresdner Eierschecke",
    "Bayerische Weißwurst",
    "Weißwurstäquator",
    "Obazda und Breze",
    "Flammkuchen aus dem Elsass",
    "Zwiebelkuchen und Federweißer",
    "Die letzte Seite eines guten Buches",
    "Das Gefühl nach einer bestandenen Prüfung",
    "Der Moment, wenn der Zug pünktlich kommt",
    "Barfuß durch nasses Gras",
    "Der erste Sprung ins kalte Wasser",
    "Kastanien sammeln im Herbst",
    "Drachen steigen lassen",
    "Der Geruch nach Regen auf warmem Asphalt",
    "Sonnenblumenfelder",
    "Ein Lied, das alles zurückbringt",
    "Alte Fotos in einer Schublade",
    "Der Klang einer Kirchenglocke",
    "Feuerwerk über dem Fluss",
    "Der stille Moment vor dem Einschlafen",
    "Sperrmüll als Schatzsuche",
    "Die Magie alter Kinos",
    "Kinobesuch oder Heimkino",
    "Programmkino und Arthouse",
    "Open-Air-Kino im Sommer",
    "Autokino-Revival",
    "Blockbuster oder Independentfilm",
    "Synchronisation oder Originalton",
    "Untertitel lesen",
    "Deutsche Synchronsprecher",
    "Hörbuch beim Einschlafen",
    "Radio im Auto",
    "Deutschlandfunk am Morgen",
    "Morgenmagazin im Fernsehen",
    "Frühstücksfernsehen",
    "Abendnachrichten als Ritual",
    "Zeitung austragen als erster Job",
    "Ferienjob in der Fabrik",
    "Praktikum und Ausbeutung",
    "Generation Praktikum",
    "Mindestlohn-Debatte",
    "Schwarzes Brett in der Uni",
    "Semesterferien nutzen",
    "Prüfungsangst überwinden",
    "Spickzettel und Ehrlichkeit",
    "Abschreiben in der Klausur",
    "Plagiat und Verantwortung",
    "Doktortitel und sein Gewicht",
    "Professor als Berufung",
    "Elfenbeinturm der Wissenschaft",
    "Grundlagenforschung finanzieren",
    "Max-Planck-Gesellschaft",
    "Fraunhofer-Institute",
    "Deutsche Forschungsgemeinschaft",
    "Nobelpreisträger aus Deutschland",
    "Humboldt-Universität",
    "Heidelberg und seine Romantik",
    "Göttingen und die Gelehrten",
    "Tübingen und seine Stocherkähne",
    "Marburg und seine Gassen",
    "Rothenburg ob der Tauber",
    "Die Romantische Straße",
    "Rheinromantik",
    "Loreley und ihr Lied",
    "Hänsel und Gretel im Wald",
    "Grimms Märchen",
    "Der Froschkönig",
    "Rotkäppchen und der Wolf",
    "Märchenwald und Kindheit",
    "Die Bremer Stadtmusikanten",
    "Der Rattenfänger von Hameln",
    "Nibelungensage",
    "Siegfried und der Drache",
    "Till Eulenspiegel",
    "Baron Münchhausen",
    "Der Struwwelpeter",
    "Max und Moritz",
    "Wilhelm Busch und die Bildergeschichten",
    "Der Räuber Hotzenplotz",
    "Das Sams und die Wunschpunkte",
    "Pünktchen und Anton",
    "Emil und die Detektive",
    "Erich Kästner und die Kindheit",
    "Die Blechtrommel lesen",
    "Grass und die Danziger Trilogie",
    "Böll und die Nachkriegsliteratur",
    "Christa Wolf und geteiltes Deutschland",
    "Ingeborg Bachmann",
    "Paul Celan und die Todesfuge",
    "Rose Ausländer",
    "Nelly Sachs",
    "Literatur als Erinnerung",
    "Schreiben gegen das Vergessen",
    "Archive und Gedächtnis",
    "Zeitkapsel vergraben",
    "Briefe an das zukünftige Ich",
    "Fotoalbum durchblättern",
    "Analogfotografie wiederentdecken",
    "Polaroid-Charme",
    "Dunkelkammer und Geduld",
    "Fotografie als Kunst",
    "Die Becher-Schule",
    "Andreas Gursky",
    "Gerhard Richter",
    "Anselm Kiefer",
    "Joseph Beuys und die soziale Plastik",
    "Jeder Mensch ist ein Künstler",
    "Kunst im öffentlichen Raum",
    "Skulpturenpark",
    "Land Art im Feld",
    "Kunst oder Krempel",
    "Bares für Rares",
    "Antiquitäten schätzen",
    "Der Wert alter Dinge",
    "Nostalgie und Verklärung",
    "Die gute alte Zeit",
    "Früher war alles besser – oder doch nicht",
    "Fortschrittsoptimismus der Nachkriegszeit",
    "Wirtschaftswunder",
    "Gastarbeiter und ihre Geschichte",
    "Anwerbeabkommen 1961",
    "Türkische Gemeinschaft in Deutschland",
    "Italienische Eisdiele",
    "Griechisches Restaurant an der Ecke",
    "Vielfalt der Kulturen",
    "Multilingualismus",
    "Mehrsprachig aufwachsen",
    "Muttersprache und Identität",
    "Sprachverlust in der Diaspora",
    "Heimatlieder aus aller Welt",
    "Musik verbindet",
    "Chor singen im Verein",
    "Kirchenchor am Sonntag",
    "Blasmusik beim Schützenfest",
    "Spielmannszug im Umzug",
    "Karneval der Kulturen in Berlin",
    "Elbhangfest in Dresden",
    "Altstadtfest und Bühnen",
    "Literaturfestival",
    "Lesungen im Buchladen",
    "Autogrammstunde",
    "Der Zauber eines vollen Bücherregals",
    "Bücherregal als Spiegel der Seele",
    "Leseratte oder Bücherwurm",
    "Die nie gelesenen Bücher",
    "Stapel ungelesener Bücher",
    "Das Buch, das alles veränderte",
    "Der Satz, der hängen bleibt",
    "Worte, die trösten",
    "Sprache als Heimat",
    "Dialekt als Herzenssprache",
    "Das erste Wort eines Kindes",
    "Kindergeschrei auf dem Spielplatz",
    "Sandburgen bauen am Strand",
    "Muscheln sammeln an der Nordsee",
    "Wattwanderung bei Ebbe",
    "Möwen und Fischbrötchen",
    "Fischbrötchen in Husum",
    "Tee in Ostfriesland",
    "Ostfriesische Teezeremonie",
    "Ankommen nach langer Reise"
];