topicsByLang.pt = {
    easy: [
        "Café da manhã",
        "Churrasco de domingo",
        "Praia no fim de semana",
        "Açaí com granola",
        "Pão de queijo quentinho",
        "Feijoada completa",
        "Coxinha de frango",
        "Brigadeiro de colher",
        "Pastel de feira",
        "Bolo de cenoura com cobertura de chocolate",
        "Tapioca recheada",
        "Cafezinho da tarde",
        "Arroz com feijão de todo dia",
        "Farofa da vovó",
        "Pipoca no cinema",
        "Sorvete na praia",
        "Água de coco gelada",
        "Guaraná natural",
        "Caldo de cana na feira",
        "Queijo coalho na brasa",
        "Acarajé baiano",
        "Moqueca capixaba ou baiana",
        "Tacacá no Ver-o-Peso",
        "Chimarrão no frio",
        "Cachorro-quente de carrocinha",
        "Bauru de padaria",
        "Pão francês fresquinho",
        "Manteiga ou margarina no pão",
        "Goiabada com queijo",
        "Bolo de fubá com café",
        "Pamonha doce ou salgada",
        "Curau de milho verde",
        "Canjica na festa junina",
        "Quentão e vinho quente",
        "Espetinho de churrasco",
        "Picanha na brasa",
        "Caipirinha bem feita",
        "Suco de laranja natural",
        "Vitamina de banana",
        "Mingau de aveia",
        "Carnaval de rua",
        "Desfile das escolas de samba",
        "Bloquinho de carnaval",
        "Fantasia de carnaval",
        "Confete e serpentina",
        "Marchinha de carnaval",
        "Trio elétrico na Bahia",
        "Axé no carnaval de Salvador",
        "Frevo em Recife",
        "Maracatu pernambucano",
        "Festa junina na escola",
        "Quadrilha de São João",
        "Fogueira de São João",
        "Balão de papel na festa junina",
        "Bandeirinhas coloridas",
        "Correio elegante",
        "Pescaria de festa junina",
        "Bingo da igreja",
        "Futebol de domingo",
        "Pelada no campinho",
        "Gol de placa",
        "Assistir jogo no bar",
        "Camisa do time do coração",
        "Figurinhas do álbum da Copa",
        "Grito de gol",
        "Chuteira de infância",
        "Jogar altinha na praia",
        "Frescobol à beira-mar",
        "Futebol de areia",
        "Peteca no quintal",
        "Pipa no céu",
        "Bolinha de gude",
        "Pular corda na rua",
        "Esconde-esconde de criança",
        "Pega-pega no recreio",
        "Queimada na escola",
        "Amarelinha no chão",
        "Bambolê no quintal",
        "Cinco Marias",
        "Cabra-cega",
        "Ciranda na praça",
        "Roda de samba",
        "Pagode no fundo de quintal",
        "Roda de capoeira",
        "Forró pé de serra",
        "Sertanejo universitário",
        "Bossa nova no violão",
        "MPB no fim de tarde",
        "Funk carioca",
        "Rap nacional",
        "Samba de roda baiano",
        "Maracatu de baque virado",
        "Violão na roda de amigos",
        "Pandeiro na roda de samba",
        "Berimbau e atabaque",
        "Sanfona de oito baixos",
        "Zabumba e triângulo",
        "Cantoria de repente",
        "Novela das nove",
        "Programa de auditório",
        "Desenho animado de sábado",
        "Filme de domingo à tarde",
        "Reprise na Sessão da Tarde",
        "Plantão da Globo",
        "Jornal Nacional",
        "Programa do Faustão",
        "Show de Talentos na TV",
        "Telecoteco de rádio AM",
        "Rádio no carro",
        "Feira livre de sábado",
        "Padaria da esquina",
        "Mercado municipal",
        "Loja de um e noventa e nove",
        "Sacolão de frutas",
        "Farmácia de bairro",
        "Salão de beleza do bairro",
        "Barbearia tradicional",
        "Lanchonete de esquina",
        "Boteco pé-sujo",
        "Quiosque de praia",
        "Barraca de coco",
        "Vendedor de picolé",
        "Pipoqueiro do parque",
        "Sorveteiro na rua",
        "Caminhão de gás",
        "Carro do ovo",
        "Feira de artesanato",
        "Brechó de bairro",
        "Loja de açaí",
        "Ônibus lotado",
        "Metrô em horário de pico",
        "Trânsito de São Paulo",
        "Motoboy na chuva",
        "Uber ou táxi",
        "Rodovia nas férias",
        "Pedágio na estrada",
        "Posto de gasolina na BR",
        "Parada em posto de estrada",
        "Viagem de ônibus leito",
        "Rede na varanda",
        "Chinelo de dedo",
        "Canga de praia",
        "Guarda-sol e cadeira de praia",
        "Protetor solar no verão",
        "Bermuda e camiseta",
        "Havaianas de todo dia",
        "Boné do time",
        "Chapéu de palha na roça",
        "Chuva de verão",
        "Temporal de fim de tarde",
        "Arco-íris depois da chuva",
        "Calor de janeiro",
        "Frio de Curitiba",
        "Friozinho de São Paulo",
        "Garoa paulistana",
        "Ventania no litoral",
        "Pôr do sol na praia",
        "Nascer do sol no sertão",
        "Noite estrelada na roça",
        "Lua cheia na varanda",
        "Canteiro de ervas da vovó",
        "Horta em casa",
        "Jardim do vizinho",
        "Plantas na sacada",
        "Cachorro vira-lata caramelo",
        "Gato de telhado",
        "Papagaio falante",
        "Periquito na janela",
        "Passarinho cantando de manhã",
        "Sabiá no quintal",
        "Bem-te-vi na árvore",
        "João-de-barro no poste",
        "Almoço de domingo em família",
        "Churrasco com os amigos",
        "Aniversário de criança",
        "Festa de 15 anos",
        "Casamento no sítio",
        "Batizado do sobrinho",
        "Formatura do ensino médio",
        "Natal em família",
        "Ceia de Natal",
        "Panetone ou chocotone",
        "Amigo secreto",
        "Réveillon na praia",
        "Roupa branca no Ano Novo",
        "Pular sete ondas",
        "Simpatias de Ano Novo",
        "Dia das Mães",
        "Dia dos Namorados em junho",
        "Dia das Crianças",
        "Presente de Dia dos Pais",
        "Páscoa e ovo de chocolate",
        "Ovo de Páscoa caseiro",
        "Semana Santa na cidade do interior",
        "Procissão religiosa",
        "Quermesse da paróquia",
        "Missa de domingo",
        "Terço da avó",
        "Primeira comunhão",
        "Promessa cumprida"
    ],
    medium: [
        "O jeitinho brasileiro",
        "Saudade como sentimento brasileiro",
        "O significado do abraço no Brasil",
        "A cultura do atraso: horário brasileiro",
        "Dar um jeitinho ou seguir a regra",
        "O brasileiro e a hospitalidade",
        "A importância da família extensa",
        "A mesa como ponto de encontro",
        "O papel do café na socialização",
        "Vizinhança e comunidade no Brasil",
        "A cultura do favor e da reciprocidade",
        "Dar um presente sem motivo",
        "O costume de levar algo quando é convidado",
        "A festa de boas-vindas",
        "O abraço demorado da despedida",
        "A arte de receber visitas",
        "Quando o vizinho vira família",
        "A rua como extensão da casa",
        "O portão aberto do interior",
        "Bater papo no portão",
        "Sentar na calçada no fim do dia",
        "Contar história na varanda",
        "O poder da fofoca de bairro",
        "Grupo de WhatsApp da família",
        "Grupo de WhatsApp do condomínio",
        "O áudio longo no WhatsApp",
        "Mandar figurinhas no grupo",
        "Redes sociais e a vida real",
        "Filtro de foto e autoestima",
        "A vida perfeita do Instagram",
        "O vício do celular",
        "Criança com tablet na mão",
        "Educação digital para jovens",
        "O brasileiro e as redes sociais",
        "Meme como expressão cultural",
        "O humor brasileiro na internet",
        "Zueira como mecanismo de defesa",
        "Rir para não chorar",
        "O otimismo do brasileiro",
        "A resiliência do povo brasileiro",
        "O sonho da casa própria",
        "Morar de aluguel no Brasil",
        "Sair da casa dos pais",
        "Dividir apartamento com amigos",
        "A vida no interior versus na capital",
        "Mudar de cidade por trabalho",
        "O êxodo rural no Brasil",
        "Saudade da cidade natal",
        "Voltar para casa nas férias",
        "Férias no litoral",
        "Viajar pelo Brasil",
        "Conhecer o próprio país",
        "Turismo de base comunitária",
        "Ecoturismo no Brasil",
        "A beleza da Chapada Diamantina",
        "Fernando de Noronha: paraíso acessível?",
        "Pantanal e sua biodiversidade",
        "A imensidão da Amazônia",
        "O cerrado esquecido",
        "A caatinga resiliente",
        "Mata Atlântica: o que restou",
        "A importância das unidades de conservação",
        "Plantar árvores como ato de esperança",
        "Sustentabilidade no dia a dia",
        "Reciclagem e consciência ambiental",
        "O catador de recicláveis",
        "Economia circular no Brasil",
        "Energia solar no Nordeste",
        "Água: abundância e desperdício",
        "Apagão e racionamento",
        "O papel do SUS na vida do brasileiro",
        "Fila de hospital público",
        "Posto de saúde do bairro",
        "Farmácia popular",
        "Remédio caseiro da avó",
        "Chá de boldo e cidreira",
        "Benzedeira e reza forte",
        "Simpatia que funciona",
        "A fé do brasileiro",
        "Sincretismo religioso no Brasil",
        "Iemanjá e as flores no mar",
        "Festa do Divino",
        "Romaria e peregrinação",
        "Círio de Nazaré em Belém",
        "Lavagem do Bonfim em Salvador",
        "São Jorge ou Ogum",
        "Cosme e Damião e os doces",
        "O terreiro como espaço sagrado",
        "A roda de candomblé",
        "A umbanda como religião brasileira",
        "O papel das igrejas evangélicas nas periferias",
        "Música gospel no Brasil",
        "O futebol como religião",
        "A rivalidade entre clássicos",
        "A emoção da final do campeonato",
        "Pelé e o legado do futebol brasileiro",
        "Futebol feminino e reconhecimento",
        "A torcida organizada",
        "Bar e futebol: combinação nacional",
        "A seleção brasileira e a identidade nacional",
        "Copa do Mundo no Brasil em 2014",
        "O 7 a 1 e o trauma coletivo",
        "Superação no esporte",
        "Atleta de comunidade",
        "Esporte como transformação social",
        "Projeto social e esporte na periferia",
        "Capoeira como resistência cultural",
        "A ginga brasileira",
        "Samba de raiz e identidade negra",
        "A herança africana na cultura brasileira",
        "A influência indígena na culinária",
        "A miscigenação e a identidade brasileira",
        "O mito da democracia racial",
        "Representatividade na mídia brasileira",
        "Novela brasileira e costumes",
        "O poder da novela na opinião pública",
        "Música sertaneja e o Brasil profundo",
        "O fenômeno do funk",
        "Trap brasileiro e a nova geração",
        "Rap como voz da periferia",
        "Literatura de cordel nordestina",
        "Repentista e a arte da improvisação",
        "Mamulengo e teatro de bonecos",
        "Cinema brasileiro e sua força",
        "Festival de cinema no Brasil",
        "A importância da Cinemateca",
        "Teatro comunitário",
        "Grafite e arte urbana",
        "Pixação: arte ou vandalismo?",
        "Muralismo nas favelas",
        "A favela como espaço cultural",
        "Baile funk e identidade",
        "O rolê cultural gratuito",
        "Sarau de poesia na periferia",
        "Slam: poesia falada",
        "Biblioteca comunitária",
        "O hábito de leitura no Brasil",
        "Machado de Assis e a literatura brasileira",
        "Clarice Lispector e a introspecção",
        "Jorge Amado e a Bahia",
        "Guimarães Rosa e o sertão",
        "Carlos Drummond e a poesia do cotidiano",
        "Vinícius de Moraes: poeta e compositor",
        "A crônica como gênero brasileiro",
        "O professor e o valor da educação",
        "Escola pública no Brasil",
        "ENEM e o acesso à universidade",
        "Cursinho popular",
        "Cotas na universidade",
        "Primeiro da família na faculdade",
        "Educação como elevador social",
        "O valor do diploma no Brasil",
        "Trabalho informal no Brasil",
        "O empreendedor de necessidade",
        "Microempreendedor individual",
        "A economia do bico",
        "Trabalho remoto no Brasil",
        "A rotina do home office",
        "Coworking e novos espaços de trabalho",
        "O sonho de ter o próprio negócio",
        "Foodtruck e comida de rua gourmet",
        "Feira gastronômica",
        "A revolução dos aplicativos de entrega",
        "O entregador de aplicativo",
        "PIX e a revolução dos pagamentos",
        "Banco digital no Brasil",
        "Compras parceladas no cartão",
        "O carnê de crediário",
        "Black Friday à brasileira",
        "Consumismo e consciência",
        "Brechó e moda sustentável",
        "A moda praia brasileira",
        "Havaianas como símbolo cultural",
        "O estilo carioca",
        "A elegância paulistana",
        "O colorido baiano",
        "A criatividade na moda de periferia",
        "Trança afro e identidade",
        "Cabelo crespo e empoderamento",
        "Padrão de beleza no Brasil",
        "O corpo brasileiro na mídia",
        "Autoestima e aceitação",
        "Saúde mental e tabu",
        "Terapia no Brasil: luxo ou necessidade",
        "O peso da cobrança social",
        "Ansiedade na vida moderna",
        "Burnout e cultura de trabalho",
        "Equilíbrio entre trabalho e lazer",
        "O direito ao ócio",
        "Domingo sem fazer nada",
        "A arte de não fazer nada",
        "Sesta depois do almoço",
        "O cheiro de terra molhada e a memória",
        "A importância do apelido no Brasil",
        "O mutirão como forma de solidariedade",
        "Morar em república na faculdade",
        "A cultura do improviso no Brasil",
        "O papel da avó na criação dos netos",
        "A dificuldade de dizer não",
        "O peso do sobrenome no Brasil"
    ],
    hard: [
        "O que é saudade para quem nunca sentiu",
        "A solidão em meio à multidão brasileira",
        "Ser estrangeiro na própria terra",
        "A dor de deixar o Brasil",
        "O imigrante brasileiro no exterior",
        "Voltar ao Brasil depois de anos fora",
        "O Brasil que a gente idealiza de longe",
        "A identidade brasileira em crise",
        "O que significa ser brasileiro no século XXI",
        "A brasilidade como construção coletiva",
        "O complexo de vira-lata do brasileiro",
        "Valorizar o que é nosso",
        "A cultura popular como patrimônio",
        "Tradição e modernidade: convivência possível?",
        "O progresso que destrói a memória",
        "A cidade que engole o campo",
        "O sertanejo que virou urbano",
        "A periferia que cria sua própria cultura",
        "Centro e margem: quem define a cultura?",
        "A voz dos silenciados",
        "Quem conta a história do Brasil?",
        "Memória e esquecimento na sociedade brasileira",
        "O que a escola não ensina sobre o Brasil",
        "A história que os livros apagaram",
        "Heróis nacionais: mito e realidade",
        "Zumbi dos Palmares e a resistência",
        "A herança da escravidão no cotidiano",
        "Racismo estrutural no dia a dia",
        "O peso de ser negro no Brasil",
        "A luta por reconhecimento",
        "Ancestralidade e pertencimento",
        "Reconectar-se com as raízes",
        "O indígena invisibilizado",
        "A terra como sagrada para os povos originários",
        "Desenvolvimento versus preservação",
        "O futuro da Amazônia",
        "Responsabilidade ambiental como dever coletivo",
        "Pensar nas próximas gerações",
        "O mundo que estamos deixando",
        "Esperança em tempos difíceis",
        "A fé como motor de sobrevivência",
        "Acreditar quando tudo desmorona",
        "Recomeçar do zero",
        "A coragem de mudar de vida",
        "Sair da zona de conforto",
        "O medo do desconhecido",
        "A incerteza como companheira",
        "Viver sem garantias",
        "A fragilidade da estabilidade",
        "O que realmente importa na vida",
        "Sucesso: definição pessoal ou social?",
        "A pressão por ser alguém na vida",
        "O peso das expectativas familiares",
        "Honrar o sacrifício dos pais",
        "A culpa de quem ascendeu socialmente",
        "Mudar de classe social e perder amigos",
        "O abismo entre ricos e pobres",
        "Empatia em uma sociedade desigual",
        "Solidariedade como ato revolucionário",
        "O poder transformador da generosidade",
        "Ajudar sem esperar nada em troca",
        "O voluntariado como propósito",
        "Encontrar sentido na vida",
        "A busca por propósito",
        "Trabalhar com o que ama: privilégio ou meta?",
        "Sobreviver ou viver?",
        "A diferença entre existir e viver",
        "O tempo que não volta",
        "Arrepender-se do que não fez",
        "As escolhas que nos definem",
        "O peso de uma decisão errada",
        "Perdoar a si mesmo",
        "Perdoar quem nos machucou",
        "O rancor que aprisiona",
        "Deixar ir o que já passou",
        "A arte de desapegar",
        "Minimalismo em um país de consumo",
        "Ter menos para viver mais",
        "A simplicidade como filosofia",
        "A sabedoria do povo simples",
        "O que aprendi com meus avós",
        "A velhice no Brasil",
        "Envelhecer com dignidade",
        "O idoso invisível",
        "O asilo e a solidão",
        "Cuidar de quem cuidou de nós",
        "A inversão de papéis entre pais e filhos",
        "Quando os filhos se tornam cuidadores",
        "A dor da perda de um ente querido",
        "Luto e reconstrução",
        "Saudade de quem já se foi",
        "A presença dos ausentes",
        "Honrar a memória de quem amamos",
        "O legado que deixamos",
        "O que dirão sobre nós quando partirmos",
        "Viver como se fosse o último dia",
        "A finitude como motivação",
        "Falar sobre a morte no Brasil",
        "O velório como ritual de despedida",
        "A celebração da vida após a morte",
        "Dia de Finados e a memória afetiva",
        "A espiritualidade brasileira",
        "A busca interior em tempos de ruído",
        "Silêncio como luxo no mundo moderno",
        "A pressa que rouba a presença",
        "Estar presente no momento",
        "A ansiedade de quem vive no futuro",
        "A nostalgia de quem vive no passado",
        "Encontrar paz no caos",
        "A calma como forma de resistência",
        "A gentileza como ato de coragem",
        "Ser vulnerável em uma cultura de força",
        "O homem brasileiro e a masculinidade",
        "A pressão sobre a mulher brasileira",
        "Maternidade: escolha ou imposição?",
        "A mãe solo no Brasil",
        "Paternidade presente",
        "O pai ausente e suas marcas",
        "Criança que cresce rápido demais",
        "A infância roubada",
        "O direito de ser criança",
        "Brincar como ato de liberdade",
        "A imaginação como refúgio",
        "O adulto que perdeu a capacidade de sonhar",
        "Reaprender a sonhar",
        "O sonho coletivo de um Brasil melhor",
        "Utopia brasileira: o que seria?",
        "A esperança como patrimônio nacional",
        "O brasileiro que não desiste nunca",
        "A força do povo que ri da própria desgraça",
        "O humor como arma de sobrevivência",
        "A alegria como resistência",
        "Sambar na cara da adversidade",
        "A leveza que esconde a dor",
        "O sorriso que não chega aos olhos",
        "A máscara da felicidade",
        "Pedir ajuda como ato de coragem",
        "A solidão do homem forte",
        "Chorar sem vergonha",
        "A beleza da fragilidade humana",
        "Aceitar as próprias imperfeições",
        "A jornada do autoconhecimento",
        "Quem sou eu além dos rótulos?",
        "A identidade que construímos para os outros",
        "Ser autêntico em um mundo de aparências",
        "A coragem de ser diferente",
        "Não caber nos padrões",
        "A liberdade de ser quem se é",
        "O preço da liberdade",
        "Liberdade e responsabilidade",
        "O coletivo e o individual no Brasil",
        "Pensar no próximo em um mundo individualista",
        "A ética do cuidado",
        "Cuidar como ato de amor",
        "O amor que transforma",
        "O amor que liberta versus o amor que prende",
        "Amar sem posse",
        "A saudade como prova de amor",
        "O primeiro amor e suas marcas",
        "O amor maduro",
        "Relacionamento e respeito",
        "A comunicação como base do amor",
        "O diálogo que cura",
        "A palavra que machuca",
        "O silêncio que diz tudo",
        "As coisas que não dizemos",
        "O abraço que fala mais que palavras",
        "A linguagem do corpo no Brasil",
        "O toque como forma de afeto",
        "A distância em tempos de conexão",
        "Estar conectado e sentir-se sozinho",
        "A tecnologia que aproxima e afasta",
        "O mundo real e o mundo virtual",
        "A inteligência artificial e o futuro do trabalho no Brasil",
        "O medo de ser substituído pela máquina",
        "Reinventar-se em um mundo que muda rápido",
        "Aprender a aprender",
        "A educação como libertação",
        "O conhecimento como poder",
        "A sabedoria que não vem dos livros",
        "A escola da vida",
        "O que a rua ensina",
        "A universidade da vivência",
        "Teoria e prática: o abismo brasileiro",
        "O Brasil que temos e o Brasil que queremos",
        "Sonhar com um país justo",
        "A justiça social como direito",
        "Cidadania como exercício diário",
        "O poder do voto consciente",
        "Participação comunitária e mudança",
        "O líder que nasce da comunidade",
        "A força do mutirão",
        "A solidariedade nas enchentes",
        "A mão estendida na tragédia",
        "O Brasil que se levanta",
        "A potência brasileira",
        "O talento desperdiçado",
        "A criatividade como recurso infinito",
        "Fazer muito com pouco: o jeito brasileiro",
        "A gambiarra como filosofia de vida",
        "Inovar na adversidade",
        "A beleza que nasce da dificuldade",
        "Flor que nasce no asfalto"
    ]
};
