topicsByLang.it = {
    easy: [
        "Il caffè al bar la mattina",
        "La pasta della nonna",
        "Il primo giorno di scuola",
        "La pizza del sabato sera",
        "Il gelato in estate",
        "La passeggiata serale",
        "Il pranzo della domenica",
        "La colazione al bar",
        "Il cornetto caldo appena sfornato",
        "Il cappuccino con la schiuma perfetta",
        "La moka sul fuoco",
        "Il profumo del ragù che cuoce",
        "La pasta al pomodoro",
        "Le lasagne della mamma",
        "La carbonara perfetta",
        "Il tiramisù fatto in casa",
        "La parmigiana di melanzane",
        "L'arancino o arancina",
        "La focaccia genovese",
        "La bruschetta con i pomodorini",
        "La mozzarella di bufala",
        "Il pane appena sfornato",
        "Il panino con la mortadella",
        "La granita siciliana con la brioche",
        "Il tramezzino al bar",
        "L'aperitivo con gli amici",
        "Lo spritz al tramonto",
        "Il limoncello dopo cena",
        "Il vino della casa",
        "La grappa del nonno",
        "Il chinotto",
        "L'aranciata San Pellegrino",
        "La cena della vigilia di Natale",
        "Il panettone o il pandoro",
        "La tombola a Natale",
        "La calza della Befana",
        "Il cenone di Capodanno",
        "La colomba a Pasqua",
        "L'uovo di Pasqua con la sorpresa",
        "La pastiera napoletana",
        "Ferragosto al mare",
        "Il Carnevale e le maschere",
        "Le chiacchiere di Carnevale",
        "La notte di San Lorenzo",
        "I fuochi d'artificio della festa del patrono",
        "La sagra del paese",
        "La festa della mamma",
        "Il mercato rionale",
        "Il fruttivendolo sotto casa",
        "Il macellaio di fiducia",
        "Il giornalaio all'angolo",
        "Il tabaccaio",
        "La farmacia di turno",
        "La fila alle Poste",
        "Il barbiere del quartiere",
        "La piazza del paese",
        "La fontanella dell'acqua",
        "I panni stesi al sole",
        "Il balcone fiorito",
        "Le persiane verdi",
        "La vespa parcheggiata",
        "Il motorino a sedici anni",
        "La patente di guida",
        "La FIAT cinquecento",
        "Il treno regionale in ritardo",
        "L'autostrada d'estate",
        "La gita al mare",
        "La spiaggia libera",
        "Il pedalò",
        "Il costume da bagno nuovo",
        "La crema solare",
        "Il castello di sabbia",
        "La passeggiata sul lungomare",
        "La cena in terrazza",
        "Il pisolino dopo pranzo",
        "Il telegiornale delle otto",
        "La schedina del Totocalcio",
        "Guardare la partita al bar",
        "Il fantacalcio",
        "Il derby della città",
        "La maglia della squadra del cuore",
        "L'album delle figurine Panini",
        "La bicicletta da bambino",
        "Il monopattino",
        "Il pallone nel cortile",
        "Giocare a nascondino",
        "Il gioco della campana",
        "Le biglie",
        "La ricreazione a scuola",
        "Il diario scolastico",
        "Il grembiule a scuola",
        "La cartella nuova",
        "La merenda del pomeriggio",
        "I nonni che vengono a pranzo",
        "La telefonata alla mamma",
        "Le foto di famiglia",
        "Il battesimo del nipotino",
        "La prima comunione",
        "Il matrimonio in chiesa",
        "Il bouquet della sposa",
        "I confetti colorati",
        "Le bomboniere",
        "La serenata sotto il balcone",
        "San Valentino all'italiana",
        "Il primo appuntamento",
        "La cena a lume di candela",
        "Il cinema all'aperto d'estate",
        "La musica dalla finestra",
        "Cantare sotto la doccia",
        "Il karaoke con gli amici",
        "Sanremo e le sue canzoni",
        "Il Festival di Sanremo",
        "La canzone dell'estate",
        "Il Natale in famiglia",
        "L'albero di Natale o il presepe",
        "Il presepe vivente",
        "I mercatini di Natale",
        "Le luminarie natalizie",
        "La letterina a Babbo Natale",
        "La recita di Natale a scuola",
        "Il veglione di Capodanno",
        "Le lenticchie a mezzanotte",
        "I botti di Capodanno",
        "La Befana vien di notte",
        "Il primo dell'anno al mare",
        "La gita fuori porta",
        "La scampagnata di Pasquetta",
        "Il picnic in campagna",
        "Il gelato passeggiando",
        "Le vacanze al mare",
        "Le vacanze in montagna",
        "Il rifugio in montagna",
        "La settimana bianca",
        "Il lago d'estate",
        "La vendemmia in autunno",
        "La raccolta delle olive",
        "I funghi nel bosco",
        "Le castagne arrosto",
        "La polenta d'inverno",
        "Il minestrone della sera",
        "La zuppa di legumi",
        "La frittata con gli avanzi",
        "La piadina romagnola",
        "I supplì romani",
        "La pizza al taglio",
        "Il panzerotto pugliese",
        "La farinata ligure",
        "I cicchetti veneziani",
        "Lo street food italiano",
        "Il mercato del pesce",
        "La frittura di pesce",
        "Le cozze al vapore",
        "Gli spaghetti alle vongole",
        "Il risotto alla milanese",
        "La bistecca alla fiorentina",
        "I tortellini in brodo",
        "Il pesto alla genovese",
        "La cacio e pepe",
        "L'amatriciana",
        "La gricia",
        "L'olio extravergine d'oliva",
        "Il parmigiano reggiano",
        "Il prosciutto di Parma",
        "La burrata pugliese",
        "Il pecorino romano",
        "La nutella sul pane",
        "Il cornetto alla crema",
        "La crostata della nonna",
        "I biscotti della colazione",
        "La cassata siciliana",
        "I cannoli siciliani",
        "Il babà napoletano",
        "Le sfogliatelle",
        "Il panna cotta",
        "Lo zabaione",
        "Le chiacchiere e la sanguinaccio",
        "La domenica allo stadio",
        "Il calciomercato d'estate",
        "La nazionale di calcio",
        "I Mondiali di calcio",
        "La coppa dei campioni",
        "Il Giro d'Italia",
        "La Formula Uno",
        "La Ferrari rossa",
        "Il motorino truccato",
        "La Lambretta vintage",
        "I Ray-Ban del nonno",
        "Le scarpe nuove",
        "Lo shopping saldi di gennaio",
        "Il vestito della festa",
        "La cravatta del papà",
        "I jeans preferiti",
        "Il grembiule della nonna",
        "L'orto del nonno",
        "Il basilico sul balcone",
        "I gerani alla finestra",
        "Il gatto del quartiere",
        "Il cane al parco",
        "La passeggiata con il cane",
        "Il parco giochi",
        "L'altalena al parco",
        "La fontana in piazza",
        "Le campane della chiesa",
        "Il profumo della lavanda",
        "Il rumore delle cicale"
    ],
    medium: [
        "Il rapporto tra italiani e il cibo",
        "Perché gli italiani gesticolano tanto",
        "La rivalità tra Nord e Sud",
        "Il campanilismo tra paesi vicini",
        "Il significato dell'aperitivo nella vita sociale",
        "La cultura del caffè in Italia",
        "Perché il cappuccino non si beve dopo le undici",
        "La sacralità della ricetta originale",
        "Il dibattito carbonara con o senza panna",
        "Pizza napoletana contro pizza romana",
        "Perché la pasta va cotta al dente",
        "Il ruolo della mamma italiana",
        "La nonna come custode delle tradizioni",
        "Il pranzo della domenica come rito familiare",
        "Vivere con i genitori fino a trent'anni",
        "Il rapporto tra genitori e figli in Italia",
        "Quando i figli lasciano il nido",
        "Il fidanzamento all'italiana",
        "Le dinamiche del condominio",
        "Il vicino di casa ideale",
        "La vita di quartiere",
        "Il bar come centro sociale",
        "La piazza come luogo di incontro",
        "Il rito dell'aperitivo",
        "La passeggiata serale come tradizione",
        "Il significato del lunedì per gli italiani",
        "Il rapporto degli italiani con il lunedì mattina",
        "L'arte di fare la fila in Italia",
        "La burocrazia italiana vista dal cittadino",
        "Il rapporto degli italiani con gli orari",
        "La puntualità in Italia",
        "Il traffico nelle grandi città",
        "La doppia fila come sport nazionale",
        "Lo sciopero dei mezzi pubblici",
        "Il pendolarismo quotidiano",
        "La vita da fuorisede",
        "Trasferirsi in un'altra città per lavoro",
        "La nostalgia del proprio paese",
        "Il dialetto come lingua del cuore",
        "Le espressioni che esistono solo in dialetto",
        "Le differenze regionali nel carattere",
        "Lo stereotipo del romano e del milanese",
        "Napoli vista da chi non ci è mai stato",
        "Il fascino di Roma per i romani",
        "Milano e la frenesia della vita moderna",
        "La dolce vita esiste ancora",
        "Il significato di fare bella figura",
        "L'importanza dell'apparenza nella cultura italiana",
        "L'eleganza italiana nel quotidiano",
        "La moda come espressione culturale",
        "Il Made in Italy nel mondo",
        "L'artigianato italiano che resiste",
        "Le botteghe storiche che chiudono",
        "Il centro storico che si svuota",
        "I borghi abbandonati che rinascono",
        "Il turismo di massa nelle città d'arte",
        "Venezia e il problema dell'overtourism",
        "Firenze tra residenti e turisti",
        "La Costiera Amalfitana d'estate",
        "Le isole italiane come paradiso",
        "Il Sud come meta riscoperta",
        "La montagna italiana d'inverno e d'estate",
        "Il rapporto degli italiani con il mare",
        "L'ombrellone prenotato all'alba",
        "La spiaggia libera contro lo stabilimento",
        "Ferragosto come rito collettivo",
        "Le ferie d'agosto sacre e immutabili",
        "Il rientro dalle vacanze",
        "Settembre come nuovo inizio",
        "L'anno scolastico che ricomincia",
        "Il rapporto degli italiani con la scuola",
        "L'esame di maturità come rito di passaggio",
        "L'università italiana tra pregi e difetti",
        "La fuga dei cervelli all'estero",
        "I giovani italiani e il futuro",
        "Il lavoro precario e i sogni",
        "L'imprenditoria familiare in Italia",
        "Il negozio sotto casa contro il centro commerciale",
        "Lo shopping online e i negozi di quartiere",
        "Il mercato rionale come esperienza sociale",
        "La contrattazione al mercato",
        "Il rapporto degli italiani con il risparmio",
        "La casa di proprietà come obiettivo di vita",
        "Ristrutturare una casa antica",
        "Il condominio e le sue regole non scritte",
        "Il terrazzo come stanza in più",
        "La cucina come cuore della casa",
        "La tavola apparecchiata come gesto d'amore",
        "L'importanza di mangiare insieme",
        "La convivialità a tavola",
        "L'ospitalità italiana verso gli stranieri",
        "Il caffè offerto come gesto di amicizia",
        "Il caffè sospeso come tradizione solidale",
        "La cultura del dono in Italia",
        "Le bomboniere e il loro significato",
        "Il matrimonio italiano come grande evento",
        "Le tradizioni nuziali regionali",
        "Il battesimo e la scelta del padrino",
        "I nomi di famiglia tramandati",
        "Le superstizioni italiane più diffuse",
        "Il malocchio e i rimedi della nonna",
        "Il numero diciassette porta sfortuna",
        "Il gatto nero e il sale versato",
        "I proverbi italiani e la loro saggezza",
        "I modi di dire che solo gli italiani capiscono",
        "L'ironia italiana come arma di sopravvivenza",
        "La commedia all'italiana come specchio sociale",
        "Il cinema italiano di ieri e di oggi",
        "La musica italiana tra tradizione e innovazione",
        "Il Festival di Sanremo come evento nazionale",
        "L'opera lirica come patrimonio culturale",
        "Il teatro dialettale",
        "La musica napoletana nel mondo",
        "Il cantautore italiano e la poesia",
        "La colonna sonora dei film di Morricone",
        "Il calcio come religione laica",
        "Il tifo allo stadio",
        "Il calciomercato come soap opera estiva",
        "Il fantacalcio e le amicizie rovinate",
        "La nazionale e il senso di unità",
        "Il Giro d'Italia e la passione per il ciclismo",
        "La Formula Uno e il mito Ferrari",
        "Lo sport minore che diventa grande",
        "La pallavolo italiana nel mondo",
        "L'atletica e i campioni italiani",
        "Il rapporto degli italiani con lo sport",
        "Fare sport o guardarlo dal divano",
        "La domenica sportiva",
        "I giochi da tavolo nelle sere d'inverno",
        "La briscola e il tresette al bar",
        "La tombola di Natale in famiglia",
        "Il totocalcio e il sogno del tredici",
        "Il Superenalotto e la speranza",
        "Il gratta e vinci al tabaccaio",
        "La televisione italiana di ieri e di oggi",
        "I programmi che hanno unito l'Italia",
        "Il telegiornale e le sue liturgie",
        "I talk show del pomeriggio",
        "I reality show e il loro successo",
        "La radio italiana e le sue voci",
        "I social media e gli italiani",
        "L'italiano e il linguaggio di internet",
        "Le parole inglesi che invadono l'italiano",
        "La difesa della lingua italiana",
        "I neologismi che entrano nell'uso comune",
        "Il galateo italiano moderno",
        "Le regole non scritte della convivenza",
        "L'educazione e le buone maniere",
        "Il lei e il tu nella conversazione",
        "La stretta di mano e il bacio sulla guancia",
        "L'arte della conversazione al bar",
        "Parlare del tempo come rito sociale",
        "La lamentela come forma d'arte italiana",
        "L'arte di arrangiarsi",
        "La creatività italiana nata dalla necessità",
        "Il design italiano nel mondo",
        "L'architettura italiana tra antico e moderno",
        "Il paesaggio italiano come opera d'arte",
        "La tutela del patrimonio culturale",
        "I musei italiani e il loro futuro",
        "L'arte contemporanea in Italia",
        "La cucina regionale come identità",
        "Le ricette che cambiano da regione a regione",
        "Il cibo come argomento di discussione infinito",
        "La dieta mediterranea come stile di vita",
        "Il vino italiano e le sue storie",
        "L'enoteca come luogo di cultura",
        "La birra artigianale italiana",
        "Il boom delle gelaterie artigianali",
        "Lo slow food e il ritorno alla qualità",
        "Il biologico al supermercato",
        "Il rapporto tra città e campagna",
        "La vita in provincia",
        "Il paese che si svuota",
        "La città che non dorme mai",
        "Il coworking e il lavoro da remoto",
        "Lo smart working all'italiana",
        "L'equilibrio tra lavoro e vita privata",
        "La pausa pranzo sacra",
        "Il caffè alla macchinetta in ufficio",
        "Il collega che parla sempre di calcio",
        "Le chat di gruppo del condominio",
        "Le chat di classe dei genitori",
        "Il gruppo WhatsApp della famiglia",
        "La suocera italiana",
        "Il Natale a casa di chi",
        "Le feste comandate e gli obblighi familiari",
        "La villeggiatura estiva",
        "Il bagno dopo mangiato",
        "Le tre ore di digestione",
        "Il colpo d'aria come malattia nazionale",
        "La mamma che dice copriti",
        "I rimedi della nonna",
        "L'erboristeria e la medicina naturale",
        "Il rapporto degli italiani con la salute",
        "La gita scolastica come avventura",
        "Il compagno di banco",
        "Il professore che ti ha cambiato la vita",
        "La mensa scolastica e i suoi misteri",
        "L'ansia da esame universitario"
    ],
    hard: [
        "Il significato della famiglia nella società moderna",
        "L'arte di vivere con lentezza",
        "Il peso delle aspettative familiari",
        "Essere figli unici nella cultura italiana",
        "Il senso di colpa di chi parte",
        "Tornare al proprio paese dopo anni all'estero",
        "Le radici come àncora o come catena",
        "Il dialetto che si perde con le generazioni",
        "La memoria dei nonni che se ne vanno",
        "L'eredità immateriale della famiglia",
        "Il significato di casa per un italiano",
        "Quando la casa d'infanzia viene venduta",
        "I luoghi della memoria che cambiano",
        "La nostalgia di un'Italia che non c'è più",
        "Il rapporto tra tradizione e modernità",
        "Conservare le tradizioni senza restarne prigionieri",
        "Il peso della storia su un paese antico",
        "Vivere circondati dalla bellezza e non vederla più",
        "L'abitudine che cancella la meraviglia",
        "Il turista che vede ciò che il residente ignora",
        "L'identità italiana tra locale e globale",
        "Sentirsi italiani o sentirsi del proprio paese",
        "Il regionalismo come ricchezza e come limite",
        "L'unità d'Italia compresa dal cuore",
        "Il Mezzogiorno tra orgoglio e sofferenza",
        "Il Nord che non capisce il Sud e viceversa",
        "La questione meridionale vista dai giovani",
        "Emigrare dal proprio paese per necessità",
        "La fuga dei cervelli come ferita collettiva",
        "Restare e lottare o partire e crescere",
        "Il coraggio di tornare dove tutti se ne vanno",
        "Ricostruire la propria vita in un paese che si svuota",
        "Il significato del lavoro nella cultura italiana",
        "L'artigiano che non trova apprendisti",
        "Il sapere manuale che rischia di scomparire",
        "La bottega del padre che il figlio non vuole",
        "L'impresa familiare e il passaggio generazionale",
        "Il precariato come condizione esistenziale",
        "Sognare in grande in un paese che pensa in piccolo",
        "La burocrazia come ostacolo ai sogni",
        "La pazienza italiana come virtù e come rassegnazione",
        "L'arte di arrangiarsi tra genialità e sopravvivenza",
        "La creatività nata dalla mancanza",
        "Il bello come necessità e non come lusso",
        "L'estetica nella vita quotidiana italiana",
        "Il gusto come educazione culturale",
        "Il rapporto tra cibo e identità personale",
        "Cucinare come atto d'amore",
        "La ricetta della nonna come testamento morale",
        "Il cibo come linguaggio universale",
        "Il pasto condiviso come rituale sacro",
        "La tavola come luogo di pace e di conflitto",
        "Il significato profondo dell'ospitalità",
        "Aprire la propria casa a uno sconosciuto",
        "La fiducia nel prossimo nella società di oggi",
        "Il senso di comunità che si perde nelle città",
        "La solitudine nelle metropoli italiane",
        "Invecchiare soli in un paese di famiglie",
        "Il ruolo degli anziani nella società moderna",
        "La saggezza che non viene più ascoltata",
        "Il tempo che scorre diversamente al Sud",
        "La fretta del Nord come malattia dell'anima",
        "L'ozio come arte perduta",
        "Il diritto alla lentezza in un mondo veloce",
        "La contemplazione come forma di resistenza",
        "Il silenzio come lusso nella vita moderna",
        "Il rumore delle città e il bisogno di quiete",
        "La natura come rifugio dall'iperconnessione",
        "Il rapporto tra uomo e paesaggio in Italia",
        "Il territorio che cambia sotto i nostri occhi",
        "La responsabilità verso il patrimonio ereditato",
        "Custodire la bellezza per chi verrà dopo",
        "L'arte come bene comune e responsabilità",
        "La cultura come cura per l'anima",
        "La lettura come atto di resistenza",
        "Il valore del teatro in un'epoca di schermi",
        "La musica come ponte tra generazioni",
        "L'opera lirica e le emozioni senza tempo",
        "Il cantautore come poeta del quotidiano",
        "Le parole delle canzoni che ci hanno formato",
        "La colonna sonora della propria vita",
        "I ricordi legati ai profumi dell'infanzia",
        "Il profumo del sugo della domenica come macchina del tempo",
        "La madeleine italiana",
        "I sapori che non si trovano più",
        "La semplicità perduta a tavola",
        "L'abbondanza come virtù o come eccesso",
        "Il rapporto con lo spreco alimentare",
        "La sobrietà come forma di eleganza",
        "L'eleganza interiore oltre l'apparenza",
        "La bella figura come maschera sociale",
        "L'autenticità in una cultura dell'apparenza",
        "Essere se stessi in una società del giudizio",
        "Il conformismo italiano nelle piccole comunità",
        "La libertà individuale e il peso del giudizio altrui",
        "Il coraggio di essere diversi in provincia",
        "La pressione sociale del matrimonio e dei figli",
        "Scegliere una vita non convenzionale in Italia",
        "Il rapporto tra fede e cultura nella società italiana",
        "La spiritualità oltre la religione organizzata",
        "Le chiese vuote e il bisogno di sacro",
        "Le feste religiose come patrimonio laico",
        "Il Natale tra consumismo e raccoglimento",
        "Il senso della Pasqua oltre il cioccolato",
        "I riti di passaggio nella vita italiana",
        "Il significato della maturità come momento di crescita",
        "La prima volta lontano da casa",
        "Costruire la propria identità lontano dalla famiglia",
        "Il ritorno a casa come adulti",
        "Guardare i propri genitori invecchiare",
        "Il momento in cui i ruoli si invertono",
        "La cura dei genitori anziani",
        "L'importanza di dire le cose prima che sia tardi",
        "Le parole non dette nella cultura italiana",
        "L'affetto espresso attraverso il cibo",
        "L'amore italiano tra passione e pudore",
        "La gelosia come espressione culturale",
        "L'amicizia che dura tutta la vita",
        "Gli amici d'infanzia e come cambiano i legami",
        "La piazza come teatro delle relazioni umane",
        "Il bar come confessionale laico",
        "Le confidenze al bancone del bar",
        "La solitudine di chi non ha un bar di fiducia",
        "Il senso di appartenenza a un luogo",
        "Quando il proprio luogo non esiste più",
        "La memoria collettiva di un paese",
        "Le storie che si raccontano in piazza",
        "L'oralità come forma di cultura",
        "I proverbi come filosofia popolare",
        "La saggezza nascosta nelle filastrocche",
        "L'umorismo italiano come filosofia di vita",
        "Ridere per non piangere",
        "La leggerezza come forma di profondità",
        "L'ironia come scudo e come ponte",
        "Il sorriso come prima forma di accoglienza",
        "La gentilezza in un mondo sempre più duro",
        "Il valore della cortesia quotidiana",
        "La bellezza dei piccoli gesti",
        "La poesia nascosta nella vita di tutti i giorni",
        "Trovare il sacro nel quotidiano",
        "La gratitudine per le cose semplici",
        "Il valore dell'imperfezione",
        "La bellezza delle cose vissute",
        "Il fascino delle rovine e del tempo che passa",
        "L'Italia come museo a cielo aperto",
        "Vivere in un'opera d'arte e dimenticarsene",
        "La responsabilità di chi abita la bellezza",
        "Il futuro dell'Italia visto dai suoi giovani",
        "L'ottimismo come atto di coraggio",
        "La speranza come tratto culturale italiano",
        "L'Italia che resiste e si reinventa",
        "Il genio italiano tra mito e realtà",
        "La dolce vita come filosofia esistenziale",
        "Il tempo sospeso dell'ora di pranzo",
        "Il crepuscolo sul Mediterraneo",
        "La luce italiana che ha ispirato i pittori",
        "Il paesaggio interiore di ogni italiano",
        "Le contraddizioni che rendono l'Italia unica",
        "Amare l'Italia nonostante tutto",
        "Il patriottismo silenzioso degli italiani",
        "L'orgoglio di essere italiani nel mondo",
        "L'Italia vista con gli occhi di chi è partito",
        "Il ritorno come atto d'amore",
        "La riconciliazione con le proprie origini",
        "Fare pace con il luogo da cui si viene",
        "Il significato di appartenere a una terra",
        "La terra come madre e come destino",
        "Le mani nella terra come gesto ancestrale",
        "Il contadino come custode della sapienza",
        "La vendemmia come metafora della vita",
        "Il ciclo delle stagioni come insegnamento",
        "La pazienza di chi aspetta il raccolto",
        "Il tempo della natura contro il tempo degli uomini",
        "L'acqua come elemento della cultura italiana",
        "Il mare come orizzonte di libertà",
        "Il Mediterraneo come culla di civiltà",
        "Le isole come luoghi dell'anima",
        "La montagna come spazio di introspezione",
        "Il vulcano come simbolo della passione italiana",
        "La luce del Sud come stato d'animo",
        "La nebbia del Nord come condizione esistenziale",
        "Le quattro stagioni vissute all'italiana",
        "La primavera come rinascita collettiva",
        "L'estate infinita dei ricordi d'infanzia",
        "L'autunno come stagione della riflessione",
        "L'inverno attorno al camino",
        "Il fuoco come centro della casa",
        "La fiamma che unisce le generazioni",
        "Il racconto attorno al fuoco",
        "Le storie che ci hanno reso chi siamo",
        "La narrazione come bisogno umano fondamentale",
        "Il bisogno di raccontare e di essere ascoltati",
        "L'ascolto come forma d'amore",
        "Il tempo dedicato all'altro come dono supremo",
        "Il coraggio della vulnerabilità",
        "La forza che si trova nella fragilità",
        "Il significato di perdonare nella cultura italiana",
        "L'onore come valore antico e moderno",
        "La dignità nel lavoro umile",
        "Il rispetto per chi fa le cose con le mani"
    ]
};