topicsByLang.fr = {
    easy: [
        "La bise",
        "Le croissant du matin",
        "La baguette sous le bras",
        "Le pain au chocolat ou la chocolatine",
        "Le cafe au comptoir",
        "Le cafe-creme du matin",
        "Le petit noir",
        "La terrasse de cafe",
        "Le bistrot du coin",
        "Le zinc",
        "Le garcon de cafe",
        "Le pourboire",
        "La carte ou le menu",
        "Le plat du jour",
        "Le fromage avant le dessert",
        "Le plateau de fromages",
        "Le vin rouge avec le fromage",
        "Le beaujolais nouveau",
        "Le champagne",
        "Trinquer en se regardant dans les yeux",
        "Le digestif",
        "Le trou normand",
        "Le repas du dimanche",
        "Le dejeuner de famille",
        "Le gouter des enfants",
        "La tartine de beurre",
        "Les crepes de la Chandeleur",
        "La galette des Rois",
        "La buche de Noel",
        "Le reveillon",
        "Le marche de Noel",
        "La fete des voisins",
        "La Fete de la musique",
        "Le 14 Juillet",
        "Le bal des pompiers",
        "Le defile du 14 Juillet",
        "Le muguet du 1er Mai",
        "La fete du travail",
        "Le pont du mois de mai",
        "Faire le pont",
        "Les jours feries",
        "La pause dejeuner sacree",
        "La cantine",
        "Le ticket restaurant",
        "La machine a cafe au bureau",
        "Les ragots a la machine a cafe",
        "Le marche du dimanche matin",
        "Les etals du marche",
        "Choisir ses legumes au marche",
        "Manger local",
        "Manger de saison",
        "Le potager",
        "Le jardin ouvrier",
        "La main verte",
        "Les herbes de Provence",
        "Le thym et le romarin",
        "L'huile d'olive",
        "La cuisine du sud",
        "La bouillabaisse",
        "Le cassoulet",
        "La choucroute",
        "La raclette",
        "La fondue savoyarde",
        "Le pot-au-feu",
        "Le boeuf bourguignon",
        "La blanquette de veau",
        "Le coq au vin",
        "La ratatouille",
        "La quiche lorraine",
        "Les escargots de Bourgogne",
        "Les cuisses de grenouille",
        "Le foie gras",
        "Le camembert",
        "Le roquefort",
        "Le comte",
        "Un pays de 400 fromages",
        "Le vin et le fromage, un mariage",
        "Le chef etoile",
        "Le guide Michelin",
        "Le bistrot gastronomique",
        "La brasserie parisienne",
        "Le serveur parisien",
        "L'addition, s'il vous plait",
        "Le cafe gourmand",
        "Le paris-brest",
        "L'eclair au chocolat",
        "La tarte Tatin",
        "Le mille-feuille",
        "La creme brulee",
        "Le macaron",
        "La patisserie francaise",
        "La vitrine du patissier",
        "Le gout du beurre",
        "La bonne baguette croustillante",
        "Le levain",
        "La farine et l'eau",
        "L'odeur du pain frais",
        "La soupe de grand-mere",
        "Le bouillon",
        "La cuisine mijotee",
        "Le feu doux",
        "La patience en cuisine",
        "Les recettes transmises",
        "Le cahier de recettes de famille",
        "La table de fete",
        "Mettre les petits plats dans les grands",
        "La belle vaisselle",
        "La nappe blanche",
        "Manger ensemble",
        "Partager un repas",
        "Recevoir chez soi",
        "Le diner entre amis",
        "L'aperitif dinatoire",
        "Le vin d'honneur",
        "Le toast",
        "Porter un toast",
        "Le discours de mariage",
        "Le mariage a la mairie",
        "Le maire et son echarpe",
        "La mairie du village",
        "Le clocher",
        "Les cloches du dimanche",
        "Le son des cloches",
        "Le marche aux puces",
        "La brocante",
        "Chiner",
        "L'objet ancien",
        "Le chateau",
        "Les chateaux de la Loire",
        "La cathedrale",
        "Notre-Dame de Paris",
        "Les immeubles haussmanniens",
        "Le parquet qui craque",
        "La cheminee en marbre",
        "Les moulures au plafond",
        "L'appartement parisien",
        "La chambre de bonne",
        "Le sixieme etage sans ascenseur",
        "Les escaliers de service",
        "La loge de la concierge",
        "Le code de l'immeuble",
        "Le digicode",
        "La porte cochiere",
        "La cour interieure",
        "Les rideaux fermes",
        "Regarder par la fenetre",
        "La fenetre sur cour",
        "Le metro parisien",
        "Le metro aux heures de pointe",
        "La ligne 13",
        "Le plan du metro",
        "Les couloirs du metro",
        "Le musicien du metro",
        "L'accordeon dans le metro",
        "La Tour Eiffel",
        "Les Champs-Elysees",
        "Montmartre",
        "Le Sacre-Coeur",
        "Saint-Germain-des-Pres",
        "Le Quartier latin",
        "Le Marais",
        "Belleville",
        "La Butte-aux-Cailles",
        "Le canal Saint-Martin",
        "Se promener au bord du canal",
        "Les berges de la Seine",
        "Les quais de Seine",
        "Un pique-nique au bord de l'eau",
        "Le pique-nique",
        "Le panier de pique-nique",
        "La nappe a carreaux",
        "Le vin en pique-nique",
        "Le saucisson",
        "Le pate de campagne",
        "Les rillettes",
        "Le pain de campagne",
        "La tartine",
        "Le beurre sale",
        "Les croutons dans la soupe",
        "Bouquiner au bord de l'eau",
        "Le livre de poche",
        "La librairie de quartier",
        "Le bouquiniste",
        "La bibliotheque",
        "Le jardin du Luxembourg",
        "Les Tuileries",
        "Le Palais-Royal",
        "Les passages couverts",
        "Les grands boulevards",
        "Flaner dans les rues",
        "Se perdre dans une ville",
        "Le charme des ruelles",
        "Un dimanche pluvieux",
        "Le bruit de la pluie sur les toits",
        "Les toits de Paris",
        "Paris vu d'en haut",
        "La vue sur les toits",
        "Le balcon parisien",
        "La cour de recreation",
        "Les jeux d'enfants",
        "La marelle",
        "Les billes",
        "Le gouter du mercredi",
        "Le mercredi des enfants",
        "L'ecole maternelle",
        "Le cartable",
        "La rentree des classes",
        "L'odeur des cahiers neufs",
        "La dictee",
        "Le tableau noir",
        "La craie",
        "Le maitre d'ecole",
        "L'instituteur",
        "Le Louvre",
        "Le musee d'Orsay",
        "Le Centre Pompidou",
        "Le musee gratuit le premier dimanche",
        "Flaner dans un musee",
        "La Joconde",
        "Le banc public",
        "S'asseoir sur un banc",
        "Observer les passants",
        "Le gardien d'immeuble",
        "La cage d'escalier",
        "Le palier",
        "Le bruit des voisins",
        "Vivre en appartement",
        "Le village francais",
        "La boulangerie du village",
        "Le dernier commerce du village",
        "La SNCF",
        "Le retard du train",
        "Le compostage du billet",
        "Le quai de gare",
        "L'attente sur le quai",
        "Les retrouvailles a la gare",
        "Les adieux sur le quai",
        "Le TGV a tout change",
        "Le petit dejeuner au lit",
        "Le dimanche matin",
        "La grasse matinee",
        "Le reveil sans alarme",
        "Le dimanche apres-midi",
        "Le film du dimanche soir",
        "Le canape un jour de pluie",
        "Le plaid sur le canape",
        "La couverture en laine",
        "Le chocolat chaud",
        "Le feu de cheminee",
        "La petite robe noire",
        "Le beret",
        "La mariniere",
        "Le foulard",
        "Le parfum",
        "Chanel N.5",
        "Le stylo plume",
        "Le carnet Moleskine",
        "Le cahier de notes",
        "La lettre manuscrite",
        "Ecrire a la main",
        "Le papier cadeau",
        "L'emballage cadeau",
        "La petanque",
        "Le cochonnet",
        "Le terrain de boules",
        "Pointer ou tirer",
        "Le soleil du Midi",
        "La Provence",
        "Les cigales",
        "La lavande",
        "Les champs de lavande",
        "Le mistral",
        "La tramontane",
        "Le vent",
        "Le vent dans les cheveux",
        "La mer",
        "La Mediterranee",
        "L'Atlantique",
        "La Manche",
        "La Bretagne",
        "La cote sauvage",
        "Les falaises d'Etretat",
        "Le phare",
        "L'ile de Re",
        "La Corse",
        "La montagne",
        "Les Alpes",
        "Les Pyrenees",
        "Le Massif central",
        "Le Jura",
        "Les Vosges",
        "La randonnee",
        "Le sentier de grande randonnee",
        "Le GR20",
        "Le refuge de montagne",
        "Le sommet",
        "Le printemps",
        "Les bourgeons",
        "La nature qui s'eveille",
        "Le jardin au printemps",
        "La floraison",
        "Les cerisiers en fleurs",
        "Le muguet",
        "Les lilas",
        "Le parfum des fleurs",
        "Le marche aux fleurs",
        "Le bouquet de fleurs",
        "L'automne",
        "Les feuilles mortes",
        "Le vent d'automne",
        "La pluie d'octobre",
        "Le brouillard",
        "La brume matinale",
        "Le givre",
        "L'hiver",
        "Le froid qui mord",
        "La chaleur du foyer",
        "L'aube",
        "Le lever du soleil",
        "Le chant des oiseaux",
        "Le rossignol",
        "Le reveil",
        "Les rituels du matin",
        "Le bonbon d'autrefois",
        "La confiserie",
        "Le caramel",
        "Les Betises de Cambrai",
        "Le nougat de Montelimar",
        "Le calisson d'Aix",
        "La violette de Toulouse",
        "Les specialites regionales",
        "Le kouign-amann",
        "Les crpes bretonnes",
        "Le cidre",
        "Le calvados",
        "Le pastis",
        "L'anisette",
        "Les expressions regionales",
        "L'accent du sud",
        "L'accent parisien",
        "Les regionalismes",
        "Le verlan",
        "L'argot",
        "Le dictionnaire",
        "Le Petit Robert",
        "Le Larousse",
        "Hausser les epaules",
        "La moue",
        "Le sourire de circonstance",
        "Le sourire sincere",
        "Le rire",
        "Le fou rire",
        "Edith Piaf",
        "La vie en rose",
        "Non, je ne regrette rien",
        "Jacques Brel",
        "Ne me quitte pas",
        "Georges Brassens",
        "Les copains d'abord",
        "Barbara et Gottingen",
        "Serge Gainsbourg",
        "Charles Aznavour",
        "La boheme",
        "Jean Ferrat",
        "Leo Ferre",
        "La radio",
        "Le transistor",
        "La musique dans la rue",
        "Le concert en plein air",
        "Le festival",
        "Les Francofolies",
        "Le Printemps de Bourges",
        "Les Vieilles Charrues",
        "Le cinema de quartier",
        "La salle obscure",
        "Le pop-corn ou pas au cinema",
        "La seance de minuit",
        "Le generique de fin",
        "Rester jusqu'au generique",
        "Les dialogues d'Audiard",
        "Les tontons flingueurs",
        "Moliere",
        "Le theatre",
        "Les trois coups",
        "Le lever de rideau",
        "Le football",
        "Zidane",
        "Le rugby",
        "Le Tournoi des Six Nations",
        "La troisieme mi-temps",
        "Le cyclisme",
        "Le Tour de France",
        "Le maillot jaune",
        "L'etape de montagne",
        "Le peloton",
        "Le PMU",
        "Le tierce",
        "Le loto",
        "Le parc urbain",
        "Le square",
        "Le jardin public",
        "Le kiosque a musique",
        "Le manege",
        "Le carrousel",
        "La photo en noir et blanc",
        "L'album photo de famille",
        "La Reunion",
        "La Martinique",
        "La Guadeloupe",
        "Le breton",
        "L'occitan",
        "Le basque",
        "Le corse",
        "L'alsacien",
        "Le salon de l'agriculture",
        "L'apero",
        "La Marseillaise",
        "Le drapeau tricolore",
        "Marianne",
        "Le maquillage",
        "Le baccalaureat",
        "Le concours",
        "La prepa",
        "Le silence en montagne",
        "Le geste francais",
        "La Coupe du monde 1998",
        "Le coup de tete",
        "La melee",
        "Les Guignols de l'info",
        "La salle d'attente",
        "Le cafe du premier rendez-vous",
        "Le premier rendez-vous",
        "Les grandes vacances",
        "Le comptoir",
        "Les discussions au comptoir",
        "Le cafe du commerce",
        "La Nouvelle Vague",
        "Godard et Truffaut",
        "Les 400 coups",
        "A bout de souffle",
        "Le mobilier urbain",
        "La sculpture dans l'espace public",
        "Le street art",
        "La nature en ville",
        "L'arbre en ville",
        "Le jardin partage",
        "Le circuit court",
        "La madeleine de Proust",
        "Un souvenir d'enfance",
        "Le silence de la bibliotheque",
        "Marcher longtemps",
        "Le vis-a-vis",
        "La foule du metro",
        "Le taxi de nuit",
        "Le dernier metro",
        "La nuit blanche",
        "Le drive-in n'existe pas en France",
        "La nostalgie de l'enfance",
        "La rentree",
        "Les acquis sociaux",
        "Le piston",
        "Arriver en retard",
        "Les bonnes manieres a table",
        "Le regard en terrasse",
        "Le coup de coeur",
        "Le coup de blues",
        "Les plaisirs simples",
        "Prendre son temps",
        "Le rituel du repas",
        "La convivialite",
        "Le savoir-faire artisanal",
        "Les metiers d'art",
        "L'apprentissage",
        "Apprendre avec ses mains",
        "Le travail bien fait",
        "Les RTT",
        "Les 35 heures",
        "Le stage non remunere",
        "La lettre de motivation",
        "Le CV parfait",
        "Le stress des examens",
        "La lecture",
        "Le plaisir de lire",
        "Le livre qu'on relit",
        "La chanson francaise",
        "La chanson a texte",
        "Ecouter une chanson en boucle",
        "La musique de notre adolescence",
        "Le rock francais",
        "Le rap francais",
        "Le film culte",
        "La replique culte",
        "Le cinema populaire",
        "Le vaudeville",
        "Raler, un sport national",
        "Le Francais qui se plaint",
        "Manifester dans la rue",
        "La banderole",
        "Le megaphone"
    ],
    medium: [
        "La flanerie",
        "L'esprit de l'escalier",
        "Le terroir",
        "Le savoir-vivre",
        "Le depaysement",
        "Le coup de foudre",
        "Le mal du pays",
        "Le spleen",
        "Le ras-le-bol",
        "Le cafard",
        "La nostalgie",
        "Le patrimoine",
        "La fraternite",
        "La politesse a la francaise",
        "Le systeme D",
        "La debrouillardise",
        "Le tutoiement et le vouvoiement",
        "Tutoyer ou vouvoyer",
        "Le quart d'heure de politesse",
        "La ponctualite",
        "Le savoir-faire",
        "L'art de la conversation",
        "La galanterie est-elle depassee",
        "Le charme a la francaise",
        "Draguer a la francaise",
        "Le romantisme",
        "La seduction",
        "La lenteur",
        "L'hospitalite a la francaise",
        "L'art culinaire francais",
        "La gastronomie au patrimoine de l'UNESCO",
        "Le repas gastronomique des Francais",
        "La nouvelle cuisine",
        "Le compagnonnage",
        "La fierte du travail",
        "La vocation",
        "Trouver sa voie",
        "Changer de vie",
        "Tout plaquer",
        "La reconversion professionnelle",
        "Vivre de sa passion",
        "L'ennui au travail",
        "Le bore-out",
        "Le burn-out a la francaise",
        "L'equilibre vie pro vie perso",
        "Le temps libre",
        "Le droit a la deconnexion",
        "La reunion qui aurait pu etre un email",
        "Le management a la francaise",
        "Le CDI, le graal",
        "La peur du chomage",
        "Pole emploi",
        "Le marche du travail",
        "L'entretien d'embauche",
        "Le reseau professionnel",
        "Le piston versus le merite",
        "L'ascenseur social en panne",
        "Les grandes ecoles",
        "La philo au bac",
        "La dissertation",
        "L'art de l'argumentation",
        "Le plan en trois parties",
        "L'autorite du professeur",
        "Le respect de l'enseignant",
        "Jules Ferry",
        "L'instruction obligatoire",
        "La rentree litteraire",
        "Le prix Goncourt",
        "Le prix Femina",
        "Le roman francais",
        "Les paroles qui marquent",
        "Le slam",
        "La poesie urbaine",
        "La culture de la rue",
        "L'humour francais",
        "L'ironie",
        "Le sarcasme",
        "Le second degre",
        "Le comique de l'absurde",
        "Le mot d'esprit",
        "Le calembour",
        "Le jeu de mots",
        "Le trait d'esprit au bon moment",
        "La repartie",
        "La comedie francaise",
        "Le cinema d'auteur",
        "Le film en version originale",
        "Le sous-titre",
        "L'emotion au cinema",
        "L'impressionnisme",
        "Monet et les nympheas",
        "La lumiere en peinture",
        "Cezanne et la Sainte-Victoire",
        "Renoir et la joie de vivre",
        "Matisse et la couleur",
        "Rodin et le mouvement",
        "L'art dans la ville",
        "L'embellissement urbain",
        "L'oeuvre qui bouleverse",
        "L'emotion devant un tableau",
        "La grogne sociale",
        "Le blocage des routes",
        "Le mouvement social",
        "La solidarite ouvriere",
        "La devise de la France",
        "Le modele social francais",
        "La solidarite nationale",
        "Les services publics",
        "L'ecole publique",
        "La gratuite de l'education",
        "L'universite pour tous",
        "L'exception culturelle francaise",
        "Le prix unique du livre",
        "Le charme de Paris",
        "Paris est-il surfait",
        "Paris versus la province",
        "La centralisation",
        "La vie en province",
        "Les villes moyennes",
        "La metropole",
        "Le train versus l'avion",
        "Le depart",
        "Le voyage",
        "L'ailleurs",
        "L'exotisme",
        "L'ouverture d'esprit",
        "La curiosite",
        "L'emerveillement",
        "Le regard d'enfant",
        "L'enfance",
        "L'alphabetisation",
        "La France rurale",
        "La patine du temps",
        "Les vieilles pierres",
        "Le patrimoine architectural",
        "La reconstruction de Notre-Dame",
        "L'architecture haussmannienne",
        "Le charme de l'ancien",
        "Le jardin secret",
        "La vie privee",
        "Le droit a l'intimite",
        "La provocation artistique",
        "Avec le temps",
        "La vie de quartier",
        "Le voisinage",
        "Les gens qui passent",
        "Le badaud",
        "La curiosite du promeneur",
        "Le hasard des rencontres",
        "Le ridicule ne tue pas",
        "Oser",
        "Le courage au quotidien",
        "La generosite",
        "Le benevolat",
        "L'entraide",
        "Les traditions familiales",
        "Le repas de Noel en famille",
        "Savoir choisir un vin",
        "L'art de la degustation",
        "La haute couture",
        "La mode parisienne",
        "Le chic decontracte",
        "L'elegance naturelle",
        "Le style plutot que la mode",
        "L'art du parfum",
        "L'odeur comme souvenir",
        "Les sens et la memoire",
        "Le gout de l'enfance",
        "La saveur retrouvee",
        "Les cinq sens",
        "Le toucher",
        "Le regard",
        "L'ecoute",
        "Savoir ecouter",
        "L'attention a l'autre",
        "La bienveillance",
        "La gentillesse",
        "La douceur",
        "La tendresse",
        "Les petites attentions",
        "Un geste qui touche",
        "La delicatesse",
        "Le tact",
        "La discretion",
        "Le secret",
        "Garder un secret",
        "La confiance",
        "La rancune",
        "Tourner la page",
        "Recommencer",
        "La sincerite",
        "La franchise",
        "Les reseaux sociaux",
        "Le like",
        "La validation par les autres",
        "Le selfie",
        "Se mettre en scene",
        "Le personal branding",
        "La deconnexion",
        "La detox numerique",
        "Eteindre son telephone",
        "Le silence du telephone",
        "Le SMS versus l'appel",
        "Le message vocal",
        "L'email du dimanche soir",
        "La boite mail debordante",
        "La notification permanente",
        "La concentration",
        "Le deep work",
        "L'aventure",
        "Le risque",
        "L'audace",
        "L'intuition",
        "Le journal intime",
        "Ecrire pour comprendre",
        "Mettre des mots sur ses emotions",
        "Gerer ses emotions",
        "La colere",
        "L'indignation",
        "La petite action locale",
        "L'ecologie au quotidien",
        "Le tri selectif",
        "Le zero dechet",
        "Le minimalisme",
        "Posseder moins",
        "Garder ou jeter",
        "L'attachement aux objets",
        "L'objet sentimental",
        "La valeur sentimentale",
        "Le don",
        "Donner sans attendre",
        "L'echange",
        "Le troc",
        "L'economie du partage",
        "Le covoiturage",
        "Le coliving",
        "La negociation",
        "Le compromis",
        "L'adolescence",
        "La crise d'adolescence",
        "La rebellion adolescente",
        "Grandir",
        "Devenir adulte",
        "L'education",
        "Elever un enfant",
        "La parentalite",
        "La relation parent-enfant",
        "Le sens du devoir",
        "L'honneur",
        "La parole donnee",
        "Tenir sa promesse",
        "La famille",
        "La famille recomposee",
        "Les liens du sang",
        "L'amitie",
        "Le meilleur ami",
        "L'ami d'enfance",
        "L'ami qu'on perd de vue",
        "Les retrouvailles",
        "Le temps de l'amitie",
        "La fidelite en amitie",
        "La jalousie entre amis",
        "Le groupe d'amis",
        "La bande de copains",
        "La soiree entre amis",
        "Le regret du lendemain",
        "Le remords",
        "Ce qu'on aurait du dire",
        "Ce qu'on n'a pas fait",
        "Les occasions manquees",
        "Le rendez-vous manque",
        "Attendre un appel",
        "Le message qu'on n'envoie pas",
        "Le brouillon jamais envoye",
        "Les mots gardes pour soi",
        "L'amour non dit",
        "La declaration",
        "Le courage d'aimer",
        "La peur d'aimer",
        "La jalousie",
        "La confiance en amour",
        "Le couple",
        "Vieillir ensemble",
        "La complicite",
        "Le silence complice",
        "Le regard qui suffit",
        "Les mains enlacees",
        "La tendresse au quotidien",
        "L'amour apres des annees",
        "Raviver la flamme",
        "La rupture",
        "Le deuil amoureux",
        "Se reconstruire apres une rupture",
        "L'amour de soi",
        "La validation",
        "L'approbation",
        "Parler d'argent en France",
        "Le tabou de l'argent",
        "Les energies renouvelables",
        "L'independance energetique",
        "L'agriculture francaise",
        "Le paysan",
        "Le premier tour et le second tour",
        "La determination",
        "La volonte",
        "Le sport et la tete",
        "Connaitre ses limites",
        "Accepter ses limites",
        "La fatigue",
        "Le repos",
        "Le sommeil",
        "Le reve",
        "Le cauchemar",
        "L'enthousiasme",
        "L'espoir",
        "La sagesse populaire",
        "Les proverbes",
        "Les dictons",
        "Les expressions francaises",
        "Avoir le cafard",
        "Poser un lapin",
        "Tomber dans les pommes",
        "Avoir la puce a l'oreille",
        "Mettre son grain de sel",
        "Couper la poire en deux",
        "La francophonie",
        "La langue francaise dans le monde",
        "Defendre la langue francaise",
        "Les anglicismes",
        "L'Academie francaise",
        "La richesse du vocabulaire",
        "Les mots qui n'existent pas en anglais",
        "Le mot juste",
        "La langue maternelle",
        "Parler plusieurs langues",
        "Le bilinguisme",
        "L'accent",
        "La langue qui evolue",
        "Les nouveaux mots",
        "Le sens des mots change",
        "Le malentendu",
        "La communication non verbale",
        "Le langage du corps",
        "Le geste",
        "La communaute",
        "Les racines",
        "D'ou vient-on",
        "Le developpement personnel",
        "La photographie",
        "L'effort de la montee",
        "La vue d'en haut",
        "Le vertige",
        "La peur du vide",
        "Affronter ses peurs",
        "Les peurs irrationnelles",
        "La phobie",
        "Ralentir",
        "Le slow living",
        "Savourer l'instant",
        "L'instant present",
        "Le carpe diem",
        "Vivre au jour le jour",
        "L'avenir incertain",
        "La planification",
        "Planifier ou improviser",
        "L'improvisation",
        "Le plan B",
        "Quand rien ne va comme prevu",
        "L'imprevu",
        "La surprise",
        "La bonne surprise",
        "Le cadeau inattendu",
        "Offrir",
        "L'art d'offrir",
        "Le cadeau parfait",
        "La calligraphie",
        "L'encre sur le papier",
        "Les notes dans la marge",
        "L'atelier",
        "La creation",
        "Le processus creatif",
        "L'inspiration",
        "La muse",
        "Le blocage creatif",
        "La page blanche",
        "Commencer",
        "Le premier pas",
        "L'elan",
        "La motivation",
        "La discipline",
        "La routine creative",
        "La routine",
        "La routine rassurante",
        "Briser la routine",
        "Les habitudes",
        "Changer ses habitudes",
        "L'aventure dans le quotidien",
        "Le naturel revient au galop",
        "Le blues de l'automne",
        "La chanson de Prevert",
        "L'ennui du dimanche",
        "Ne pas se prendre au serieux",
        "La legerete",
        "La gravite",
        "Le serieux",
        "Rire de soi",
        "L'autodersion",
        "La perseverance",
        "La tenacite",
        "La patience",
        "Savoir attendre",
        "L'attente",
        "La satisfaction",
        "Se contenter de ce qu'on a",
        "Dire merci",
        "La reconnaissance",
        "Le merci sincere",
        "Les petits mots",
        "Le mot doux",
        "Le billet glisse sous la porte",
        "La surprise du matin",
        "Le rendez-vous",
        "Le coup de telephone",
        "La nuit parisienne",
        "L'aube apres la fete",
        "La gueule de bois",
        "Le lendemain de fete",
        "Le trac",
        "Le trac avant de monter sur scene",
        "Prendre la parole en public",
        "Le discours improvise",
        "L'art de l'improvisation",
        "Le lacher-prise",
        "Faire confiance au moment",
        "L'esprit du moment",
        "La spontaneite",
        "La scene",
        "Le Quebec",
        "La Belgique francophone",
        "La Suisse romande",
        "Les DOM-TOM",
        "Le creole",
        "Les langues regionales",
        "Le melange des cultures",
        "Le metissage culturel",
        "La creolite",
        "La francophonie africaine",
        "Le stereotype",
        "Le cliche",
        "La generalisation",
        "Le prejuge",
        "La difference",
        "Celebrer la difference",
        "L'inclusion",
        "La diversite",
        "Le gardien de phare",
        "La solitude du gardien de phare",
        "L'ile deserte",
        "Le maquis corse",
        "La vendetta",
        "L'honneur familial",
        "Le referendum",
        "La place publique",
        "L'agora",
        "Le destin",
        "La chance",
        "Saisir sa chance",
        "L'opportunite",
        "Le moment juste",
        "Le bon moment pour agir",
        "L'hesitation",
        "Le doute",
        "L'indecision",
        "La prise de decision",
        "Decider vite ou bien",
        "Le regard sur l'autre",
        "Le grenier plein de souvenirs"
    ],
    hard: [
        "La joie de vivre",
        "La douceur de vivre",
        "La belle epoque",
        "Le droit a la paresse",
        "L'egalite des chances",
        "La liberte d'expression",
        "Le vivre-ensemble",
        "L'amour courtois",
        "L'amour impossible",
        "La passion versus la raison",
        "Le vague a l'ame",
        "Le bonheur est-il un choix",
        "Le petit bonheur du quotidien",
        "La these, l'antithese, la synthese",
        "Penser par soi-meme",
        "Le doute cartesien",
        "Je pense donc je suis",
        "L'existentialisme",
        "L'absurde selon Camus",
        "La nausee de Sartre",
        "La liberte selon Sartre",
        "Le role de l'intellectuel",
        "L'intellectuel de gauche",
        "Le debat d'idees",
        "La culture du debat",
        "L'art de la polemique",
        "Le pamphlet",
        "L'esprit critique",
        "La pensee unique",
        "La langue de bois",
        "Dire les choses telles qu'elles sont",
        "L'art de tourner autour du pot",
        "Le non-dit",
        "Le sous-entendu",
        "Lire entre les lignes",
        "La pudeur des sentiments",
        "Ne pas etaler ses emotions",
        "Le stoicisme au quotidien",
        "Il est interdit d'interdire",
        "Sous les paves, la plage",
        "Liberte, egalite, fraternite",
        "L'impot, un devoir civique",
        "Le consentement a l'impot",
        "Le savoir est-il un bien commun",
        "La culture pour tous",
        "La poesie est-elle morte",
        "Baudelaire et la modernite",
        "Les fleurs du mal",
        "Le spleen baudelairien",
        "Rimbaud et la desobaissance",
        "Verlaine et la melancolie",
        "Proust et la memoire involontaire",
        "Le temps perdu",
        "Le temps retrouve",
        "La memoire collective",
        "L'oubli necessaire",
        "Se souvenir ou avancer",
        "Le devoir de memoire",
        "L'histoire qui se repete",
        "Les lecons du passe",
        "L'idealisation du passe",
        "Le progres est-il un bien",
        "La modernite",
        "Le changement fait peur",
        "Resister au changement",
        "S'adapter ou disparaitre",
        "L'evolution des moeurs",
        "La tradition versus la modernite",
        "Preserver le passe",
        "La precision du langage",
        "L'eloquence",
        "L'art oratoire",
        "Le discours qui change tout",
        "Les grands discours de l'histoire",
        "La rhetorique",
        "Convaincre sans manipuler",
        "L'art de persuader",
        "Le silence en dit long",
        "Les mots qu'on ne dit pas",
        "Les mots qui blessent",
        "Les mots qui guerissent",
        "La puissance du langage",
        "Nommer les choses",
        "Dire non",
        "L'affirmation de soi",
        "La bravoure discrete",
        "L'anonymat du bien",
        "Le graffiti est-il de l'art",
        "L'art contemporain",
        "L'art est-il pour tous",
        "La rencontre qui change une vie",
        "Le hasard et la necessite",
        "La chance existe-t-elle",
        "Le kairos",
        "Choisir c'est renoncer",
        "Le dilemme",
        "La liberte de choix",
        "Trop de choix tue le choix",
        "La simplicite",
        "L'essentiel",
        "Aller a l'essentiel",
        "Le superflu",
        "Le luxe est-il necessaire",
        "Le luxe a la francaise",
        "La synesthesie du souvenir",
        "La bienveillance est-elle naive",
        "La gentillesse n'est pas une faiblesse",
        "Pardonner sans oublier",
        "L'imperfection assumee",
        "Le wabi-sabi a la francaise",
        "La beaute de l'imparfait",
        "Le defaut qui fait le charme",
        "Le paraaitre versus l'etre",
        "La facade",
        "Derriere la facade",
        "Les faux-semblants",
        "L'hypocrisie sociale",
        "Dire la verite",
        "La verite blesse-t-elle toujours",
        "Le mensonge pieux",
        "Le mensonge par omission",
        "La transparence",
        "Le droit a l'opacite",
        "La vie numerique",
        "L'identite numerique",
        "L'exhibitionnisme numerique",
        "L'attention fragmentee",
        "Le flux de travail",
        "L'etat de flow",
        "L'inconnu",
        "La prudence excessive",
        "Qui ne risque rien n'a rien",
        "Le pressentiment",
        "L'instinct",
        "L'ecriture comme therapie",
        "Les mots sur les maux",
        "L'intelligence emotionnelle",
        "La colere juste",
        "S'indigner est-ce agir",
        "L'activisme",
        "Penser global, agir local",
        "La decroissance",
        "Le materalisme",
        "L'accumulation",
        "Ce qui n'a pas de prix",
        "Le gratuit",
        "La gratuite est-elle possible",
        "La reciprocite",
        "Vivre en communaute",
        "L'individualisme",
        "L'individualisme versus le collectif",
        "L'interet general",
        "Le bien commun",
        "L'art du compromis",
        "Le consensus",
        "Le desaccord productif",
        "Le conflit necessaire",
        "La paix sociale",
        "Le dialogue social",
        "La mediation",
        "Ecouter l'autre camp",
        "La nuance",
        "Le monde n'est pas noir ou blanc",
        "La complexite",
        "Accepter la complexite",
        "La simplification excessive",
        "Le raccourci de pensee",
        "L'exception confirme la regle",
        "La regle et l'exception",
        "La norme",
        "La normalite",
        "Etre normal",
        "Le refus",
        "Dire non au systeme",
        "L'utopie concrete",
        "Les communautes alternatives",
        "Le retour a la terre",
        "La permaculture",
        "La fleur coupee",
        "L'ephemere",
        "La beaute ephemere",
        "Le fugace",
        "L'instant qui s'echappe",
        "Retenir le temps",
        "Le souvenir fige",
        "Les photos qu'on ne prend pas",
        "Le moment vecu plutot que photographie",
        "Vivre sans filtre",
        "Le naturel",
        "L'artifice",
        "Le masque",
        "Tomber le masque",
        "La vulnerabilite",
        "Montrer sa fragilite",
        "La force dans la fragilite",
        "Le cristal et l'acier",
        "Ne pas ceder",
        "Le desir",
        "Le desir mimietique",
        "Vouloir ce qu'on n'a pas",
        "La reverie",
        "Rever eveille",
        "L'imaginaire",
        "L'utopie",
        "Le monde ideal",
        "Construire un monde meilleur",
        "L'optimisme versus le realisme",
        "Le pessimisme francais",
        "Le declinisme",
        "La France est-elle en declin",
        "La grandeur de la France",
        "Le rayonnement culturel",
        "Le voyage interieur",
        "Partir pour mieux revenir",
        "Le savoir",
        "La connaissance",
        "L'ignorance",
        "Savoir qu'on ne sait rien",
        "La sagesse",
        "La philosophie au quotidien",
        "Philosopher en marchant",
        "La promenade philosophique",
        "Le silence",
        "Contempler",
        "L'art de ne rien faire",
        "Ne rien faire",
        "L'oisivete est-elle un vice",
        "Le droit a la paresse revisited",
        "La passion est-elle un piege",
        "Vivre en marge",
        "La marginalite",
        "L'artiste maudit",
        "Le poete fauche",
        "La boheme artistique",
        "Le grenier d'artiste",
        "La marge",
        "Le quotidien poetique",
        "La poesie du reel",
        "Le realisme poetique",
        "Le regard poetique",
        "Voir la beaute partout",
        "La beaute cachee",
        "La beaute du geste",
        "Le geste gratuit",
        "L'acte gratuit",
        "Le crime gratuit de Gide",
        "La litterature et la morale",
        "Faut-il separer l'oeuvre de l'artiste",
        "L'artiste et son epoque",
        "L'art pour l'art",
        "L'utilite de l'art",
        "L'art change-t-il le monde",
        "La beaute sauvera-t-elle le monde",
        "L'esthetique",
        "Le beau et le laid",
        "Le kitsch",
        "Le mauvais gout",
        "Le bon gout",
        "Les gouts et les couleurs",
        "Le snobisme culturel",
        "La culture populaire",
        "La culture savante",
        "Le fosse culturel",
        "La culture de masse",
        "La culture de niche",
        "L'underground",
        "L'alternatif",
        "Le mainstream",
        "Suivre le troupeau",
        "Aller a contre-courant",
        "La rebellion",
        "Trouver l'extraordinaire dans l'ordinaire",
        "L'intimite",
        "La liberte du vent",
        "Le temps qui ralentit",
        "L'ennui creatif",
        "L'ennui est-il necessaire",
        "Le cinema francais",
        "La marche comme meditation",
        "Le calme",
        "La paix interieure",
        "La serenite",
        "Le contentement",
        "L'euphorie passagere",
        "L'allegresse",
        "La joie",
        "Le bonheur malgre tout",
        "Le bonheur absurde",
        "Il faut imaginer Sisyphe heureux",
        "Le mythe de Sisyphe",
        "Vivre avec l'absurde",
        "L'absurde",
        "La raison d'etre",
        "A quoi sert la vie",
        "Le sens de la vie",
        "La quete de sens",
        "La quete de soi",
        "La transformation personnelle",
        "Se reinventer",
        "L'identite est-elle fixe",
        "L'identite",
        "L'enracinement",
        "Le citoyen du monde",
        "L'ouverture au monde",
        "Le repli sur soi",
        "Le regard sur l'etranger",
        "L'etranger",
        "L'accueil",
        "La main tendue",
        "Construire des ponts",
        "Le mur entre les gens",
        "Ce qui nous separe",
        "Ce qui nous unit",
        "La condition humaine",
        "L'universel et le particulier",
        "Y a-t-il des verites universelles",
        "Le relativisme",
        "L'ambiguite morale",
        "La zone grise",
        "Le confort moral",
        "L'alibi moral",
        "La bonne conscience",
        "La mauvaise conscience",
        "La culpabilite",
        "Les consequences de ses actes",
        "L'ethique personnelle",
        "Le syndrome de Peter Pan",
        "L'age adulte est-il une illusion",
        "L'amour et la liberte",
        "Aimer sans posseder",
        "L'usure du temps sur l'amour",
        "Etre seul sans etre solitaire",
        "La difference entre seul et solitaire",
        "L'ermite moderne",
        "L'interdependance",
        "Le tissu social",
        "La cohesion sociale",
        "Vivre sans l'approbation des autres",
        "La liberte interieure",
        "L'autonomie",
        "L'argent fait-il le bonheur",
        "L'argent et les rapports humains",
        "La justice sociale",
        "L'equite",
        "Le merite",
        "La dette envers les generations passees",
        "La responsabilite envers les generations futures",
        "Le monde qu'on laisse",
        "L'empreinte ecologique",
        "Le destin versus le libre arbitre",
        "Le libre arbitre",
        "Le pouvoir de la volonte",
        "La limite",
        "L'echappee solitaire",
        "Le contre-la-montre",
        "L'effort solitaire",
        "La nuit porte conseil",
        "Le reve lucide",
        "Les demons interieurs",
        "Faire face a ses demons",
        "L'ombre et la lumiere",
        "Le clair-obscur",
        "La dualite",
        "Le yin et le yang a la francaise",
        "La mesure",
        "La demesure",
        "L'exces",
        "Vivre intensement",
        "La passion devoranante",
        "Le feu interieur",
        "La flamme",
        "La flamme qui s'eteint",
        "Rallumer la flamme",
        "L'espoir tetu",
        "Le desespoir",
        "L'optimisme de la volonte",
        "Le pessimisme de l'intelligence",
        "L'intelligence du coeur",
        "Penser dans une autre langue",
        "Le mot intraduisible",
        "La traduction est-elle trahison",
        "Traduttore, traditore",
        "La semantique",
        "La definition des mots",
        "L'angoisse existentielle",
        "L'anxiete moderne",
        "Le stress permanent",
        "La lenteur volontaire",
        "Prendre le temps de vivre",
        "Le futur",
        "Le renouveau",
        "La ponctualite est-elle une vertu",
        "L'attente de quelqu'un",
        "L'amitie est-elle plus forte",
        "L'intelligence de la main",
        "La desertification des campagnes",
        "Restaurer ou moderniser",
        "L'ancien et le moderne",
        "La promiscuite urbaine",
        "La solitude en ville",
        "Seul dans la foule",
        "Le temps qui passe",
        "La confiance en soi",
        "L'estime de soi",
        "Le regard des autres",
        "Le jugement",
        "La peur du ridicule",
        "L'heroisme ordinaire",
        "Les heros du quotidien",
        "La nostalgie du temps d'avant",
        "C'etait mieux avant",
        "Les coutumes qui disparaissent",
        "L'heritage culinaire",
        "La transmission",
        "L'empathie",
        "La compassion",
        "La trahison",
        "Le pardon",
        "Tomber et se relever",
        "Apprendre de ses erreurs",
        "Le droit a l'erreur",
        "La perfectionnisme",
        "L'authenticite",
        "Etre soi-meme",
        "Le masque social",
        "Les apparences",
        "Sauver les apparences",
        "L'image de soi en ligne",
        "La zone de confort",
        "Sortir de sa zone de confort",
        "La raison versus le coeur",
        "Suivre son coeur",
        "La voix interieure",
        "L'introspection",
        "Se connaitre soi-meme",
        "La consommation responsable",
        "Consommer moins mais mieux",
        "La maturite",
        "La responsabilite",
        "Assumer ses choix",
        "Transmettre des valeurs",
        "Les valeurs",
        "La morale",
        "La solitude choisie",
        "La solitude subie",
        "Le besoin de l'autre",
        "Le lien social",
        "Le sentiment d'appartenance",
        "Appartenir a un groupe",
        "Le besoin de reconnaissance",
        "L'independance",
        "L'independance financiere",
        "Les inegalites",
        "L'heritage",
        "L'heritage culturel",
        "L'heritage familial",
        "Ce qu'on transmet",
        "Le rechauffement climatique",
        "La transition ecologique",
        "L'abstention",
        "Le devoir civique",
        "Le debat public",
        "La force mentale",
        "La preparation mentale",
        "Le depassement de soi",
        "Repousser ses limites",
        "L'insomnie",
        "Les pensees de la nuit",
        "L'equilibre",
        "Le juste milieu",
        "La melancolie",
        "La melancolie douce",
        "La resilience",
        "L'echec formateur",
        "L'anticipation",
        "L'impatience",
        "La gratitude"
    ]
};
