topicsByLang.en = {
    easy: [
        "Coffee shops at 7 a.m.",
        "Old passwords",
        "Being the youngest in the room",
        "Being the oldest in the room",
        "Voice memos",
        "Cracked phone screens",
        "Group chats",
        "Moving furniture",
        "Small talk",
        "Running in the rain",
        "Public transportation",
        "Waiting for test results",
        "Handshakes",
        "Parallel parking",
        "Libraries",
        "Snowstorms",
        "Electric scooters",
        "Eye contact",
        "Compliments",
        "Quiet people",
        "Loud people",
        "The last slice of pizza",
        "The first paycheck",
        "Social media",
        "Health",
        "Clutter",
        "Rest",
        "The smell of old books",
        "Airplane mode",
        "Being on hold",
        "The color yellow",
        "Broken umbrellas",
        "Window seats",
        "Paper cuts",
        "Road trips",
        "Name tags",
        "Awkward hugs",
        "Monday mornings",
        "Friday afternoons",
        "Expired coupons",
        "Deleted photos",
        "The mute button",
        "Being copied on an email",
        "Surprise parties",
        "Nicknames",
        "Running late",
        "Overpacking",
        "Curtains",
        "Standing ovations",
        "Whispering",
        "Sarcasm",
        "Accents",
        "Texting vs calling",
        "Autocorrect mistakes",
        "Complaining",
        "Celebrations",
        "The first snowfall",
        "Summer nights",
        "Empty notebooks",
        "Alarm clocks",
        "Online reviews",
        "Traffic jams",
        "Green lights",
        "Haircuts",
        "Losing your keys",
        "Houseplants",
        "Interruptions",
        "Stretching before a run",
        "Cold showers",
        "Gym mirrors",
        "Making eye contact with strangers",
        "Rainy Sundays",
        "The smell of coffee",
        "Budget airlines",
        "Fine print",
        "Dead batteries",
        "Birthday candles",
        "Inside voices",
        "Being ignored",
        "Long lines",
        "Free samples",
        "Open tabs",
        "Algorithm feeds",
        "Breaking routines",
        "First apartments",
        "Neighbors",
        "Community events",
        "Public speeches",
        "Mic checks",
        "Impulse purchases",
        "Icebreakers",
        "Early mornings",
        "The last train home",
        "Streetlights",
        "Group projects",
        "Silence in elevators",
        "Weather apps",
        "Burned toast",
        "Handwritten notes",
        "Spam emails",
        "Saying goodbye",
        "Saying hello",
        "Superstitions",
        "Loud rooms",
        "Quiet rooms",
        "Background noise",
        "Time zones",
        "Missed flights",
        "Window shopping",
        "Multitasking",
        "Night walks",
        "The junk drawer",
        "Lost socks",
        "The snooze button",
        "Grocery lists",
        "Leftovers",
        "Tangled earbuds",
        "The kitchen sink",
        "Takeout containers",
        "Spare change",
        "The checkout line",
        "Vending machines",
        "Elevator music",
        "Post-it notes",
        "Bookmarks",
        "The welcome mat",
        "Doorbells",
        "Jigsaw puzzles",
        "Board games",
        "The remote control",
        "Hotel room keys",
        "The last page of a book",
        "Moving boxes",
        "The smell of fresh laundry",
        "Kitchen timers",
        "Old receipts",
        "Gas station coffee",
        "The rearview mirror",
        "Speed bumps",
        "Toll booths",
        "Parking meters",
        "The waiting room",
        "Hospital cafeterias",
        "Airplane armrests",
        "Carry-on luggage",
        "The middle seat",
        "Departure boards",
        "Baggage claim",
        "The revolving door",
        "Hotel breakfasts",
        "The do-not-disturb sign",
        "Clean sheets",
        "The thermostat war",
        "Fluorescent lights",
        "The water cooler",
        "Sticky keyboards",
        "Swivel chairs",
        "Whiteboards",
        "The office microwave",
        "Shared refrigerators",
        "The printer that always jams",
        "The pen that works",
        "The pen that doesn't",
        "Reusable grocery bags",
        "The shopping cart with one bad wheel",
        "Fitting rooms",
        "Price tags",
        "Gift receipts",
        "Screen time reports",
        "Password managers",
        "The robot voice on customer service",
        "Voice assistants",
        "Smart home devices",
        "Double texting",
        "The three dots",
        "Virtual backgrounds",
        "Sunday evenings",
        "The golden hour",
        "The last day of summer",
        "The first day of school",
        "The last day of school",
        "New Year's resolutions",
        "Empty parking lots at night",
        "Libraries at closing time",
        "Airports at dawn",
        "Train stations",
        "Bus stops",
        "Park benches",
        "Rooftops",
        "The childhood bedroom",
        "The kitchen table",
        "The front porch",
        "The driveway",
        "Highways at night",
        "Country roads",
        "City sidewalks",
        "Crosswalks",
        "Bridges",
        "Tunnels",
        "Hospital waiting rooms",
        "Barbershops",
        "Elevator pitches",
        "Talking to yourself",
        "Participation trophies",
        "First place",
        "Second place",
        "Last place",
        "Beginner's luck",
        "Gossip",
        "The morning routine",
        "The night routine",
        "The first cup of coffee",
        "The last meal of the day",
        "Midnight snacks",
        "Sunday cleaning",
        "The phone check first thing in the morning",
        "Reading before bed",
        "To-do lists",
        "Walking after dinner",
        "The shower thought",
        "The tip jar",
        "Splitting the bill",
        "The friend who never pays",
        "Comfort food",
        "Home-cooked meals",
        "Eating alone",
        "Cooking for someone",
        "Cold pizza for breakfast",
        "Birthday cake",
        "Tea vs coffee",
        "Street food",
        "Pop quizzes",
        "Homework",
        "Cramming",
        "The all-nighter",
        "The library card",
        "The seating chart",
        "The kids' table",
        "Thank-you notes",
        "The family recipe",
        "Sore losers",
        "Gracious winners",
        "Good sportsmanship",
        "Singing alone in the car",
        "Dancing when nobody's watching",
        "Laughing at your own joke",
        "The yawn during a meeting",
        "The sneeze that won't come",
        "The hiccup that won't stop",
        "The itch you can't reach",
        "The name on the tip of your tongue",
        "The word you can't remember",
        "The thing you walked into the room to get",
        "The errand you forgot",
        "The package you forgot you ordered",
        "The subscription you forgot to cancel",
        "The money you found in old jeans",
        "The coin on the sidewalk",
        "The wishing well",
        "The birthday wish",
        "Knocking on wood",
        "Crossing your fingers",
        "The blanket you still have",
        "The stuffed animal in the closet",
        "The childhood drawing",
        "The trophy gathering dust",
        "The medal in the drawer",
        "Old photographs",
        "The toy you never threw away",
        "Handwriting",
        "The doodle in the margin",
        "Sticky notes on the bathroom mirror",
        "The refrigerator door",
        "Magnets from places you've been",
        "Souvenirs",
        "The postcard you meant to send",
        "Pen pals",
        "The stamps you collected",
        "Yearbooks",
        "Home videos",
        "The song that takes you back",
        "The playlist from that summer",
        "The movie that defined your childhood",
        "The game you used to play",
        "The restaurant that closed",
        "The receipt at the bottom of your bag",
        "The umbrella you always forget",
        "The wallet you left at home",
        "The alarm you set but didn't need",
        "Report cards",
        "The first stretch in the morning",
        "Walking in nature",
        "The sound of rain",
        "Thunderstorms",
        "Sunsets",
        "Sunrises",
        "The ocean",
        "Mountains",
        "Forests",
        "The sound of birds",
        "The first warm day of spring",
        "The smell of rain on hot pavement",
        "Moonlight",
        "Stargazing",
        "Wildflowers",
        "Old trees",
        "Fallen leaves",
        "The sound of wind",
        "Fog",
        "Fire",
        "Rivers",
        "Physical exhaustion",
        "The gym at 5 a.m.",
        "Skipping the gym",
        "The news cycle",
        "The American dream",
        "Student debt",
        "The cost of college",
        "Charity",
        "Volunteering",
        "Coincidences",
        "Rain on a wedding day",
        "The recipe passed down",
        "The meal that reminds you of home",
        "Fast food guilt",
        "Cooking as therapy",
        "The meal you ruined",
        "The meal you perfected",
        "The subject you hated",
        "The subject that surprised you",
        "Graduation",
        "The learning curve",
        "Muscle memory",
        "Gut feelings",
        "The table for one",
        "The morning rush",
        "The night owl",
        "The early bird",
        "The alarm you slept through",
        "The meeting you forgot",
        "The birthday you remembered",
        "The birthday you forgot",
        "The favor you owe",
        "The door held open",
        "The smile from a stranger",
        "The nod of acknowledgment",
        "The wave you weren't sure was for you",
        "The compliment from a stranger",
        "The unread book on your nightstand",
        "The plant you forgot to water",
        "The password you can't remember",
        "The phone call you keep postponing",
        "The drawer you're afraid to open",
        "The closet you've been meaning to clean",
        "The email sitting in your drafts",
        "The gift that meant more than it cost",
        "The outfit you save for special occasions",
        "The shoes that hurt but look good",
        "The voicemail you haven't listened to",
        "The notification you swiped away",
        "The scar with a story",
        "The doodle you drew during a meeting",
        "The note in the margin",
        "The underlined sentence",
        "The dog-eared page",
        "Borrowed books you never returned",
        "The library fine",
        "The late fee",
        "The grace period",
        "The wallflower",
        "The life of the party",
        "The designated driver",
        "The last one standing",
        "The first one to leave",
        "The one who always stays too long",
        "The Irish goodbye",
        "The French exit",
        "The letter in the mailbox",
        "The free trial that wasn't free",
        "The hidden cost",
        "The unexpected bill",
        "The lucky charm",
        "The comfort object",
        "The report card your parents kept",
        "The certificate on the wall",
        "The diploma nobody asks about",
        "The conversation you rehearse in the shower",
        "The argument you win in your head",
        "The monologue in the car",
        "The joke only you understand",
        "Inside jokes with yourself",
        "The laugh that escapes at the wrong time",
        "The tear that falls at the wrong time",
        "The task you keep moving to tomorrow",
        "The sign nobody reads",
        "The warning nobody heeds",
        "The test that turned out easy",
        "The stranger who changed your day",
        "Ordinary days",
        "The mundane",
        "The draft in the room",
        "The chill you can't explain",
        "Contracts",
        "The friend who drifted away",
        "The text you never sent",
        "Anxiety before a phone call",
        "The friend you only see at funerals",
        "Midnight conversations",
        "Seasons changing",
        "Silence in nature",
        "The opening line",
        "The closing line",
        "Rehearsing in the mirror",
        "Nervous laughter",
        "The shaky voice",
        "The teacher who believed in you",
        "The teacher who didn't",
        "The friend from kindergarten",
        "Your first heartbreak",
        "Your first best friend",
        "The neighborhood that changed",
        "The way things used to be",
        "Journaling",
        "The list that never shrinks",
        "Procrastination rituals",
        "The nap that changes everything",
        "Morning pages",
        "The ritual you never skip",
        "Photographs you wish you took",
        "Old journals",
        "The things you saved but never look at",
        "Love letters",
        "The letter you never sent",
        "The voicemail you keep",
        "The smell that triggers a memory",
        "The teacher who changed your life",
        "The tattoo you'd never get",
        "The tattoo that means something",
        "The second opinion",
        "The yes-man",
        "The quiet observer",
        "The loud participant",
        "The slow fade",
        "The clean break",
        "The unfinished conversation",
        "The phone that rings at the wrong time",
        "The knock on the door you weren't expecting",
        "The wish on a star",
        "Making promises to the moon",
        "The four-leaf clover",
        "The broken mirror",
        "Walking under a ladder",
        "The bio you wrote about yourself",
        "The photo you use everywhere",
        "Rush hour",
        "The afternoon slump",
        "The milestone",
        "Random acts of kindness",
        "Childhood nicknames",
        "The first draft",
        "The final draft",
        "Behind the scenes",
        "The unfinished project",
        "The abandoned draft",
        "Blank canvases",
        "Fresh starts",
        "The movie you watched alone",
        "The concert in the rain",
        "The song on repeat",
        "Asking for directions",
        "Looking back",
        "Looking forward",
        "The surprise you didn't want",
        "The gift you didn't ask for",
        "Holiday expectations",
        "Holiday reality",
        "New traditions",
        "The secret ingredient",
        "The missing piece",
        "The puzzle you gave up on",
        "The thank you that came too late",
        "The apology that came too early"
    ],
    medium: [
        "The fear of being average",
        "Apologizing too much",
        "The last 5% of effort",
        "Starting over",
        "Confidence vs arrogance",
        "Being misunderstood",
        "Burnout",
        "Overthinking",
        "The first day at a new job",
        "Cancel culture",
        "Nostalgia",
        "Silence after an argument",
        "Ambition",
        "Envy",
        "The feeling before a presentation",
        "Being ghosted",
        "Winning an argument",
        "Losing gracefully",
        "Risk",
        "Regret",
        "Boredom",
        "Long-distance friendships",
        "Deadlines",
        "Failure",
        "Procrastination",
        "Being underestimated",
        "Being overestimated",
        "Authority",
        "Rejection",
        "Perfectionism",
        "Escaping corporate life",
        "Mentorship",
        "Competition",
        "Discipline",
        "Motivation",
        "Consistency",
        "Independence",
        "Freedom",
        "Quitting",
        "Staying",
        "Growth",
        "Reinvention",
        "Imposter syndrome",
        "Leadership",
        "Following",
        "Responsibility",
        "Loyalty",
        "Trust",
        "Privacy",
        "Comparison",
        "Jealousy",
        "Aging",
        "Resilience",
        "Patience",
        "Luck",
        "Preparation",
        "Courage",
        "Comfort zones",
        "Failure in public",
        "Success in private",
        "Minimalism",
        "Hustle culture",
        "Community",
        "Loneliness",
        "Saying no",
        "Saying yes",
        "First impressions",
        "Last impressions",
        "The sound of typing",
        "Secrets",
        "Mispronouncing someone's name",
        "Awkward silences",
        "Being second choice",
        "Loyalty tests",
        "Gratitude",
        "Productivity hacks",
        "Refund policies",
        "Applause",
        "Being talked over",
        "Whisper networks",
        "Stage fright",
        "Canceled subscriptions",
        "The unsubscribe button",
        "Vision boards",
        "Late-night thoughts",
        "Dreams you remember",
        "Dreams you forget",
        "Parallel lives",
        "Missed opportunities",
        "Being the only one who notices",
        "Predictability",
        "Surprise success",
        "Underpromising",
        "Overdelivering",
        "Mediocrity",
        "Greatness",
        "Promotional discounts",
        "High expectations",
        "Minimal effort",
        "White lies",
        "Compliments you don't believe",
        "Apologies you don't accept",
        "Authority figures",
        "Breaking rules",
        "Following rules",
        "Curiosity",
        "Cynicism",
        "Patting yourself on the back",
        "Overexplaining",
        "Underexplaining",
        "Sincerity",
        "Rituals",
        "Growing pains",
        "Reinventing yourself",
        "Being overlooked",
        "Being spotlighted",
        "Mentors",
        "Rivals",
        "Silent competition",
        "Learning slowly",
        "Learning fast",
        "Pressure",
        "Peace",
        "Waiting for permission",
        "Taking initiative",
        "Applause that feels fake",
        "Honest feedback",
        "Brutal honesty",
        "Soft skills",
        "Hard truths",
        "Choosing stability",
        "Choosing risk",
        "Being replaced",
        "Being irreplaceable",
        "Borrowed time",
        "Side projects",
        "Burning bridges",
        "Building bridges",
        "Being present",
        "Daydreaming",
        "Private victories",
        "Public failures",
        "Hidden talent",
        "Untapped potential",
        "Loyalty to yourself",
        "Small improvements",
        "Big promises",
        "Being dependable",
        "Being unpredictable",
        "Learning to rest",
        "Earning trust",
        "Breaking trust",
        "Self-doubt",
        "Self-respect",
        "Emotional exhaustion",
        "Guilt after saying no",
        "Relief after letting go",
        "Feeling stuck",
        "Feeling restless",
        "Emotional walls",
        "Vulnerability",
        "Shame",
        "Pride",
        "Contentment",
        "Calm after chaos",
        "Inner peace",
        "Emotional maturity",
        "Joy in small things",
        "Nervous energy",
        "The comfort of routine",
        "Serenity",
        "Controlled chaos",
        "Quiet confidence",
        "Misplaced anger",
        "Toxic positivity",
        "People who only call when they need something",
        "The art of listening",
        "Unsolicited advice",
        "Being the reliable one",
        "Being the forgotten one",
        "The friend who always cancels",
        "Conditional love",
        "Unconditional love",
        "Setting boundaries",
        "Crossing boundaries",
        "Keeping score in relationships",
        "One-sided friendships",
        "The friend who tells you the truth",
        "People-pleasing",
        "The need for approval",
        "Emotional labor in friendships",
        "Choosing your circle wisely",
        "Friends by proximity",
        "Friends by choice",
        "Love languages",
        "Growing apart",
        "Growing together",
        "Promises between friends",
        "Chosen family",
        "Office politics",
        "The meeting that could have been an email",
        "Working from home",
        "The commute",
        "Career pivots",
        "Passion vs stability",
        "The Sunday scaries",
        "Toxic work culture",
        "Good bosses",
        "Bad bosses",
        "Workplace friendships",
        "Leaving a job you love",
        "Staying at a job you hate",
        "Salary negotiations",
        "Job interviews",
        "Rejection letters",
        "The gap on your resume",
        "Doing work that matters",
        "Work-life balance",
        "Emails after hours",
        "Quiet quitting",
        "Corporate jargon",
        "Performance reviews",
        "The coworker who takes credit",
        "Building something from scratch",
        "Networking",
        "Starting a business",
        "Remote work loneliness",
        "Being micromanaged",
        "The promotion you didn't want",
        "The meeting no one prepared for",
        "Your work email voice",
        "The out-of-office reply",
        "Workplace burnout",
        "Progress vs perfection",
        "The plateau",
        "Self-awareness",
        "Self-sabotage",
        "Self-compassion",
        "Building new habits",
        "Finding your voice",
        "Losing your voice",
        "Wasted talent",
        "Late bloomers",
        "Early success",
        "Learning from failure",
        "Starting before you're ready",
        "Finishing what you start",
        "Knowing when to walk away",
        "Doom scrolling",
        "Digital detox",
        "The blue light of your phone at 2 a.m.",
        "Notifications you ignore",
        "The email you're afraid to open",
        "Two-factor authentication",
        "Data privacy",
        "Targeted ads",
        "The internet at 3 a.m.",
        "Online shopping at midnight",
        "Influencer culture",
        "Going viral",
        "Keyboard warriors",
        "Comment sections",
        "Read receipts",
        "Zoom fatigue",
        "The camera-off meeting",
        "The hot mic moment",
        "Saying too much",
        "Saying too little",
        "Reading the room",
        "Tone of voice",
        "Body language",
        "Active listening",
        "Selective hearing",
        "The comeback story",
        "The underdog",
        "Peaking too early",
        "Peaking too late",
        "Measuring success",
        "Health scares",
        "Sleep deprivation",
        "The body you live in",
        "Aging gracefully",
        "Aging reluctantly",
        "Generational differences",
        "Tradition",
        "Progress",
        "Misinformation",
        "Groupthink",
        "The majority opinion",
        "The minority opinion",
        "The loudest voice in the room",
        "The quietest voice in the room",
        "Complacency",
        "Privilege",
        "Representation",
        "Stereotypes",
        "Labels",
        "Urban loneliness",
        "Rural isolation",
        "The education system",
        "The value of a degree",
        "Self-taught vs formally educated",
        "Activism",
        "Performative activism",
        "The bandwagon effect",
        "The court of public opinion",
        "The cost of living",
        "Saving vs spending",
        "Financial literacy",
        "The emergency fund",
        "Living paycheck to paycheck",
        "Generational wealth",
        "Credit card debt",
        "Rent vs own",
        "The thing you bought and never used",
        "Retail therapy",
        "Overcommitting",
        "The personal best",
        "Breaking your own record",
        "Beating your own expectations",
        "Raising the bar",
        "Moving the goalposts",
        "The moving target",
        "Missing the mark",
        "Instinct vs logic",
        "Intuition",
        "Hindsight",
        "Blind spots",
        "Tunnel vision",
        "The elephant in the room",
        "Open secrets",
        "Rumors",
        "Lost in translation",
        "Language barriers",
        "Code-switching",
        "Wearing masks",
        "Dropping the mask",
        "Faking it till you make it",
        "The confident walk",
        "Dressing for the job you want",
        "The outfit that changes your mood",
        "The poker face",
        "Doubling down",
        "Playing it safe",
        "Playing with fire",
        "Walking on eggshells",
        "Band-aid solutions",
        "Root causes",
        "Prevention vs cure",
        "Better late than never",
        "Quality time",
        "Decision fatigue",
        "Analysis paralysis",
        "Pacing yourself",
        "Going all in",
        "Holding back",
        "Second wind",
        "Momentum",
        "The breakthrough",
        "The grade that didn't reflect your effort",
        "Learning by doing",
        "Learning by failing",
        "The lecture you'll never forget",
        "Lifelong learning",
        "Self-education",
        "Online courses you never finished",
        "Friends you outgrow",
        "Friends who outgrow you",
        "The apology that never came",
        "Forgiving without an apology",
        "People who make you feel small",
        "People who make you feel seen",
        "Holding grudges",
        "Letting go of grudges",
        "People you meet once but never forget",
        "Outgrowing your hometown",
        "The sibling dynamic",
        "Being the black sheep",
        "The politics of family dinners",
        "Reconnecting after years apart",
        "Relationships that survive distance",
        "Relationships that don't survive change",
        "The conversation you keep replaying",
        "The weight of family expectations",
        "The myth of dream jobs",
        "Passion projects that become obligations",
        "Mentoring someone who surpasses you",
        "The corner office myth",
        "The person you were five years ago",
        "The person you want to become",
        "Unlearning",
        "Outgrowing your own beliefs",
        "Admitting you were wrong",
        "The quarter-life crisis",
        "The midlife crisis",
        "The thing you keep putting off",
        "The hobby you abandoned",
        "The hobby you picked up too late",
        "The instrument you stopped playing",
        "The language you tried to learn",
        "The dance you never learned",
        "The skill you wished you had",
        "The talent you take for granted",
        "The praise that made you uncomfortable",
        "The moment you realized you were the adult",
        "The first bill in your name",
        "Calling your parents for advice",
        "Becoming your parents",
        "Outgrowing a phase",
        "The phase that stuck",
        "The trend you followed",
        "The trend you missed",
        "Being ahead of your time",
        "Being behind the times",
        "The comfort of familiar things",
        "The thrill of the unknown",
        "The safety net",
        "The leap of faith",
        "Trusting the process",
        "Questioning the process",
        "The plan that fell apart",
        "The plan that came together",
        "Winging it",
        "Overthinking the plan",
        "The shortcut that wasn't",
        "The long way around",
        "Scenic routes",
        "Detours",
        "Dead ends",
        "U-turns",
        "The halfway point",
        "The home stretch",
        "Finish lines",
        "Starting lines",
        "The marathon vs the sprint",
        "The reserve tank",
        "Giving up too soon",
        "Holding on too long",
        "Micro-decisions",
        "Big decisions",
        "The cost of convenience",
        "The price of comfort",
        "The cost of saying yes",
        "The power of saying no",
        "Discipline when no one is watching",
        "Being the backup plan",
        "The feeling of progress",
        "The fear of being judged",
        "Feeling like a fraud",
        "Unexpected sadness",
        "Bittersweet memories",
        "The relief of crying",
        "Numbness",
        "Emotional hangovers",
        "The guilt of doing nothing",
        "The guilt of doing well",
        "Celebrating too early",
        "Not celebrating enough",
        "The victory no one saw",
        "The failure everyone remembers",
        "Achievements that don't fulfill you",
        "The goal you abandoned",
        "The goal you're afraid to set",
        "The highlight reel",
        "Terms and conditions no one reads",
        "The cart you never checked out",
        "The blank mind at the podium",
        "Finding your stage voice",
        "The joke that landed",
        "The joke that didn't",
        "Speaking without notes",
        "Speaking to one person vs a thousand",
        "Speaking from the heart",
        "The way things could have been",
        "Meditation",
        "Productivity rituals",
        "The investment that paid off",
        "The scarcity mindset",
        "The dissenting voice",
        "The contrarian",
        "The voice of reason",
        "The optimist in the room",
        "The pessimist at the table",
        "The realist nobody listens to",
        "The dreamer everyone dismisses",
        "The messy ending",
        "The deadline you met",
        "The deadline you missed",
        "Keeping promises",
        "Breaking promises",
        "Writer's block",
        "Creative blocks",
        "The tipping point",
        "The breaking point",
        "The straw that broke the camel's back",
        "Paying it forward",
        "The advice you ignored",
        "The advice that saved you",
        "The warning you didn't heed",
        "Old traditions you've outgrown",
        "Competition with yourself"
    ],
    hard: [
        "Existential dread",
        "Identity",
        "Time",
        "The life you didn't choose",
        "The illusion of progress",
        "Becoming who you avoided becoming",
        "The fear of being forgotten",
        "The fear of missing out",
        "The fear of being too late",
        "The fear of being too much",
        "The fear of not being enough",
        "Feeling invisible",
        "Feeling too visible",
        "The weight of expectations",
        "The anxiety of waiting",
        "Hope without evidence",
        "The urge to run away",
        "The fear of success",
        "The heaviness of secrets",
        "The weight of an unspoken apology",
        "Feeling homesick in your own city",
        "Tears you hold back",
        "Anger that protects you",
        "Anger that destroys you",
        "The sadness after a celebration",
        "The fear of vulnerability",
        "The power of a good conversation",
        "Conversations that change you",
        "Arguments that should have been conversations",
        "The loneliness of being surrounded by people",
        "The difference between love and attachment",
        "The resume that tells a different story",
        "The version of yourself you left behind",
        "The moment you stopped pretending",
        "The cost of growth",
        "Boundaries with yourself",
        "Promises you made to yourself",
        "Promises you broke to yourself",
        "Letting go of who you used to be",
        "The weight of potential",
        "Who you become when no one is watching",
        "The gap between intention and action",
        "Outgrowing your comfort zone",
        "Your relationship with your past self",
        "The habit that changed your life",
        "The book that changed your perspective",
        "The conversation that shifted everything",
        "The courage to be bad at something new",
        "Your evolving definition of success",
        "The lesson that took too long to learn",
        "The meaning of home",
        "The meaning of success",
        "The difference between lonely and alone",
        "The difference between hearing and listening",
        "The line between confidence and delusion",
        "The difference between giving up and letting go",
        "The illusion of control",
        "The paradox of choice",
        "The weight of privilege",
        "Things money can't buy",
        "The currency of attention",
        "The value of boredom",
        "The power of silence",
        "The danger of certainty",
        "Living in the present",
        "Planning for the future",
        "Dwelling on the past",
        "The stories we tell ourselves",
        "The lies we believe",
        "The truths we avoid",
        "The comfort of denial",
        "Free will vs fate",
        "Nature vs nurture",
        "The pursuit of happiness",
        "The acceptance of sadness",
        "The myth of balance",
        "The art of storytelling",
        "The power of a pause",
        "The voice in your head",
        "The words you swallow",
        "The words you wish you said",
        "The text you overthought",
        "The conversation you've been avoiding",
        "Compliments you deflect",
        "Criticism you accept too easily",
        "The apology that means nothing",
        "The apology that changes everything",
        "The illusion of overnight success",
        "The ten-year overnight success",
        "The success that costs your health",
        "The failure that saved your life",
        "Winning the wrong game",
        "Redefining winning",
        "The gap between effort and results",
        "Creating vs consuming",
        "Teaching vs learning",
        "Giving vs receiving",
        "Holding on vs letting go",
        "The easy choice vs the right choice",
        "Short-term pain vs long-term gain",
        "Comfort vs growth",
        "Depth vs breadth",
        "Quality vs quantity",
        "Tradition vs innovation",
        "Rules vs instinct",
        "The confident pause",
        "The price of happiness",
        "Free things that cost you",
        "The argument you had with your younger self",
        "The letter you'd write to your future self",
        "The advice you'd give your younger self",
        "The thing you wish someone told you sooner",
        "The lesson you had to learn the hard way",
        "The boundary you should have set earlier",
        "The yes that should have been a no",
        "The no that changed your life",
        "The moment you chose yourself",
        "The moment you didn't",
        "The menu with too many options",
        "The one-item menu",
        "Simplicity",
        "Complexity",
        "The race you didn't sign up for",
        "Last legs",
        "The wall",
        "Breaking through",
        "The art of letting go",
        "The art of showing up",
        "The art of saying nothing",
        "The art of waiting",
        "The art of starting",
        "The art of finishing",
        "The art of failing",
        "The art of recovering",
        "The art of reinvention",
        "The art of being wrong",
        "Extraordinary moments",
        "The magnificent",
        "The in-between",
        "Liminal spaces",
        "Transition periods",
        "Growing seasons",
        "Dormant seasons",
        "The harvest",
        "Planting seeds",
        "Seeds that never sprouted",
        "Gardens you forgot to water",
        "Roots",
        "Branches",
        "Rings on a tree",
        "The age of a scar",
        "Scars that tell stories",
        "Wounds that still ache",
        "Healing that happens in silence",
        "Recovery nobody sees",
        "The invisible load",
        "The mental load",
        "Carrying other people's problems",
        "Putting yourself first",
        "The guilt of putting yourself first",
        "The necessity of selfishness",
        "Selfish vs self-aware",
        "Boundaries that feel like walls",
        "Walls that feel like safety",
        "The cage you built yourself",
        "The key you already have",
        "The door that was always open",
        "The window you forgot to close",
        "The warmth of a kind word",
        "The sting of a careless one",
        "Words that linger",
        "Words that fade",
        "The sentence that changed everything",
        "The question nobody asks",
        "The question everyone avoids",
        "The answer you already know",
        "The answer that raises more questions",
        "Certainty",
        "Uncertainty",
        "The comfort of not knowing",
        "The burden of knowing too much",
        "Ignorance vs bliss",
        "Awareness vs peace",
        "The price of truth",
        "The cost of silence",
        "The currency of trust",
        "The economy of attention",
        "The inflation of praise",
        "The deflation of criticism",
        "Words that heal",
        "Words that wound",
        "The story you tell at parties",
        "The story you only tell yourself",
        "The story that isn't yours to tell",
        "The narrative you've outgrown",
        "Rewriting your story",
        "Editing your past",
        "Drafting your future",
        "The rough draft of your life",
        "The revision you're afraid to make",
        "The character you play",
        "The character you are",
        "The role you were given",
        "The role you chose",
        "The script you didn't write",
        "Going off-script",
        "Improvising",
        "The unplanned moment",
        "The planned spontaneity",
        "The rehearsed authenticity",
        "Being real",
        "Being polite",
        "Being both",
        "The mask of professionalism",
        "The uniform you wear",
        "The hat you put on",
        "Wearing too many hats",
        "Putting one hat down",
        "The title that doesn't fit",
        "The label you can't shake",
        "The box people put you in",
        "Breaking out of the box",
        "The mold you were poured into",
        "Breaking the mold",
        "The pattern you keep repeating",
        "The cycle you can't break",
        "The loop you're stuck in",
        "Breaking the loop",
        "The spiral",
        "The upward spiral",
        "The downward spiral",
        "Inertia",
        "Friction",
        "The resistance",
        "The moment it clicks",
        "The lightbulb moment",
        "The slow realization",
        "The sudden clarity",
        "The fog lifting",
        "The fog rolling in",
        "Clarity after confusion",
        "Confusion after clarity",
        "The calm before the storm",
        "The storm before the calm",
        "The eye of the storm",
        "Standing still",
        "Moving forward",
        "Taking a step back",
        "The view from a distance",
        "The view up close",
        "Zooming in",
        "Zooming out",
        "The wide angle",
        "The narrow focus",
        "Tunnel vision vs peripheral vision",
        "The blind spot you didn't know you had",
        "The mirror you avoid",
        "The mirror that tells the truth",
        "The reflection you don't recognize",
        "Aging in photographs",
        "The face in the mirror vs the face in your mind",
        "The gap between how you see yourself and how others see you",
        "The opinion that shouldn't matter but does",
        "The validation you seek",
        "The validation you give yourself",
        "Internal scorecards",
        "External scorecards",
        "Keeping up appearances",
        "Dropping the act",
        "The relief of being honest",
        "The weight of pretending",
        "The energy it takes to be someone else",
        "The freedom of being yourself",
        "The risk of being yourself",
        "The reward of being yourself",
        "Authenticity as a luxury",
        "Authenticity as a practice",
        "The first time you stood up for yourself",
        "The first time you walked away",
        "The first time you spoke up",
        "The first time you stayed quiet on purpose",
        "Choosing silence",
        "Choosing your battles",
        "The battle you should have fought",
        "The battle you should have walked away from",
        "The hill you're willing to die on",
        "The hill that isn't worth it",
        "Picking your moments",
        "The moment that picked you",
        "Being chosen",
        "Choosing yourself",
        "The seat at the table",
        "Building your own table",
        "The invitation that never came",
        "The party you weren't invited to",
        "The party you chose to skip",
        "The gathering that felt like home",
        "The room that felt like a trap",
        "The exit you've been eyeing",
        "The entrance you keep walking past",
        "The threshold",
        "The before and after",
        "The pivot",
        "The plot twist you didn't see coming",
        "The ending you didn't expect",
        "The beginning you almost missed",
        "The middle that felt endless",
        "The intermission",
        "The encore",
        "The standing ovation you earned",
        "The applause you didn't need",
        "The silence that said everything",
        "The noise that said nothing",
        "Signal vs noise",
        "The message in the static",
        "The promise you made at midnight",
        "Muscle memory from a past life",
        "Handwriting that reveals character",
        "The devil's advocate",
        "The title on your business card",
        "The version of you on LinkedIn",
        "The version of you at a job interview",
        "The version of you at a reunion",
        "The version of you at 2 a.m.",
        "The version of you on a good day",
        "The version of you on the worst day",
        "The version of you that only your dog knows",
        "The version of you in your mother's eyes",
        "The speech you give to no one",
        "The project that grew bigger than expected",
        "The commitment that outlasted the enthusiasm",
        "The tradition that lost its meaning",
        "The rule that makes no sense",
        "The policy nobody follows",
        "The obvious answer nobody gives",
        "The simple solution nobody tries",
        "The complicated answer to a simple question",
        "The simple answer to a complicated question",
        "The question you've been afraid to ask",
        "The question you already know the answer to",
        "The test you weren't prepared for",
        "The hard thing that turned out to be worth it",
        "The easy thing that turned out to be a trap",
        "The compliment that stuck with you for years",
        "The insult you never got over",
        "The small gesture that meant everything",
        "The effort nobody noticed",
        "The detail nobody appreciated",
        "The thing you did that mattered more than you knew",
        "The impact you'll never see",
        "The ripple you started",
        "The chain you broke",
        "The cycle you ended",
        "The door you closed",
        "The door you opened for someone else",
        "The hand you extended",
        "The bridge you built without knowing",
        "The wall you tore down",
        "The space you held for someone",
        "The room you made at the table",
        "The voice you amplified",
        "The story you helped someone tell",
        "The courage you borrowed",
        "The strength you didn't know you had",
        "The kindness you forgot you showed",
        "The difference between giving and giving up",
        "The difference between patience and passivity",
        "The difference between peace and numbness",
        "The difference between rest and avoidance",
        "The difference between alone and lonely",
        "The distance between almost and enough",
        "The distance between good enough and great",
        "The space between thinking and doing",
        "The moment between sleep and waking",
        "The pause between lightning and thunder",
        "The beat before the chorus",
        "The breath before you speak",
        "The silence before the applause",
        "The exhale after it's over",
        "The real you",
        "The public you",
        "The private you",
        "The professional you",
        "The weekend you",
        "The version of you that exists in other people's stories",
        "The pep talk you gave yourself",
        "The pep talk you needed",
        "Your biggest cheerleader",
        "Your harshest critic",
        "The inner critic",
        "The inner child",
        "The adult in the room",
        "Solid ground",
        "The slow burn",
        "The quick fix",
        "The clock ticking",
        "Running out of time",
        "Making time",
        "Killing time",
        "The countdown",
        "The eleventh hour",
        "Dreams vs reality",
        "The wake-up call",
        "The consequences you didn't expect",
        "The domino effect",
        "The ripple effect",
        "The butterfly effect",
        "Unintended consequences",
        "The aftermath",
        "The blank page",
        "The cursor blinking",
        "The spark",
        "The flame",
        "The embers",
        "Rising from the ashes",
        "Starting from zero",
        "The foundation",
        "The missing link",
        "The final piece",
        "The benefit of the doubt",
        "The kindness of strangers",
        "The criticism from a friend",
        "The sign you were looking for",
        "Patterns you start to notice",
        "The thing everyone knows but nobody says",
        "The room after everyone leaves",
        "The silence after the music stops",
        "The moment before the results",
        "The pause between songs",
        "The space between breaths",
        "The gap between who you are and who you pretend to be",
        "The distance between wanting and doing",
        "The line between helping and enabling",
        "The line between honest and hurtful",
        "The line between humble and invisible",
        "The line between busy and productive",
        "The line between passion and obsession",
        "The difference between a house and a home",
        "The difference between surviving and living",
        "The difference between apologizing and changing",
        "The difference between being nice and being kind",
        "The empty chair",
        "The hand you didn't shake",
        "The door you didn't open",
        "The road not taken",
        "The path of least resistance",
        "Swimming against the current",
        "Treading water",
        "The deep end",
        "The weight of a decision",
        "The lightness of acceptance",
        "The gravity of silence",
        "Window reflections",
        "Shadows",
        "Echoes",
        "Footprints",
        "The version no one saw",
        "The idea that woke you up",
        "The dream you wrote down",
        "The goal you kept secret",
        "The secret you kept too long",
        "Second chances",
        "Third chances",
        "The last chance",
        "Borrowed confidence",
        "Earned respect",
        "Inherited beliefs",
        "Chosen values",
        "Unwritten rules",
        "Written rules no one follows",
        "The fine line",
        "The gray area",
        "Black and white thinking",
        "Nuance",
        "Context",
        "Perspective",
        "The bigger picture",
        "The small print",
        "The exception to the rule",
        "The risk that paid off",
        "The risk that didn't",
        "The safe bet",
        "The wild card",
        "The dark horse",
        "The long shot",
        "The sure thing that wasn't",
        "The plot twist",
        "The cliffhanger",
        "The chapter you'd skip",
        "The chapter you'd reread",
        "The book you couldn't finish",
        "The song you can't listen to anymore",
        "The soundtrack of your life",
        "The handshake that lingered",
        "Keeping a secret for someone else",
        "The courage to ask for help",
        "The wrong turn that led somewhere beautiful",
        "The beauty of doing nothing",
        "The permission to be average",
        "Excellence vs perfection",
        "Diminishing returns",
        "The point of no return",
        "Turning points",
        "Crossroads",
        "The bridge you've already crossed",
        "Water under the bridge",
        "Rock bottom",
        "The climb back up",
        "The view from the top",
        "The view from the bottom",
        "Autopilot",
        "The emergency exit",
        "The restart button",
        "The undo button",
        "The original vs the copy",
        "The beautiful mess",
        "Organized chaos"
    ]
};
